/* $TOG: XmStrDefs.ht /main/2 1997/06/18 17:50:15 samborn $ */
#ifndef _XmStrDefs_h_
#define _XmStrDefs_h_

#include <X11/Intrinsic.h>

#ifndef _XmConst
#define _XmConst /**/
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* $TOG: makestrs.c /main/11 1998/02/06 11:24:15 kaleb $ */
/* This file is automatically generated. */
/* Default ABI version -- Do not edit */
/* TOG: xmstring.list /main/5 1997/06/20 08:37:02 samborn */

#ifdef XMSTRINGDEFINES
#define XmS ""
#define XmCAccelerator "Accelerator"
#define XmCAcceleratorText "AcceleratorText"
#define XmCAdjustLast "AdjustLast"
#define XmCAdjustMargin "AdjustMargin"
#define XmCAlignment "Alignment"
#define XmCAllowOverlap "AllowOverlap"
#define XmCAllowUnusedSpace "AllowUnusedSpace"
#define XmCAnimationMask "AnimationMask"
#define XmCAnimationPixmap "AnimationPixmap"
#define XmCAnimationPixmapDepth "AnimationPixmapDepth"
#define XmCAnimationStyle "AnimationStyle"
#define XmCApplyLabelString "ApplyLabelString"
#define XmCArmCallback "ArmCallback"
#define XmCArmColor "ArmColor"
#define XmCArmPixmap "ArmPixmap"
#define XmCArrowDirection "ArrowDirection"
#define XmCAttachment "Attachment"
#define XmCAudibleWarning "AudibleWarning"
#define XmCAutoShowCursorPosition "AutoShowCursorPosition"
#define XmCAutoUnmanage "AutoUnmanage"
#define XmCAutomaticSelection "AutomaticSelection"
#define XmCAvailability "Availability"
#define XmCBackgroundPixmap "BackgroundPixmap"
#define XmCBlendModel "BlendModel"
#define XmCBlinkRate "BlinkRate"
#define XmCBottomShadowColor "BottomShadowColor"
#define XmCBottomShadowPixmap "BottomShadowPixmap"
#define XmCButtonAcceleratorText "ButtonAcceleratorText"
#define XmCButtonAccelerators "ButtonAccelerators"
#define XmCButtonCount "ButtonCount"
#define XmCButtonFontList "ButtonFontList"
#define XmCButtonMnemonicCharSets "ButtonMnemonicCharSets"
#define XmCButtonMnemonics "ButtonMnemonics"
#define XmCButtonSet "ButtonSet"
#define XmCButtonType "ButtonType"
#define XmCButtons "Buttons"
#define XmCCancelLabelString "CancelLabelString"
#define XmCChildHorizontalAlignment "ChildHorizontalAlignment"
#define XmCChildHorizontalSpacing "ChildHorizontalSpacing"
#define XmCChildPlacement "ChildPlacement"
#define XmCChildType "ChildType"
#define XmCChildVerticalAlignment "ChildVerticalAlignment"
#define XmCChildren "Children"
#define XmCClientData "ClientData"
#define XmCClipWindow "ClipWindow"
#define XmCColumns "Columns"
#define XmCCommandWindow "CommandWindow"
#define XmCCommandWindowLocation "CommandWindowLocation"
#define XmCConvertProc "ConvertProc"
#define XmCCursorBackground "CursorBackground"
#define XmCCursorForeground "CursorForeground"
#define XmCCursorPosition "CursorPosition"
#define XmCCursorPositionVisible "CursorPositionVisible"
#define XmCDarkThreshold "DarkThreshold"
#define XmCDecimalPoints "DecimalPoints"
#define XmCDefaultButtonShadowThickness "DefaultButtonShadowThickness"
#define XmCDefaultButtonType "DefaultButtonType"
#define XmCDefaultCopyCursorIcon "DefaultCopyCursorIcon"
#define XmCDefaultFontList "DefaultFontList"
#define XmCDefaultInvalidCursorIcon "DefaultInvalidCursorIcon"
#define XmCDefaultLinkCursorIcon "DefaultLinkCursorIcon"
#define XmCDefaultMoveCursorIcon "DefaultMoveCursorIcon"
#define XmCDefaultNoneCursorIcon "DefaultNoneCursorIcon"
#define XmCDefaultPosition "DefaultPosition"
#define XmCDefaultSourceCursorIcon "DefaultSourceCursorIcon"
#define XmCDefaultValidCursorIcon "DefaultValidCursorIcon"
#define XmCDeleteResponse "DeleteResponse"
#define XmCDesktopParent "DesktopParent"
#define XmCDialogStyle "DialogStyle"
#define XmCDialogTitle "DialogTitle"
#define XmCDialogType "DialogType"
#define XmCDirListItemCount "DirListItemCount"
#define XmCDirListItems "DirListItems"
#define XmCDirListLabelString "DirListLabelString"
#define XmCDirMask "DirMask"
#define XmCDirSearchProc "DirSearchProc"
#define XmCDirSpec "DirSpec"
#define XmCDirectory "Directory"
#define XmCDirectoryValid "DirectoryValid"
#define XmCDisarmCallback "DisarmCallback"
#define XmCDoubleClickInterval "DoubleClickInterval"
#define XmCDragContextClass "DragContextClass"
#define XmCDragDropFinishCallback "DragDropFinishCallback"
#define XmCDragIconClass "DragIconClass"
#define XmCDragInitiatorProtocolStyle "DragInitiatorProtocolStyle"
#define XmCDragMotionCallback "DragMotionCallback"
#define XmCDragOperations "DragOperations"
#define XmCDragOverMode "DragOverMode"
#define XmCDragProc "DragProc"
#define XmCDragReceiverProtocolStyle "DragReceiverProtocolStyle"
#define XmCDropProc "DropProc"
#define XmCDropRectangles "DropRectangles"
#define XmCDropSiteActivity "DropSiteActivity"
#define XmCDropSiteEnterCallback "DropSiteEnterCallback"
#define XmCDropSiteLeaveCallback "DropSiteLeaveCallback"
#define XmCDropSiteManagerClass "DropSiteManagerClass"
#define XmCDropSiteOperations "DropSiteOperations"
#define XmCDropSiteType "DropSiteType"
#define XmCDropStartCallback "DropStartCallback"
#define XmCDropTransferClass "DropTransferClass"
#define XmCDropTransfers "DropTransfers"
#define XmCEditable "Editable"
#define XmCEntryBorder "EntryBorder"
#define XmCEntryClass "EntryClass"
#define XmCExportTargets "ExportTargets"
#define XmCExposeCallback "ExposeCallback"
#define XmCExtensionType "ExtensionType"
#define XmCFileListItemCount "FileListItemCount"
#define XmCFileListItems "FileListItems"
#define XmCFileListLabelString "FileListLabelString"
#define XmCFileSearchProc "FileSearchProc"
#define XmCFileTypeMask "FileTypeMask"
#define XmCFillOnArm "FillOnArm"
#define XmCFillOnSelect "FillOnSelect"
#define XmCFilterLabelString "FilterLabelString"
#define XmCFontList "FontList"
#define XmCForegroundThreshold "ForegroundThreshold"
#define XmCHelpLabelString "HelpLabelString"
#define XmCHighlightColor "HighlightColor"
#define XmCHighlightOnEnter "HighlightOnEnter"
#define XmCHighlightPixmap "HighlightPixmap"
#define XmCHighlightThickness "HighlightThickness"
#define XmCHorizontalFontUnit "HorizontalFontUnit"
#define XmCHorizontalScrollBar "HorizontalScrollBar"
#define XmCHot "Hot"
#define XmCICCHandle "ICCHandle"
#define XmCImportTargets "ImportTargets"
#define XmCIncrement "Increment"
#define XmCIncremental "Incremental"
#define XmCIndicatorOn "IndicatorOn"
#define XmCIndicatorSize "IndicatorSize"
#define XmCIndicatorType "IndicatorType"
#define XmCInitialDelay "InitialDelay"
#define XmCInitialFocus "InitialFocus"
#define XmCInputCreate "InputCreate"
#define XmCInputMethod "InputMethod"
#define XmCInvalidCursorForeground "InvalidCursorForeground"
#define XmCIsAligned "IsAligned"
#define XmCIsHomogeneous "IsHomogeneous"
#define XmCItemCount "ItemCount"
#define XmCItems "Items"
#define XmCKeyboardFocusPolicy "KeyboardFocusPolicy"
#define XmCLabelFontList "LabelFontList"
#define XmCLabelInsensitivePixmap "LabelInsensitivePixmap"
#define XmCLabelPixmap "LabelPixmap"
#define XmCLabelString "LabelString"
#define XmCLabelType "LabelType"
#define XmCLightThreshold "LightThreshold"
#define XmCListLabelString "ListLabelString"
#define XmCListMarginHeight "ListMarginHeight"
#define XmCListMarginWidth "ListMarginWidth"
#define XmCListSizePolicy "ListSizePolicy"
#define XmCListSpacing "ListSpacing"
#define XmCListUpdated "ListUpdated"
#define XmCLogicalParent "LogicalParent"
#define XmCMainWindowMarginHeight "MainWindowMarginHeight"
#define XmCMainWindowMarginWidth "MainWindowMarginWidth"
#define XmCMappingDelay "MappingDelay"
#define XmCMarginBottom "MarginBottom"
#define XmCMarginHeight "MarginHeight"
#define XmCMarginLeft "MarginLeft"
#define XmCMarginRight "MarginRight"
#define XmCMarginTop "MarginTop"
#define XmCMarginWidth "MarginWidth"
#define XmCMask "Mask"
#define XmCMaxItems "MaxItems"
#define XmCMaxLength "MaxLength"
#define XmCMaxValue "MaxValue"
#define XmCMaximum "Maximum"
#define XmCMenuBar "MenuBar"
#define XmCMenuPost "MenuPost"
#define XmCMenuWidget "MenuWidget"
#define XmCMessageProc "MessageProc"
#define XmCMessageWindow "MessageWindow"
#define XmCMinimizeButtons "MinimizeButtons"
#define XmCMinimum "Minimum"
#define XmCMnemonic "Mnemonic"
#define XmCMnemonicCharSet "MnemonicCharSet"
#define XmCMoveOpaque "MoveOpaque"
#define XmCMultiClick "MultiClick"
#define XmCMustMatch "MustMatch"
#define XmCMwmDecorations "MwmDecorations"
#define XmCMwmFunctions "MwmFunctions"
#define XmCMwmInputMode "MwmInputMode"
#define XmCMwmMenu "MwmMenu"
#define XmCMwmMessages "MwmMessages"
#define XmCNavigationType "NavigationType"
#define XmCNeedsMotion "NeedsMotion"
#define XmCNoMatchString "NoMatchString"
#define XmCNoResize "NoResize"
#define XmCNoneCursorForeground "NoneCursorForeground"
#define XmCNotifyProc "NotifyProc"
#define XmCNumChildren "NumChildren"
#define XmCNumColumns "NumColumns"
#define XmCNumDropRectangles "NumDropRectangles"
#define XmCNumDropTransfers "NumDropTransfers"
#define XmCNumExportTargets "NumExportTargets"
#define XmCNumImportTargets "NumImportTargets"
#define XmCOffset "Offset"
#define XmCOkLabelString "OkLabelString"
#define XmCOperationChangedCallback "OperationChangedCallback"
#define XmCOperationCursorIcon "OperationCursorIcon"
#define XmCOptionLabel "OptionLabel"
#define XmCOptionMnemonic "OptionMnemonic"
#define XmCOutputCreate "OutputCreate"
#define XmCPacking "Packing"
#define XmCPageIncrement "PageIncrement"
#define XmCPaneMaximum "PaneMaximum"
#define XmCPaneMinimum "PaneMinimum"
#define XmCPattern "Pattern"
#define XmCPendingDelete "PendingDelete"
#define XmCPopupEnabled "PopupEnabled"
#define XmCPositionIndex "PositionIndex"
#define XmCPostFromButton "PostFromButton"
#define XmCPostFromCount "PostFromCount"
#define XmCPostFromList "PostFromList"
#define XmCPreeditType "PreeditType"
#define XmCProcessingDirection "ProcessingDirection"
#define XmCPromptString "PromptString"
#define XmCProtocolCallback "ProtocolCallback"
#define XmCPushButtonEnabled "PushButtonEnabled"
#define XmCQualifySearchDataProc "QualifySearchDataProc"
#define XmCRadioAlwaysOne "RadioAlwaysOne"
#define XmCRadioBehavior "RadioBehavior"
#define XmCRecomputeSize "RecomputeSize"
#define XmCRectangles "Rectangles"
#define XmCRepeatDelay "RepeatDelay"
#define XmCResizeCallback "ResizeCallback"
#define XmCResizeHeight "ResizeHeight"
#define XmCResizePolicy "ResizePolicy"
#define XmCResizeWidth "ResizeWidth"
#define XmCRowColumnType "RowColumnType"
#define XmCRows "Rows"
#define XmCRubberPositioning "RubberPositioning"
#define XmCSashHeight "SashHeight"
#define XmCSashIndent "SashIndent"
#define XmCSashWidth "SashWidth"
#define XmCScaleHeight "ScaleHeight"
#define XmCScaleMultiple "ScaleMultiple"
#define XmCScaleWidth "ScaleWidth"
#define XmCScroll "Scroll"
#define XmCScrollBarDisplayPolicy "ScrollBarDisplayPolicy"
#define XmCScrollBarPlacement "ScrollBarPlacement"
#define XmCScrollSide "ScrollSide"
#define XmCScrolledWindowMarginHeight "ScrolledWindowMarginHeight"
#define XmCScrolledWindowMarginWidth "ScrolledWindowMarginWidth"
#define XmCScrollingPolicy "ScrollingPolicy"
#define XmCSelectColor "SelectColor"
#define XmCSelectInsensitivePixmap "SelectInsensitivePixmap"
#define XmCSelectPixmap "SelectPixmap"
#define XmCSelectThreshold "SelectThreshold"
#define XmCSelectedItemCount "SelectedItemCount"
#define XmCSelectedItems "SelectedItems"
#define XmCSelectionArrayCount "SelectionArrayCount"
#define XmCSelectionLabelString "SelectionLabelString"
#define XmCSelectionPolicy "SelectionPolicy"
#define XmCSeparatorOn "SeparatorOn"
#define XmCSeparatorType "SeparatorType"
#define XmCSet "Set"
#define XmCShadowThickness "ShadowThickness"
#define XmCShadowType "ShadowType"
#define XmCShellUnitType "ShellUnitType"
#define XmCShowArrows "ShowArrows"
#define XmCShowAsDefault "ShowAsDefault"
#define XmCShowSeparator "ShowSeparator"
#define XmCShowValue "ShowValue"
#define XmCSimpleCheckBox "SimpleCheckBox"
#define XmCSimpleMenuBar "SimpleMenuBar"
#define XmCSimpleOptionMenu "SimpleOptionMenu"
#define XmCSimplePopupMenu "SimplePopupMenu"
#define XmCSimplePulldownMenu "SimplePulldownMenu"
#define XmCSimpleRadioBox "SimpleRadioBox"
#define XmCSizePolicy "SizePolicy"
#define XmCSliderSize "SliderSize"
#define XmCSource "Source"
#define XmCSourceCursorIcon "SourceCursorIcon"
#define XmCSourceIsExternal "SourceIsExternal"
#define XmCSourcePixmapIcon "SourcePixmapIcon"
#define XmCSourceWidget "SourceWidget"
#define XmCSourceWindow "SourceWindow"
#define XmCSpacing "Spacing"
#define XmCStartTime "StartTime"
#define XmCStateCursorIcon "StateCursorIcon"
#define XmCStringDirection "StringDirection"
#define XmCTearOffModel "TearOffModel"
#define XmCTextFontList "TextFontList"
#define XmCTextString "TextString"
#define XmCTextValue "TextValue"
#define XmCTitleString "TitleString"
#define XmCTopCharacter "TopCharacter"
#define XmCTopItemPosition "TopItemPosition"
#define XmCTopLevelEnterCallback "TopLevelEnterCallback"
#define XmCTopLevelLeaveCallback "TopLevelLeaveCallback"
#define XmCTopShadowColor "TopShadowColor"
#define XmCTopShadowPixmap "TopShadowPixmap"
#define XmCTransferProc "TransferProc"
#define XmCTransferStatus "TransferStatus"
#define XmCTraversalOn "TraversalOn"
#define XmCTraversalType "TraversalType"
#define XmCTreeUpdateProc "TreeUpdateProc"
#define XmCTroughColor "TroughColor"
#define XmCUnitType "UnitType"
#define XmCUnpostBehavior "UnpostBehavior"
#define XmCUnselectPixmap "UnselectPixmap"
#define XmCUpdateSliderSize "UpdateSliderSize"
#define XmCUseAsyncGeometry "UseAsyncGeometry"
#define XmCUserData "UserData"
#define XmCValidCursorForeground "ValidCursorForeground"
#define XmCValueChangedCallback "ValueChangedCallback"
#define XmCValueWcs "ValueWcs"
#define XmCVerifyBell "VerifyBell"
#define XmCVerticalAlignment "VerticalAlignment"
#define XmCVerticalFontUnit "VerticalFontUnit"
#define XmCVerticalScrollBar "VerticalScrollBar"
#define XmCVisibleItemCount "VisibleItemCount"
#define XmCVisibleWhenOff "VisibleWhenOff"
#define XmCVisualPolicy "VisualPolicy"
#define XmCWhichButton "WhichButton"
#define XmCWordWrap "WordWrap"
#define XmCWorkWindow "WorkWindow"
#define XmCXmString "XmString"
#define XmNaccelerator "accelerator"
#define XmNacceleratorText "acceleratorText"
#define XmNactivateCallback "activateCallback"
#define XmNadjustLast "adjustLast"
#define XmNadjustMargin "adjustMargin"
#define XmNalignment "alignment"
#define XmNallowOverlap "allowOverlap"
#define XmNallowResize "allowResize"
#define XmNallowUnusedSpace "allowUnusedSpace"
#define XmNanimationMask "animationMask"
#define XmNanimationPixmap "animationPixmap"
#define XmNanimationPixmapDepth "animationPixmapDepth"
#define XmNanimationStyle "animationStyle"
#define XmNapplyCallback "applyCallback"
#define XmNapplyLabelString "applyLabelString"
#define XmNarmCallback "armCallback"
#define XmNarmColor "armColor"
#define XmNarmPixmap "armPixmap"
#define XmNarrowDirection "arrowDirection"
#define XmNattachment "attachment"
#define XmNaudibleWarning "audibleWarning"
#define XmNautoShowCursorPosition "autoShowCursorPosition"
#define XmNautoUnmanage "autoUnmanage"
#define XmNautomaticSelection "automaticSelection"
#define XmNavailability "availability"
#define XmNblendModel "blendModel"
#define XmNblinkRate "blinkRate"
#define XmNbottomAttachment "bottomAttachment"
#define XmNbottomOffset "bottomOffset"
#define XmNbottomPosition "bottomPosition"
#define XmNbottomShadowColor "bottomShadowColor"
#define XmNbottomShadowPixmap "bottomShadowPixmap"
#define XmNbottomWidget "bottomWidget"
#define XmNbrowseSelectionCallback "browseSelectionCallback"
#define XmNbuttonAcceleratorText "buttonAcceleratorText"
#define XmNbuttonAccelerators "buttonAccelerators"
#define XmNbuttonCount "buttonCount"
#define XmNbuttonFontList "buttonFontList"
#define XmNbuttonMnemonicCharSets "buttonMnemonicCharSets"
#define XmNbuttonMnemonics "buttonMnemonics"
#define XmNbuttonSet "buttonSet"
#define XmNbuttonType "buttonType"
#define XmNbuttons "buttons"
#define XmNcancelButton "cancelButton"
#define XmNcancelCallback "cancelCallback"
#define XmNcancelLabelString "cancelLabelString"
#define XmNcascadePixmap "cascadePixmap"
#define XmNcascadingCallback "cascadingCallback"
#define XmNchildHorizontalAlignment "childHorizontalAlignment"
#define XmNchildHorizontalSpacing "childHorizontalSpacing"
#define XmNchildPlacement "childPlacement"
#define XmNchildPosition "childPosition"
#define XmNchildType "childType"
#define XmNchildVerticalAlignment "childVerticalAlignment"
#define XmNclientData "clientData"
#define XmNclipWindow "clipWindow"
#define XmNcolumns "columns"
#define XmNcommand "command"
#define XmNcommandChangedCallback "commandChangedCallback"
#define XmNcommandEnteredCallback "commandEnteredCallback"
#define XmNcommandWindow "commandWindow"
#define XmNcommandWindowLocation "commandWindowLocation"
#define XmNconvertProc "convertProc"
#define XmNcursorBackground "cursorBackground"
#define XmNcursorForeground "cursorForeground"
#define XmNcursorPosition "cursorPosition"
#define XmNcursorPositionVisible "cursorPositionVisible"
#define XmNdarkThreshold "darkThreshold"
#define XmNdecimalPoints "decimalPoints"
#define XmNdecrementCallback "decrementCallback"
#define XmNdefaultActionCallback "defaultActionCallback"
#define XmNdefaultButton "defaultButton"
#define XmNdefaultButtonShadowThickness "defaultButtonShadowThickness"
#define XmNdefaultButtonType "defaultButtonType"
#define XmNdefaultCopyCursorIcon "defaultCopyCursorIcon"
#define XmNdefaultFontList "defaultFontList"
#define XmNdefaultInvalidCursorIcon "defaultInvalidCursorIcon"
#define XmNdefaultLinkCursorIcon "defaultLinkCursorIcon"
#define XmNdefaultMoveCursorIcon "defaultMoveCursorIcon"
#define XmNdefaultNoneCursorIcon "defaultNoneCursorIcon"
#define XmNdefaultPosition "defaultPosition"
#define XmNdefaultSourceCursorIcon "defaultSourceCursorIcon"
#define XmNdefaultValidCursorIcon "defaultValidCursorIcon"
#define XmNdeleteResponse "deleteResponse"
#define XmNdesktopParent "desktopParent"
#define XmNdialogStyle "dialogStyle"
#define XmNdialogTitle "dialogTitle"
#define XmNdialogType "dialogType"
#define XmNdirListItemCount "dirListItemCount"
#define XmNdirListItems "dirListItems"
#define XmNdirListLabelString "dirListLabelString"
#define XmNdirMask "dirMask"
#define XmNdirSearchProc "dirSearchProc"
#define XmNdirSpec "dirSpec"
#define XmNdirectory "directory"
#define XmNdirectoryValid "directoryValid"
#define XmNdisarmCallback "disarmCallback"
#define XmNdoubleClickInterval "doubleClickInterval"
#define XmNdragCallback "dragCallback"
#define XmNdragContextClass "dragContextClass"
#define XmNdragDropFinishCallback "dragDropFinishCallback"
#define XmNdragIconClass "dragIconClass"
#define XmNdragInitiatorProtocolStyle "dragInitiatorProtocolStyle"
#define XmNdragMotionCallback "dragMotionCallback"
#define XmNdragOperations "dragOperations"
#define XmNdragOverMode "dragOverMode"
#define XmNdragProc "dragProc"
#define XmNdragReceiverProtocolStyle "dragReceiverProtocolStyle"
#define XmNdropFinishCallback "dropFinishCallback"
#define XmNdropProc "dropProc"
#define XmNdropRectangles "dropRectangles"
#define XmNdropSiteActivity "dropSiteActivity"
#define XmNdropSiteEnterCallback "dropSiteEnterCallback"
#define XmNdropSiteLeaveCallback "dropSiteLeaveCallback"
#define XmNdropSiteManagerClass "dropSiteManagerClass"
#define XmNdropSiteOperations "dropSiteOperations"
#define XmNdropSiteType "dropSiteType"
#define XmNdropStartCallback "dropStartCallback"
#define XmNdropTransferClass "dropTransferClass"
#define XmNdropTransfers "dropTransfers"
#define XmNeditMode "editMode"
#define XmNeditable "editable"
#define XmNentryAlignment "entryAlignment"
#define XmNentryBorder "entryBorder"
#define XmNentryCallback "entryCallback"
#define XmNentryClass "entryClass"
#define XmNentryVerticalAlignment "entryVerticalAlignment"
#define XmNexportTargets "exportTargets"
#define XmNexposeCallback "exposeCallback"
#define XmNextendedSelectionCallback "extendedSelectionCallback"
#define XmNextensionType "extensionType"
#define XmNfileListItemCount "fileListItemCount"
#define XmNfileListItems "fileListItems"
#define XmNfileListLabelString "fileListLabelString"
#define XmNfileSearchProc "fileSearchProc"
#define XmNfileTypeMask "fileTypeMask"
#define XmNfillOnArm "fillOnArm"
#define XmNfillOnSelect "fillOnSelect"
#define XmNfilterLabelString "filterLabelString"
#define XmNfocusCallback "focusCallback"
#define XmNfocusMovedCallback "focusMovedCallback"
#define XmNfocusPolicyChanged "focusPolicyChanged"
#define XmNfontList "fontList"
#define XmNforegroundThreshold "foregroundThreshold"
#define XmNfractionBase "fractionBase"
#define XmNgainPrimaryCallback "gainPrimaryCallback"
#define XmNhelpCallback "helpCallback"
#define XmNhelpLabelString "helpLabelString"
#define XmNhighlightColor "highlightColor"
#define XmNhighlightOnEnter "highlightOnEnter"
#define XmNhighlightPixmap "highlightPixmap"
#define XmNhighlightThickness "highlightThickness"
#define XmNhistoryItemCount "historyItemCount"
#define XmNhistoryItems "historyItems"
#define XmNhistoryMaxItems "historyMaxItems"
#define XmNhistoryVisibleItemCount "historyVisibleItemCount"
#define XmNhorizontalFontUnit "horizontalFontUnit"
#define XmNhorizontalScrollBar "horizontalScrollBar"
#define XmNhorizontalSpacing "horizontalSpacing"
#define XmNhotX "hotX"
#define XmNhotY "hotY"
#define XmNiccHandle "iccHandle"
#define XmNimportTargets "importTargets"
#define XmNincrement "increment"
#define XmNincrementCallback "incrementCallback"
#define XmNincremental "incremental"
#define XmNindicatorOn "indicatorOn"
#define XmNindicatorSize "indicatorSize"
#define XmNindicatorType "indicatorType"
#define XmNinitialDelay "initialDelay"
#define XmNinitialFocus "initialFocus"
#define XmNinputCallback "inputCallback"
#define XmNinputCreate "inputCreate"
#define XmNinputMethod "inputMethod"
#define XmNinvalidCursorForeground "invalidCursorForeground"
#define XmNisAligned "isAligned"
#define XmNisHomogeneous "isHomogeneous"
#define XmNitemCount "itemCount"
#define XmNitems "items"
#define XmNkeyboardFocusPolicy "keyboardFocusPolicy"
#define XmNlabelFontList "labelFontList"
#define XmNlabelInsensitivePixmap "labelInsensitivePixmap"
#define XmNlabelPixmap "labelPixmap"
#define XmNlabelString "labelString"
#define XmNlabelType "labelType"
#define XmNleftAttachment "leftAttachment"
#define XmNleftOffset "leftOffset"
#define XmNleftPosition "leftPosition"
#define XmNleftWidget "leftWidget"
#define XmNlightThreshold "lightThreshold"
#define XmNlineSpace "lineSpace"
#define XmNlistItemCount "listItemCount"
#define XmNlistItems "listItems"
#define XmNlistLabelString "listLabelString"
#define XmNlistMarginHeight "listMarginHeight"
#define XmNlistMarginWidth "listMarginWidth"
#define XmNlistSizePolicy "listSizePolicy"
#define XmNlistSpacing "listSpacing"
#define XmNlistUpdated "listUpdated"
#define XmNlistVisibleItemCount "listVisibleItemCount"
#define XmNlogicalParent "logicalParent"
#define XmNlosePrimaryCallback "losePrimaryCallback"
#define XmNlosingFocusCallback "losingFocusCallback"
#define XmNmainWindowMarginHeight "mainWindowMarginHeight"
#define XmNmainWindowMarginWidth "mainWindowMarginWidth"
#define XmNmapCallback "mapCallback"
#define XmNmappingDelay "mappingDelay"
#define XmNmargin "margin"
#define XmNmarginBottom "marginBottom"
#define XmNmarginHeight "marginHeight"
#define XmNmarginLeft "marginLeft"
#define XmNmarginRight "marginRight"
#define XmNmarginTop "marginTop"
#define XmNmarginWidth "marginWidth"
#define XmNmask "mask"
#define XmNmaxLength "maxLength"
#define XmNmaximum "maximum"
#define XmNmenuAccelerator "menuAccelerator"
#define XmNmenuBar "menuBar"
#define XmNmenuCursor "menuCursor"
#define XmNmenuHelpWidget "menuHelpWidget"
#define XmNmenuHistory "menuHistory"
#define XmNmenuPost "menuPost"
#define XmNmessageAlignment "messageAlignment"
#define XmNmessageProc "messageProc"
#define XmNmessageString "messageString"
#define XmNmessageWindow "messageWindow"
#define XmNminimizeButtons "minimizeButtons"
#define XmNminimum "minimum"
#define XmNmnemonic "mnemonic"
#define XmNmnemonicCharSet "mnemonicCharSet"
#define XmNmodifyVerifyCallback "modifyVerifyCallback"
#define XmNmodifyVerifyCallbackWcs "modifyVerifyCallbackWcs"
#define XmNmotionVerifyCallback "motionVerifyCallback"
#define XmNmoveOpaque "moveOpaque"
#define XmNmultiClick "multiClick"
#define XmNmultipleSelectionCallback "multipleSelectionCallback"
#define XmNmustMatch "mustMatch"
#define XmNmwmDecorations "mwmDecorations"
#define XmNmwmFunctions "mwmFunctions"
#define XmNmwmInputMode "mwmInputMode"
#define XmNmwmMenu "mwmMenu"
#define XmNmwmMessages "mwmMessages"
#define XmNnavigationType "navigationType"
#define XmNneedsMotion "needsMotion"
#define XmNnoMatchCallback "noMatchCallback"
#define XmNnoMatchString "noMatchString"
#define XmNnoResize "noResize"
#define XmNnoneCursorForeground "noneCursorForeground"
#define XmNnotifyProc "notifyProc"
#define XmNnumColumns "numColumns"
#define XmNnumDropRectangles "numDropRectangles"
#define XmNnumDropTransfers "numDropTransfers"
#define XmNnumExportTargets "numExportTargets"
#define XmNnumImportTargets "numImportTargets"
#define XmNnumRectangles "numRectangles"
#define XmNoffsetX "offsetX"
#define XmNoffsetY "offsetY"
#define XmNokCallback "okCallback"
#define XmNokLabelString "okLabelString"
#define XmNoperationChangedCallback "operationChangedCallback"
#define XmNoperationCursorIcon "operationCursorIcon"
#define XmNoptionLabel "optionLabel"
#define XmNoptionMnemonic "optionMnemonic"
#define XmNoutputCreate "outputCreate"
#define XmNpacking "packing"
#define XmNpageDecrementCallback "pageDecrementCallback"
#define XmNpageIncrement "pageIncrement"
#define XmNpageIncrementCallback "pageIncrementCallback"
#define XmNpaneMaximum "paneMaximum"
#define XmNpaneMinimum "paneMinimum"
#define XmNpattern "pattern"
#define XmNpendingDelete "pendingDelete"
#define XmNpopupEnabled "popupEnabled"
#define XmNpositionIndex "positionIndex"
#define XmNpostFromButton "postFromButton"
#define XmNpostFromCount "postFromCount"
#define XmNpostFromList "postFromList"
#define XmNpreeditType "preeditType"
#define XmNprocessingDirection "processingDirection"
#define XmNpromptString "promptString"
#define XmNprotocolCallback "protocolCallback"
#define XmNpushButtonEnabled "pushButtonEnabled"
#define XmNqualifySearchDataProc "qualifySearchDataProc"
#define XmNradioAlwaysOne "radioAlwaysOne"
#define XmNradioBehavior "radioBehavior"
#define XmNrealizeCallback "realizeCallback"
#define XmNrecomputeSize "recomputeSize"
#define XmNrectangles "rectangles"
#define XmNrefigureMode "refigureMode"
#define XmNrepeatDelay "repeatDelay"
#define XmNresizable "resizable"
#define XmNresizeCallback "resizeCallback"
#define XmNresizeHeight "resizeHeight"
#define XmNresizePolicy "resizePolicy"
#define XmNresizeWidth "resizeWidth"
#define XmNrightAttachment "rightAttachment"
#define XmNrightOffset "rightOffset"
#define XmNrightPosition "rightPosition"
#define XmNrightWidget "rightWidget"
#define XmNrowColumnType "rowColumnType"
#define XmNrows "rows"
#define XmNrubberPositioning "rubberPositioning"
#define XmNsashHeight "sashHeight"
#define XmNsashIndent "sashIndent"
#define XmNsashShadowThickness "sashShadowThickness"
#define XmNsashWidth "sashWidth"
#define XmNscaleHeight "scaleHeight"
#define XmNscaleMultiple "scaleMultiple"
#define XmNscaleWidth "scaleWidth"
#define XmNscrollBarDisplayPolicy "scrollBarDisplayPolicy"
#define XmNscrollBarPlacement "scrollBarPlacement"
#define XmNscrollHorizontal "scrollHorizontal"
#define XmNscrollLeftSide "scrollLeftSide"
#define XmNscrollTopSide "scrollTopSide"
#define XmNscrollVertical "scrollVertical"
#define XmNscrolledWindowMarginHeight "scrolledWindowMarginHeight"
#define XmNscrolledWindowMarginWidth "scrolledWindowMarginWidth"
#define XmNscrollingPolicy "scrollingPolicy"
#define XmNselectColor "selectColor"
#define XmNselectInsensitivePixmap "selectInsensitivePixmap"
#define XmNselectPixmap "selectPixmap"
#define XmNselectThreshold "selectThreshold"
#define XmNselectedItemCount "selectedItemCount"
#define XmNselectedItems "selectedItems"
#define XmNselectionArrayCount "selectionArrayCount"
#define XmNselectionLabelString "selectionLabelString"
#define XmNselectionPolicy "selectionPolicy"
#define XmNseparatorOn "separatorOn"
#define XmNseparatorType "separatorType"
#define XmNset "set"
#define XmNshadow "shadow"
#define XmNshadowThickness "shadowThickness"
#define XmNshadowType "shadowType"
#define XmNshellUnitType "shellUnitType"
#define XmNshowArrows "showArrows"
#define XmNshowAsDefault "showAsDefault"
#define XmNshowSeparator "showSeparator"
#define XmNshowValue "showValue"
#define XmNsimpleCallback "simpleCallback"
#define XmNsingleSelectionCallback "singleSelectionCallback"
#define XmNsizePolicy "sizePolicy"
#define XmNskipAdjust "skipAdjust"
#define XmNsliderSize "sliderSize"
#define XmNsource "source"
#define XmNsourceCursorIcon "sourceCursorIcon"
#define XmNsourceIsExternal "sourceIsExternal"
#define XmNsourcePixmapIcon "sourcePixmapIcon"
#define XmNsourceWidget "sourceWidget"
#define XmNsourceWindow "sourceWindow"
#define XmNspacing "spacing"
#define XmNspotLocation "spotLocation"
#define XmNstartTime "startTime"
#define XmNstateCursorIcon "stateCursorIcon"
#define XmNstringDirection "stringDirection"
#define XmNsubMenuId "subMenuId"
#define XmNsymbolPixmap "symbolPixmap"
#define XmNtearOffMenuActivateCallback "tearOffMenuActivateCallback"
#define XmNtearOffMenuDeactivateCallback "tearOffMenuDeactivateCallback"
#define XmNtearOffModel "tearOffModel"
#define XmNtextAccelerators "textAccelerators"
#define XmNtextColumns "textColumns"
#define XmNtextFontList "textFontList"
#define XmNtextString "textString"
#define XmNtextTranslations "textTranslations"
#define XmNtextValue "textValue"
#define XmNtitleString "titleString"
#define XmNtoBottomCallback "toBottomCallback"
#define XmNtoPositionCallback "toPositionCallback"
#define XmNtoTopCallback "toTopCallback"
#define XmNtopAttachment "topAttachment"
#define XmNtopCharacter "topCharacter"
#define XmNtopItemPosition "topItemPosition"
#define XmNtopLevelEnterCallback "topLevelEnterCallback"
#define XmNtopLevelLeaveCallback "topLevelLeaveCallback"
#define XmNtopOffset "topOffset"
#define XmNtopPosition "topPosition"
#define XmNtopShadowColor "topShadowColor"
#define XmNtopShadowPixmap "topShadowPixmap"
#define XmNtopWidget "topWidget"
#define XmNtransferProc "transferProc"
#define XmNtransferStatus "transferStatus"
#define XmNtraversalCallback "traversalCallback"
#define XmNtraversalOn "traversalOn"
#define XmNtraversalType "traversalType"
#define XmNtraverseObscuredCallback "traverseObscuredCallback"
#define XmNtreeUpdateProc "treeUpdateProc"
#define XmNtroughColor "troughColor"
#define XmNunitType "unitType"
#define XmNunmapCallback "unmapCallback"
#define XmNunpostBehavior "unpostBehavior"
#define XmNunselectPixmap "unselectPixmap"
#define XmNupdateSliderSize "updateSliderSize"
#define XmNuseAsyncGeometry "useAsyncGeometry"
#define XmNuserData "userData"
#define XmNvalidCursorForeground "validCursorForeground"
#define XmNvalueChangedCallback "valueChangedCallback"
#define XmNvalueWcs "valueWcs"
#define XmNverifyBell "verifyBell"
#define XmNverticalFontUnit "verticalFontUnit"
#define XmNverticalScrollBar "verticalScrollBar"
#define XmNverticalSpacing "verticalSpacing"
#define XmNvisibleItemCount "visibleItemCount"
#define XmNvisibleWhenOff "visibleWhenOff"
#define XmNvisualPolicy "visualPolicy"
#define XmNwhichButton "whichButton"
#define XmNwordWrap "wordWrap"
#define XmNworkWindow "workWindow"
#define XmRAlignment "Alignment"
#define XmRAnimationMask "AnimationMask"
#define XmRAnimationPixmap "AnimationPixmap"
#define XmRAnimationStyle "AnimationStyle"
#define XmRArrowDirection "ArrowDirection"
#define XmRAtomList "AtomList"
#define XmRAttachment "Attachment"
#define XmRAudibleWarning "AudibleWarning"
#define XmRAvailability "Availability"
#define XmRBackgroundPixmap "BackgroundPixmap"
#define XmRBlendModel "BlendModel"
#define XmRBooleanDimension "BooleanDimension"
#define XmRBottomShadowPixmap "BottomShadowPixmap"
#define XmRButtonType "ButtonType"
#define XmRCallbackProc "CallbackProc"
#define XmRChar "Char"
#define XmRCharSetTable "CharSetTable"
#define XmRChildHorizontalAlignment "ChildHorizontalAlignment"
#define XmRChildPlacement "ChildPlacement"
#define XmRChildType "ChildType"
#define XmRChildVerticalAlignment "ChildVerticalAlignment"
#define XmRCommandWindowLocation "CommandWindowLocation"
#define XmRCompoundText "CompoundText"
#define XmRDefaultButtonType "DefaultButtonType"
#define XmRDeleteResponse "DeleteResponse"
#define XmRDialogStyle "DialogStyle"
#define XmRDialogType "DialogType"
#define XmRDoubleClickInterval "DoubleClickInterval"
#define XmRDragInitiatorProtocolStyle "DragInitiatorProtocolStyle"
#define XmRDragReceiverProtocolStyle "DragReceiverProtocolStyle"
#define XmRDropSiteActivity "DropSiteActivity"
#define XmRDropSiteOperations "DropSiteOperations"
#define XmRDropSiteType "DropSiteType"
#define XmRDropTransfers "DropTransfers"
#define XmRExtensionType "ExtensionType"
#define XmRFileTypeMask "FileTypeMask"
#define XmRFontList "FontList"
#define XmRGadgetPixmap "GadgetPixmap"
#define XmRHighlightPixmap "HighlightPixmap"
#define XmRHorizontalDimension "HorizontalDimension"
#define XmRHorizontalInt "HorizontalInt"
#define XmRHorizontalPosition "HorizontalPosition"
#define XmRIconAttachment "IconAttachment"
#define XmRImportTargets "ImportTargets"
#define XmRIndicatorType "IndicatorType"
#define XmRItemCount "ItemCount"
#define XmRItems "Items"
#define XmRKeySym "KeySym"
#define XmRKeySymTable "KeySymTable"
#define XmRKeyboardFocusPolicy "KeyboardFocusPolicy"
#define XmRLabelType "LabelType"
#define XmRListMarginHeight "ListMarginHeight"
#define XmRListMarginWidth "ListMarginWidth"
#define XmRListSizePolicy "ListSizePolicy"
#define XmRListSpacing "ListSpacing"
#define XmRManBottomShadowPixmap "ManBottomShadowPixmap"
#define XmRManForegroundPixmap "ManForegroundPixmap"
#define XmRManHighlightPixmap "ManHighlightPixmap"
#define XmRManTopShadowPixmap "ManTopShadowPixmap"
#define XmRMenuWidget "MenuWidget"
#define XmRMnemonic "Mnemonic"
#define XmRMultiClick "MultiClick"
#define XmRNavigationType "NavigationType"
#define XmRPacking "Packing"
#define XmRPrimForegroundPixmap "PrimForegroundPixmap"
#define XmRProc "Proc"
#define XmRProcessingDirection "ProcessingDirection"
#define XmRRectangleList "RectangleList"
#define XmRResizePolicy "ResizePolicy"
#define XmRRowColumnType "RowColumnType"
#define XmRScrollBarDisplayPolicy "ScrollBarDisplayPolicy"
#define XmRScrollBarPlacement "ScrollBarPlacement"
#define XmRScrollingPolicy "ScrollingPolicy"
#define XmRSelectedItemCount "SelectedItemCount"
#define XmRSelectedItems "SelectedItems"
#define XmRSelectionPolicy "SelectionPolicy"
#define XmRSelectionType "SelectionType"
#define XmRSeparatorType "SeparatorType"
#define XmRShadowType "ShadowType"
#define XmRShellHorizDim "ShellHorizDim"
#define XmRShellHorizPos "ShellHorizPos"
#define XmRShellUnitType "ShellUnitType"
#define XmRShellVertDim "ShellVertDim"
#define XmRShellVertPos "ShellVertPos"
#define XmRSizePolicy "SizePolicy"
#define XmRStringDirection "StringDirection"
#define XmRTearOffModel "TearOffModel"
#define XmRTopShadowPixmap "TopShadowPixmap"
#define XmRTransferStatus "TransferStatus"
#define XmRTraversalType "TraversalType"
#define XmRUnitType "UnitType"
#define XmRUnpostBehavior "UnpostBehavior"
#define XmRValueWcs "ValueWcs"
#define XmRVerticalAlignment "VerticalAlignment"
#define XmRVerticalDimension "VerticalDimension"
#define XmRVerticalInt "VerticalInt"
#define XmRVerticalPosition "VerticalPosition"
#define XmRVirtualBinding "VirtualBinding"
#define XmRVisibleItemCount "VisibleItemCount"
#define XmRVisualPolicy "VisualPolicy"
#define XmRWhichButton "WhichButton"
#define XmRXmBackgroundPixmap "XmBackgroundPixmap"
#define XmRXmString "XmString"
#define XmRXmStringCharSet "XmStringCharSet"
#define XmRXmStringTable "XmStringTable"
#define XmVosfActivate "osfActivate"
#define XmVosfAddMode "osfAddMode"
#define XmVosfBackSpace "osfBackSpace"
#define XmVosfBeginLine "osfBeginLine"
#define XmVosfCancel "osfCancel"
#define XmVosfClear "osfClear"
#define XmVosfCopy "osfCopy"
#define XmVosfCut "osfCut"
#define XmVosfDelete "osfDelete"
#define XmVosfDown "osfDown"
#define XmVosfEndLine "osfEndLine"
#define XmVosfHelp "osfHelp"
#define XmVosfInsert "osfInsert"
#define XmVosfLeft "osfLeft"
#define XmVosfMenu "osfMenu"
#define XmVosfMenuBar "osfMenuBar"
#define XmVosfPageDown "osfPageDown"
#define XmVosfPageLeft "osfPageLeft"
#define XmVosfPageRight "osfPageRight"
#define XmVosfPageUp "osfPageUp"
#define XmVosfPaste "osfPaste"
#define XmVosfPrimaryPaste "osfPrimaryPaste"
#define XmVosfQuickPaste "osfQuickPaste"
#define XmVosfRight "osfRight"
#define XmVosfSelect "osfSelect"
#define XmVosfUndo "osfUndo"
#define XmVosfUp "osfUp"
#define XmSFONTLIST_DEFAULT_TAG_STRING "FONTLIST_DEFAULT_TAG_STRING"
#define XmSXmFONTLIST_DEFAULT_TAG_STRING "XmFONTLIST_DEFAULT_TAG_STRING"
#define XmRTopItemPosition "TopItemPosition"
#define XmNtearOffTitle "tearOffTitle"
#define XmCTearOffTitle "TearOffTitle"
#define XmNpopupHandlerCallback "popupHandlerCallback"
#define XmNconvertCallback "convertCallback"
#define XmNdestinationCallback "destinationCallback"
#define XmNselectedItem "selectedItem"
#define XmCSelectedItem "SelectedItem"
#define XmNselectionCallback "selectionCallback"
#define XmNmatchBehavior "matchBehavior"
#define XmCMatchBehavior "MatchBehavior"
#define XmNnoFontCallback "noFontCallback"
#define XmNtextPath "textPath"
#define XmNeditingPath "editingPath"
#define XmCEditingPath "EditingPath"
#define XmNbidirectionalCursor "bidirectionalCursor"
#define XmCBidirectionalCursor "BidirectionalCursor"
#define XmNcollapsedStatePixmap "collapsedStatePixmap"
#define XmNdetailColumnHeading "detailColumnHeading"
#define XmNdetailCount "detailCount"
#define XmNdetailTabList "detailTabList"
#define XmNexpandedStatePixmap "expandedStatePixmap"
#define XmNlargeCellHeight "largeCellHeight"
#define XmNlargeCellWidth "largeCellWidth"
#define XmNlayoutType "layoutType"
#define XmNoutlineIndentation "outlineIndentation"
#define XmNoutlineLineStyle "outlineLineStyle"
#define XmNprimaryOwnership "primaryOwnership"
#define XmNselectionTechnique "selectionTechnique"
#define XmNsmallCellHeight "smallCellHeight"
#define XmNsmallCellWidth "smallCellWidth"
#define XmNspatialStyle "spatialStyle"
#define XmNentryParent "entryParent"
#define XmNlargeIconX "largeIconX"
#define XmNlargeIconY "largeIconY"
#define XmNsmallIconX "smallIconX"
#define XmNsmallIconY "smallIconY"
#define XmCCollapsedStatePixmap "CollapsedStatePixmap"
#define XmCDetailColumnHeading "DetailColumnHeading"
#define XmCDetailCount "DetailCount"
#define XmCDetailMask "DetailMask"
#define XmCEntryViewType "EntryViewType"
#define XmCLineStyle "LineStyle"
#define XmCDetailTabList "DetailTabList"
#define XmCExpandedStatePixmap "ExpandedStatePixmap"
#define XmCIncludeModel "IncludeModel"
#define XmCCellHeight "CellHeight"
#define XmCCellWidth "CellWidth"
#define XmCLayoutType "LayoutType"
#define XmCOutlineIndentation "OutlineIndentation"
#define XmCPlaceModel "PlaceModel"
#define XmCPrimaryOwnership "PrimaryOwnership"
#define XmCSelectionTechnique "SelectionTechnique"
#define XmCSpatialStyle "SpatialStyle"
#define XmCEntryDetail "EntryDetail"
#define XmCExpandState "ExpandState"
#define XmNlargeIcon "largeIcon"
#define XmNlargeIconMask "largeIconMask"
#define XmNlargeIconPixmap "largeIconPixmap"
#define XmNsmallIcon "smallIcon"
#define XmNsmallIconMask "smallIconMask"
#define XmNsmallIconPixmap "smallIconPixmap"
#define XmCIcon "Icon"
#define XmCViewType "ViewType"
#define XmCVisualEmphasis "VisualEmphasis"
#define XmNcurrentPageNumber "currentPageNumber"
#define XmNfirstPageNumber "firstPageNumber"
#define XmNlastPageNumber "lastPageNumber"
#define XmNbackPagePlacement "backPagePlacement"
#define XmNbackPageNumber "backPageNumber"
#define XmNbackPageSize "backPageSize"
#define XmNbackPageForeground "backPageForeground"
#define XmNbackPageBackground "backPageBackground"
#define XmNframeBackground "frameBackground"
#define XmNbindingType "bindingType"
#define XmNbindingPixmap "bindingPixmap"
#define XmNbindingWidth "bindingWidth"
#define XmNmajorTabSpacing "majorTabSpacing"
#define XmNminorTabSpacing "minorTabSpacing"
#define XmNinnerMarginWidth "innerMarginWidth"
#define XmNinnerMarginHeight "innerMarginHeight"
#define XmNframeShadowThickness "frameShadowThickness"
#define XmNpageNumber "pageNumber"
#define XmCCurrentPageNumber "CurrentPageNumber"
#define XmCFirstPageNumber "FirstPageNumber"
#define XmCLastPageNumber "LastPageNumber"
#define XmCBackPagePlacement "BackPagePlacement"
#define XmCBackPageNumber "BackPageNumber"
#define XmCBackPageSize "BackPageSize"
#define XmCBackPageForeground "BackPageForeground"
#define XmCBackPageBackground "BackPageBackground"
#define XmCFrameBackground "FrameBackground"
#define XmCBindingType "BindingType"
#define XmCBindingPixmap "BindingPixmap"
#define XmCBindingWidth "BindingWidth"
#define XmCMajorTabSpacing "MajorTabSpacing"
#define XmCMinorTabSpacing "MinorTabSpacing"
#define XmCInnerMarginWidth "InnerMarginWidth"
#define XmCInnerMarginHeight "InnerMarginHeight"
#define XmCPageChangeCallback "PageChangeCallback"
#define XmCPageNumber "PageNumber"
#define XmRArrowLayout "ArrowLayout"
#define XmRArrowSensitivity "ArrowSensitivity"
#define XmRSpinBoxChildType "SpinBoxChildType"
#define XmNarrowLayout "arrowLayout"
#define XmCArrowLayout "ArrowLayout"
#define XmNarrowSensitivity "arrowSensitivity"
#define XmCArrowSensitivity "ArrowSensitivity"
#define XmNdefaultArrowSensitivity "defaultArrowSensitivity"
#define XmCDefaultArrowSensitivity "DefaultArrowSensitivity"
#define XmNarrowSize "arrowSize"
#define XmCArrowSize "ArrowSize"
#define XmNspinBoxChildType "spinBoxChildType"
#define XmCSpinBoxChildType "SpinBoxChildType"
#define XmNposition "position"
#define XmNnumValues "numValues"
#define XmCNumValues "NumValues"
#define XmNvalues "values"
#define XmCValues "Values"
#define XmNminimumValue "minimumValue"
#define XmCMinimumValue "MinimumValue"
#define XmNmaximumValue "maximumValue"
#define XmCMaximumValue "MaximumValue"
#define XmNincrementValue "incrementValue"
#define XmCIncrementValue "IncrementValue"
#define XmRAutomaticSelection "AutomaticSelection"
#define XmRLineStyle "LineStyle"
#define XmREntryViewType "EntryViewType"
#define XmRDirection "Direction"
#define XmRLayoutType "LayoutType"
#define XmRPrimaryOwnership "PrimaryOwnership"
#define XmRSelectionTechnique "SelectionTechnique"
#define XmRSpatialStyle "SpatialStyle"
#define XmRTabList "TabList"
#define XmRViewType "ViewType"
#define XmRVisualEmphasis "VisualEmphasis"
#define XmRBindingType "BindingType"
#define XmRNBChildType "NBChildType"
#define XmNentryViewType "entryViewType"
#define XmNinsensitiveStippleBitmap "insensitiveStippleBitmap"
#define XmNlayoutDirection "layoutDirection"
#define XmNviewType "viewType"
#define XmNvisualEmphasis "visualEmphasis"
#define XmCLayoutDirection "LayoutDirection"
#define XmNsnapBackMultiple "snapBackMultiple"
#define XmNslidingMode "slidingMode"
#define XmNsliderVisual "sliderVisual"
#define XmNautoDragModel "autoDragModel"
#define XmNcolorCalculationProc "colorCalculationProc"
#define XmNbitmapConversionModel "bitmapConversionModel"
#define XmNcolorAllocationProc "colorAllocationProc"
#define XmNselectionMode "selectionMode"
#define XmNselectedPositions "selectedPositions"
#define XmNselectedPositionCount "selectedPositionCount"
#define XmCSnapBackMultiple "SnapBackMultiple"
#define XmCSliderVisual "SliderVisual"
#define XmCSlidingMode "SlidingMode"
#define XmCAutoDragModel "AutoDragModel"
#define XmCColorCalculationProc "ColorCalculationProc"
#define XmCBitmapConversionModel "BitmapConversionModel"
#define XmCColorAllocationProc "ColorAllocationProc"
#define XmCInsensitiveStippleBitmap "InsensitiveStippleBitmap"
#define XmCSelectionMode "SelectionMode"
#define XmCSelectedPositions "SelectedPositions"
#define XmCSelectedPositionCount "SelectedPositionCount"
#define XmRSlidingMode "SlidingMode"
#define XmRShowArrows "ShowArrows"
#define XmRSliderVisual "SliderVisual"
#define XmRShowValue "ShowValue"
#define XmRAutoDragModel "AutoDragModel"
#define XmRSWChildType "SWChildType"
#define XmRBitmapConversionModel "BitmapConversionModel"
#define XmRSelectionMode "SelectionMode"
#define XmNinputPolicy "inputPolicy"
#define XmCInputPolicy "InputPolicy"
#define XmRInputPolicy "InputPolicy"
#define XmNtoggleMode "toggleMode"
#define XmCToggleMode "ToggleMode"
#define XmRToggleMode "ToggleMode"
#define XmRIndicatorOn "IndicatorOn"
#define XmRSet "Set"
#define XmNindeterminatePixmap "indeterminatePixmap"
#define XmCIndeterminatePixmap "IndeterminatePixmap"
#define XmNunselectColor "unselectColor"
#define XmCUnselectColor "UnselectColor"
#define XmNselectedPosition "selectedPosition"
#define XmNarrowSpacing "arrowSpacing"
#define XmCArrowSpacing "ArrowSpacing"
#define XmRMatchBehavior "MatchBehavior"
#define XmRComboBoxType "ComboBoxType"
#define XmCSelectedPosition "SelectedPosition"
#define XmNenableWarp "enableWarp"
#define XmCEnableWarp "EnableWarp"
#define XmREnableWarp "EnableWarp"
#define XmNmotifVersion "motifVersion"
#define XmCMotifVersion "MotifVersion"
#define XmNdefaultGlyphPixmap "defaultGlyphPixmap"
#define XmCDefaultGlyphPixmap "DefaultGlyphPixmap"
#define XmCRendition "Rendition"
#define XmNtag "tag"
#define XmCTag "Tag"
#define XmNfontName "fontName"
#define XmCFontName "FontName"
#define XmNfontType "fontType"
#define XmCFontType "FontType"
#define XmRFontType "FontType"
#define XmNloadModel "loadModel"
#define XmCLoadModel "LoadModel"
#define XmRLoadModel "LoadModel"
#define XmNtabList "tabList"
#define XmCTabList "TabList"
#define XmRRenditionPixel "RenditionPixel"
#define XmNunderlineType "underlineType"
#define XmCUnderlineType "UnderlineType"
#define XmNstrikethruType "strikethruType"
#define XmCStrikethruType "StrikethruType"
#define XmRLineType "LineType"
#define XmNrenderTable "renderTable"
#define XmCRenderTable "RenderTable"
#define XmRRenderTable "RenderTable"
#define XmNbuttonRenderTable "buttonRenderTable"
#define XmCButtonRenderTable "ButtonRenderTable"
#define XmRButtonRenderTable "ButtonRenderTable"
#define XmNlabelRenderTable "labelRenderTable"
#define XmCLabelRenderTable "LabelRenderTable"
#define XmRLabelRenderTable "LabelRenderTable"
#define XmNtextRenderTable "textRenderTable"
#define XmCTextRenderTable "TextRenderTable"
#define XmRTextRenderTable "TextRenderTable"
#define XmNdragStartCallback "dragStartCallback"
#define XmNnoRenditionCallback "noRenditionCallback"
#define XmSXmAS_IS "XmAS_IS"
#define XmMIsWhiteSpaceMethod "IsWhiteSpaceMethod"
#define XmMIsScanBreakMethod "IsScanBreakMethod"
#define XmMCharDirection "CharDirection"
#define XmMInitialCharsDirection "InitialCharsDirection"
#define XmNpatternType "patternType"
#define XmNsubstitute "substitute"
#define XmNinvokeParseProc "invokeParseProc"
#define XmNincludeStatus "includeStatus"
#define XmVosfBackTab "osfBackTab"
#define XmVosfBeginData "osfBeginData"
#define XmVosfDeselectAll "osfDeselectAll"
#define XmVosfEndData "osfEndData"
#define XmVosfEscape "osfEscape"
#define XmVosfExtend "osfExtend"
#define XmVosfLeftLine "osfLeftLine"
#define XmVosfNext "osfNext"
#define XmVosfNextField "osfNextField"
#define XmVosfNextMenu "osfNextMenu"
#define XmVosfNextMinor "osfNextMinor"
#define XmVosfPrevField "osfPrevField"
#define XmVosfPrevMenu "osfPrevMenu"
#define XmVosfPrior "osfPrior"
#define XmVosfPriorMinor "osfPriorMinor"
#define XmVosfReselect "osfReselect"
#define XmVosfRestore "osfRestore"
#define XmVosfRightLine "osfRightLine"
#define XmVosfSelectAll "osfSelectAll"
#define XmVosfSwitchDirection "osfSwitchDirection"
#define XmNnotebookChildType "notebookChildType"
#define XmCNotebookChildType "NotebookChildType"
#define XmRNotebookChildType "NotebookChildType"
#define XmNscrolledWindowChildType "scrolledWindowChildType"
#define XmCScrolledWindowChildType "ScrolledWindowChildType"
#define XmRScrolledWindowChildType "ScrolledWindowChildType"
#define XmNselectedObjects "selectedObjects"
#define XmCSelectedObjects "SelectedObjects"
#define XmNselectedObjectCount "selectedObjectCount"
#define XmCSelectedObjectCount "SelectedObjectCount"
#define XmNcomboBoxType "comboBoxType"
#define XmCComboBoxType "ComboBoxType"
#define XmNtabValue "tabValue"
#define XmNoffsetModel "offsetModel"
#define XmNdecimal "decimal"
#define XmNdetail "detail"
#define XmCDetail "Detail"
#define XmNdetailCount "detailCount"
#define XmCDetailCount "DetailCount"
#define XmNcontainerID "containerID"
#define XmCContainerID "ContainerID"
#define XmSCLIENT_WINDOW "CLIENT_WINDOW"
#define XmSCLIP_TEMPORARY "CLIP_TEMPORARY"
#define XmSCLIPBOARD "CLIPBOARD"
#define XmSCOMPOUND_TEXT "COMPOUND_TEXT"
#define XmSDELETE "DELETE"
#define XmSFILE "FILE"
#define XmSFILE_NAME "FILE_NAME"
#define XmSINCR "INCR"
#define XmSINSERT_PROPERTY "INSERT_PROPERTY"
#define XmSINSERT_SELECTION "INSERT_SELECTION"
#define XmSLENGTH "LENGTH"
#define XmSLINK_SELECTION "LINK_SELECTION"
#define XmS_MOTIF_ATOM_0 "_MOTIF_ATOM_0"
#define XmS_MOTIF_BINDINGS "_MOTIF_BINDINGS"
#define XmS_MOTIF_DEFAULT_BINDINGS "_MOTIF_DEFAULT_BINDINGS"
#define XmS_MOTIF_CANCEL_DROP_EFFECT "_MOTIF_CANCEL_DROP_EFFECT"
#define XmS_MOTIF_CLIP_HEADER "_MOTIF_CLIP_HEADER"
#define XmS_MOTIF_CLIP_DATA_REQUEST "_MOTIF_CLIP_DATA_REQUEST"
#define XmS_MOTIF_CLIP_DATA_DELETE "_MOTIF_CLIP_DATA_DELETE"
#define XmS_MOTIF_CLIP_ITEM "_MOTIF_CLIP_ITEM"
#define XmS_MOTIF_CLIP_LOCK "_MOTIF_CLIP_LOCK"
#define XmS_MOTIF_CLIP_LOCK_ACCESS_VALID "_MOTIF_CLIP_LOCK_ACCESS_VALID"
#define XmS_MOTIF_CLIP_MESSAGE "_MOTIF_CLIP_MESSAGE"
#define XmS_MOTIF_CLIP_NEXT_ID "_MOTIF_CLIP_NEXT_ID"
#define XmS_MOTIF_CLIP_TIME "_MOTIF_CLIP_TIME"
#define XmS_MOTIF_CLIPBOARD_TARGETS "_MOTIF_CLIPBOARD_TARGETS"
#define XmS_MOTIF_COMPOUND_STRING "_MOTIF_COMPOUND_STRING"
#define XmS_MOTIF_DEFERRED_CLIPBOARD_TARGETS "_MOTIF_DEFERRED_CLIPBOARD_TARGETS"
#define XmS_MOTIF_DESTINATION "_MOTIF_DESTINATION"
#define XmS_MOTIF_DRAG_OFFSET "_MOTIF_DRAG_OFFSET"
#define XmS_MOTIF_DROP "_MOTIF_DROP"
#define XmS_MOTIF_ENCODING_REGISTRY "_MOTIF_ENCODING_REGISTRY"
#define XmS_MOTIF_EXPORT_TARGETS "_MOTIF_EXPORT_TARGETS"
#define XmS_MOTIF_LOSE_SELECTION "_MOTIF_LOSE_SELECTION"
#define XmS_MOTIF_RENDER_TABLE "_MOTIF_RENDER_TABLE"
#define XmS_MOTIF_WM_QUERY "_MOTIF_WM_QUERY"
#define XmS_MOTIF_WM_ALL_CLIENTS "_MOTIF_WM_ALL_CLIENTS"
#define XmSMULTIPLE "MULTIPLE"
#define XmSNULL "NULL"
#define XmSTARGETS "TARGETS"
#define XmSTEXT "TEXT"
#define XmSTIMESTAMP "TIMESTAMP"
#define XmSWM_STATE "WM_STATE"
#define XmSTRANSFER_SUCCESS "XmTRANSFER_SUCCESS"
#define XmSTRANSFER_FAILURE "XmTRANSFER_FAILURE"
#define XmNpathMode "pathMode"
#define XmRPathMode "PathMode"
#define XmCPathMode "PathMode"
#define XmNfileFilterStyle "fileFilterStyle"
#define XmRFileFilterStyle "FileFilterStyle"
#define XmCFileFilterStyle "FileFilterStyle"
#define XmNdirTextLabelString "dirTextLabelString"
#define XmCDirTextLabelString "DirTextLabelString"
#define XmNenableBtn1Transfer "enableBtn1Transfer"
#define XmCEnableBtn1Transfer "EnableBtn1Transfer"
#define XmNenableButtonTab "enableButtonTab"
#define XmCEnableButtonTab "EnableButtonTab"
#define XmNenableEtchedInMenu "enableEtchedInMenu"
#define XmCEnableEtchedInMenu "EnableEtchedInMenu"
#define XmNdefaultButtonEmphasis "defaultButtonEmphasis"
#define XmCDefaultButtonEmphasis "DefaultButtonEmphasis"
#define XmRDefaultButtonEmphasis "DefaultButtonEmphasis"
#define XmNenableToggleColor "enableToggleColor"
#define XmCEnableToggleColor "EnableToggleColor"
#define XmNenableToggleVisual "enableToggleVisual"
#define XmCEnableToggleVisual "EnableToggleVisual"
#define XmNenableDragIcon "enableDragIcon"
#define XmCEnableDragIcon "EnableDragIcon"
#define XmNenableUnselectableDrag "enableUnselectableDrag"
#define XmCEnableUnselectableDrag "EnableUnselectableDrag"
#define XmNdragOverActiveMode "dragOverActiveMode"
#define XmCDragOverActiveMode "DragOverActiveMode"
#define XmNinstallColormap "installColormap"
#define XmCInstallColormap "InstallColormap"
#define XmCOwnerEvents "OwnerEvents"
#define XmNownerEvents "ownerEvents"
#define XmCGrabStyle "GrabStyle"
#define XmNgrabStyle "grabStyle"
#define XmNforegroundState "foregroundState"
#define XmNbackgroundState "backgroundState"
#define XmCGroundState "GroundState"
#define XmRGroundState "GroundState"
#define XmRSelectColor "SelectColor"
#define XmRLargeIconPixmap "LargeIconPixmap"
#define XmRSmallIconPixmap "SmallIconPixmap"
#define XmNoutlineState "outlineState"
#define XmCOutlineState "OutlineState"
#define XmROutlineState "OutlineState"
#define XmNspatialIncludeModel "spatialIncludeModel"
#define XmCSpatialIncludeModel "SpatialIncludeModel"
#define XmRSpatialIncludeModel "SpatialIncludeModel"
#define XmNspatialResizeModel "spatialResizeModel"
#define XmCSpatialResizeModel "SpatialResizeModel"
#define XmRSpatialResizeModel "SpatialResizeModel"
#define XmNspatialSnapModel "spatialSnapModel"
#define XmCSpatialSnapModel "SpatialSnapModel"
#define XmRSpatialSnapModel "SpatialSnapModel"
#define XmNdetailColumnHeadingCount "detailColumnHeadingCount"
#define XmCDetailColumnHeadingCount "DetailColumnHeadingCount"
#define XmNdetailOrder "detailOrder"
#define XmCDetailOrder "DetailOrder"
#define XmRCardinalList "CardinalList"
#define XmNdetailOrderCount "detailOrderCount"
#define XmCDetailOrderCount "DetailOrderCount"
#define XmNoutlineColumnWidth "outlineColumnWidth"
#define XmCOutlineColumnWidth "OutlineColumnWidth"
#define XmNoutlineChangedCallback "outlineChangedCallback"
#define XmCOutlineChangedCallback "OutlineChangedCallback"
#define XmNoutlineButtonPolicy "outlineButtonPolicy"
#define XmCOutlineButtonPolicy "OutlineButtonPolicy"
#define XmROutlineButtonPolicy "OutlineButtonPolicy"
#define XmCDefaultVirtualBindings "DefaultVirtualBindings"
#define XmNdefaultVirtualBindings "defaultVirtualBindings"
#define XmCResizable "Resizable"
#define XmRDynamicPixmap "DynamicPixmap"
#define XmNpageChangedCallback "pageChangedCallback"
#define XmNarea "area"
#define XmNdetailShadowThickness "detailShadowThickness"
#define XmNsliderMark "sliderMark"
#define XmCSliderMark "SliderMark"
#define XmRSliderMark "SliderMark"
#define XmREnableBtn1Transfer "EnableBtn1Transfer"
#define XmNrenditionBackground "renditionBackground"
#define XmNrenditionForeground "renditionForeground"
#define XmCRenditionBackground "RenditionBackground"
#define XmCRenditionForeground "RenditionForeground"
#define XmNindeterminateInsensitivePixmap "indeterminateInsensitivePixmap"
#define XmCIndeterminateInsensitivePixmap "IndeterminateInsensitivePixmap"
#define XmNframeChildType "frameChildType"
#define XmCFrameChildType "FrameChildType"
#define XmNtextField "textField"
#define XmCTextField "TextField"
#define XmNenableThinThickness "enableThinThickness"
#define XmCEnableThinThickness "EnableThinThickness"
#define XmNprimaryColorSetId "primaryColorSetId"
#define XmCPrimaryColorSetId "PrimaryColorSetId"
#define XmNsecondaryColorSetId "secondaryColorSetId"
#define XmCSecondaryColorSetId "SecondaryColorSetId"
#define XmNtextColorSetId "textColorSetId"
#define XmCTextColorSetId "TextColorSetId"
#define XmNactiveColorSetId "activeColorSetId"
#define XmCActiveColorSetId "ActiveColorSetId"
#define XmNinactiveColorSetId "inactiveColorSetId"
#define XmCInactiveColorSetId "InactiveColorSetId"
#define XmNuseColorObj "useColorObj"
#define XmCUseColorObj "UseColorObj"
#define XmNuseTextColor "useTextColor"
#define XmCUseTextColor "UseTextColor"
#define XmNuseTextColorForList "useTextColorForList"
#define XmCUseTextColorForList "UseTextColorForList"
#define XmNuseMask "useMask"
#define XmCUseMask "UseMask"
#define XmNuseMultiColorIcons "useMultiColorIcons"
#define XmCUseMultiColorIcons "UseMultiColorIcons"
#define XmNuseIconFileCache "useIconFileCache"
#define XmCUseIconFileCache "UseIconFileCache"
#define XmSPIXEL_SET "Pixel Sets"
#define XmSCUSTOMIZE_DATA "Customize Data:"
#define XmSCOLOR_SRV_NAME "ColorServer"
#define XmNlist "list"
#define XmCList "List"
#define XmNarrowOrientation "arrowOrientation"
#define XmCArrowOrientation "ArrowOrientation"
#define XmRArrowOrientation "ArrowOrientation"
#define XmNpositionType "positionType"
#define XmCPositionType "PositionType"
#define XmRPositionType "PositionType"
#define XmNwrap "wrap"
#define XmCWrap "Wrap"
#define XmNpositionMode "positionMode"
#define XmCPositionMode "PositionMode"
#define XmRPositionMode "PositionMode"
#define XmNprintOrientation "printOrientation"
#define XmCPrintOrientation "PrintOrientation"
#define XmNprintOrientations "printOrientations"
#define XmCPrintOrientations "PrintOrientations"
#define XmNprintResolution "printResolution"
#define XmCPrintResolution "PrintResolution"
#define XmNprintResolutions "printResolutions"
#define XmCPrintResolutions "PrintResolutions"
#define XmNdefaultPixmapResolution "defaultPixmapResolution"
#define XmCDefaultPixmapResolution "DefaultPixmapResolution"
#define XmNstartJobCallback "startJobCallback"
#define XmNendJobCallback "endJobCallback"
#define XmNpageSetupCallback "pageSetupCallback"
#define XmNpdmNotificationCallback "pdmNotificationCallback"
#define XmNminX "minX"
#define XmNminY "minY"
#define XmNmaxX "maxX"
#define XmNmaxY "maxY"
#define XmCMinX "MinX"
#define XmCMinY "MinY"
#define XmCMaxX "MaxX"
#define XmCMaxY "MaxY"
#define XmNpreeditStartCallback "preeditStartCallback"
#define XmNpreeditDoneCallback "preeditDoneCallback"
#define XmNpreeditDrawCallback "preeditDrawCallback"
#define XmNpreeditCaretCallback "preeditCaretCallback"
#define XmNverifyPreedit "verifyPreedit"
#define XmCVerifyPreedit "VerifyPreedit"
#define XmNenableMultiKeyBindings "enableMultiKeyBindings"
#define XmCEnableMultiKeyBindings "EnableMultiKeyBindings"
#define XmRButtonFontList "ButtonFontList"
#define XmRLabelFontList "LabelFontList"
#define XmRTextFontList "TextFontList"
#define XmSPIXEL_SET_PROP "SDT Pixel Set"
#define XmS50_foreground "50_foreground"
#define XmSunspecified_pixmap "unspecified_pixmap"
#else
extern const char _XmStrings[];

#ifdef __cplusplus
}  /* Close scope of 'extern "C"' declaration */
#endif

#include <X11/StringDefs.h>

#ifdef __cplusplus
extern "C" {
#endif

#define XmSTRING_DEFAULT_CHARSET	XmS
#define XmSTRING_ISO8859_1		"ISO8859-1"
#define XmFONTLIST_DEFAULT_TAG		XmSFONTLIST_DEFAULT_TAG_STRING
#define XmFONTLIST_DEFAULT_TAG_STRING	XmSXmFONTLIST_DEFAULT_TAG_STRING

#define XmVaCASCADEBUTTON		"cascadeButton"
#define XmVaCHECKBUTTON			"checkButton"
#define XmVaDOUBLE_SEPARATOR		"doubleSeparator"
#define XmVaPUSHBUTTON			"pushButton"
#define XmVaRADIOBUTTON			"radioButton"
#define XmVaSEPARATOR			"separator"
#define XmVaSINGLE_SEPARATOR		"singleSeparator"
#define XmVaTOGGLEBUTTON		"checkButton"

#ifndef XmVaTITLE
#define XmVaTITLE			XtNtitle
#endif

#ifndef XtCKeyboardFocusPolicy
#define XtCKeyboardFocusPolicy		XmCKeyboardFocusPolicy
#endif

#ifndef XtCShellUnitType
#define XtCShellUnitType		XmCShellUnitType
#endif

#ifndef XtNkeyboardFocusPolicy
#define XtNkeyboardFocusPolicy		XmNkeyboardFocusPolicy
#endif

#ifndef XtNshellUnitType
#define XtNshellUnitType		XmNshellUnitType
#endif

#ifndef XtRKeyboardFocusPolicy
#define XtRKeyboardFocusPolicy		XmRKeyboardFocusPolicy
#endif

#ifndef XmRPrimBottomShadowPixmap
#define XmRPrimBottomShadowPixmap       XmRBottomShadowPixmap
#endif

#ifndef XmRPrimHighlightPixmap
#define XmRPrimHighlightPixmap          XmRHighlightPixmap
#endif

#ifndef XmRPrimTopShadowPixmap
#define XmRPrimTopShadowPixmap          XmRTopShadowPixmap
#endif

#ifndef XmCAccelerators
#define XmCAccelerators			XtCAccelerators
#endif

#ifndef XmCAllowShellResize
#define XmCAllowShellResize		XtCAllowShellResize
#endif

#ifndef XmCArgc
#define XmCArgc				XtCArgc
#endif

#ifndef XmCArgv
#define XmCArgv				XtCArgv
#endif

#ifndef XmCBackground
#define XmCBackground			XtCBackground
#endif

#ifndef XmCBaseHeight
#define XmCBaseHeight			XtCBaseHeight
#endif

#ifndef XmCBaseHeight
#define XmCBaseHeight			XtCBaseHeight
#endif

#ifndef XmCBaseWidth
#define XmCBaseWidth			XtCBaseWidth
#endif

#ifndef XmCBaseWidth
#define XmCBaseWidth			XtCBaseWidth
#endif

#ifndef XmCBitmap
#define XmCBitmap			XtCBitmap
#endif

#ifndef XmCBoolean
#define XmCBoolean			XtCBoolean
#endif

#ifndef XmCBorderColor
#define XmCBorderColor			XtCBorderColor
#endif

#ifndef XmCBorderWidth
#define XmCBorderWidth			XtCBorderWidth
#endif

#ifndef XmCCallback
#define XmCCallback			XtCCallback
#endif

#ifndef XmCColor
#define XmCColor			XtCColor
#endif

#ifndef XmCColormap
#define XmCColormap			XtCColormap
#endif

#ifndef XmCCreatePopupChildProc
#define XmCCreatePopupChildProc		XtCCreatePopupChildProc
#endif

#ifndef XmCCursor
#define XmCCursor			XtCCursor
#endif

#ifndef XmCDepth
#define XmCDepth			XtCDepth
#endif

#ifndef XmCDimension
#define XmCDimension			XtRDimension
#endif

#ifndef XmCEditMode
#define XmCEditMode			XtREditMode
#endif

#ifndef XmCEditType
#define XmCEditType			XtCEditType
#endif

#ifndef XmCEventBindings
#define XmCEventBindings		XtCEventBindings
#endif

#ifndef XmCFile
#define XmCFile				XtCFile
#endif

#ifndef XmCFont
#define XmCFont				XtCFont
#endif

#ifndef XmCFontSet
#define XmCFontSet			XtCFontSet
#endif

#ifndef XmCForeground
#define XmCForeground			XtCForeground
#endif

#ifndef XmCFraction
#define XmCFraction			XtCFraction
#endif 

#ifndef XmCFunction
#define XmCFunction			XtCFunction
#endif 

#ifndef XmCGeometry
#define XmCGeometry			XtCGeometry
#endif 

#ifndef XmCHSpace
#define XmCHSpace			XtCHSpace
#endif 

#ifndef XmCHeight
#define XmCHeight			XtCHeight
#endif 

#ifndef XmCHeightInc
#define XmCHeightInc			XtCHeightInc
#endif 

#ifndef XmCIconMask
#define XmCIconMask			XtCIconMask
#endif 

#ifndef XmCIconName
#define XmCIconName			XtCIconName
#endif 

#ifndef XmCIconNameEncoding
#define XmCIconNameEncoding		XtCIconNameEncoding
#endif 

#ifndef XmCIconPixmap
#define XmCIconPixmap			XtCIconPixmap
#endif 

#ifndef XmCIconWindow
#define XmCIconWindow			XtCIconWindow
#endif 

#ifndef XmCIconX
#define XmCIconX			XtCIconX
#endif 

#ifndef XmCIconY
#define XmCIconY			XtCIconY
#endif 

#ifndef XmCIconic
#define XmCIconic			XtCIconic
#endif 

#ifndef XmCIndex
#define XmCIndex			XtCIndex
#endif 

#ifndef XmCInitialResourcesPersistent
#define XmCInitialResourcesPersistent	XtCInitialResourcesPersistent
#endif 

#ifndef XmCInitialState
#define XmCInitialState			XtCInitialState
#endif 

#ifndef XmCInput
#define XmCInput			XtCInput
#endif 

#ifndef XmCInsertPosition
#define XmCInsertPosition		XtCInsertPosition
#endif 

#ifndef XmCInterval
#define XmCInterval			XtCInterval
#endif 

#ifndef XmCJustify
#define XmCJustify			XtCJustify
#endif 

#ifndef XmCLabel
#define XmCLabel			XtCLabel
#endif 

#ifndef XmCLength
#define XmCLength			XtCLength
#endif 

#ifndef XmCMappedWhenManaged
#define XmCMappedWhenManaged		XtCMappedWhenManaged
#endif 

#ifndef XmCMargin
#define XmCMargin			XtCMargin
#endif 


#ifndef XmCMaxAspectX
#define XmCMaxAspectX			XtCMaxAspectX
#endif 


#ifndef XmCMaxAspectY
#define XmCMaxAspectY			XtCMaxAspectY
#endif 

#ifndef XmCMaxHeight
#define XmCMaxHeight			XtCMaxHeight
#endif 

#ifndef XmCMaxWidth
#define XmCMaxWidth			XtCMaxWidth
#endif

#ifndef XmCMenuEntry
#define XmCMenuEntry			XtCMenuEntry
#endif

#ifndef XmCMinAspectX
#define XmCMinAspectX			XtCMinAspectX
#endif

#ifndef XmCMinAspectY
#define XmCMinAspectY			XtCMinAspectY
#endif

#ifndef XmCMinHeight
#define XmCMinHeight			XtCMinHeight
#endif

#ifndef XmCMinWidth
#define XmCMinWidth			XtCMinWidth
#endif

#ifndef XmCNotify
#define XmCNotify			XtCNotify
#endif

#ifndef XmCOrientation
#define XmCOrientation			XtCOrientation
#endif

#ifndef XmCOverrideRedirect
#define XmCOverrideRedirect		XtCOverrideRedirect
#endif

#ifndef XmCParameter
#define XmCParameter			XtCParameter
#endif 

#ifndef XmCPixmap
#define XmCPixmap			XtCPixmap
#endif


#ifndef XmCPosition
#define XmCPosition			XtCPosition
#endif

#ifndef XmCReadOnly
#define XmCReadOnly			XtCReadOnly
#endif

#ifndef XmCResize
#define XmCResize			XtCResize
#endif

#ifndef XmCReverseVideo
#define XmCReverseVideo			XtCReverseVideo
#endif

#ifndef XmCSaveUnder
#define XmCSaveUnder			XtCSaveUnder
#endif

#ifndef XmCScreen
#define XmCScreen			XtCScreen
#endif

#ifndef XmCScrollDCursor
#define XmCScrollDCursor		XtCScrollDCursor
#endif

#ifndef XmCScrollHCursor
#define XmCScrollHCursor		XtCScrollHCursor
#endif

#ifndef XmCScrollLCursor
#define XmCScrollLCursor		XtCScrollLCursor
#endif

#ifndef XmCScrollProc
#define XmCScrollProc			XtCScrollProc
#endif

#ifndef XmCScrollRCursor
#define XmCScrollRCursor		XtCScrollRCursor
#endif

#ifndef XmCScrollUCursor
#define XmCScrollUCursor		XtCScrollUCursor
#endif

#ifndef XmCScrollVCursor
#define XmCScrollVCursor		XtCScrollVCursor
#endif

#ifndef XmCSelection
#define XmCSelection			XtCSelection
#endif

#ifndef XmCSelectionArray
#define XmCSelectionArray		XtCSelectionArray
#endif

#ifndef XmCSensitive
#define XmCSensitive			XtCSensitive
#endif

#ifndef XmCSpace
#define XmCSpace			XtCSpace
#endif

#ifndef XmCString
#define XmCString			XtCString
#endif

#ifndef XmCTextOptions
#define XmCTextOptions			XtCTextOptions
#endif

#ifndef XmCTextPosition
#define XmCTextPosition			XtCTextPosition
#endif

#ifndef XmCTextSink
#define XmCTextSink			XtCTextSink
#endif

#ifndef XmCTextSource
#define XmCTextSource			XtCTextSource
#endif

#ifndef XmCThickness
#define XmCThickness			XtCThickness
#endif

#ifndef XmCThumb
#define XmCThumb			XtCThumb
#endif

#ifndef XmCTitle
#define XmCTitle			XtCTitle
#endif

#ifndef XmCTitleEncoding
#define XmCTitleEncoding		XtCTitleEncoding
#endif

#ifndef XmCTransient
#define XmCTransient			XtCTransient
#endif

#ifndef XmCTransientFor
#define XmCTransientFor			XtCTransientFor
#endif

#ifndef XmCTranslations
#define XmCTranslations			XtCTranslations
#endif

#ifndef XmCVSpace
#define XmCVSpace			XtCVSpace
#endif


#ifndef XmCValue
#define XmCValue			XtCValue
#endif

#ifndef XmCVisual
#define XmCVisual			XtCVisual
#endif

#ifndef XmCWaitForWm
#define XmCWaitForWm			XtCWaitForWm
#endif

#ifndef XmCWidget
#define XmCWidget			XtRWidget
#endif

#ifndef XmCWidth
#define XmCWidth			XtCWidth
#endif

#ifndef XmCWidthInc
#define XmCWidthInc			XtCWidthInc
#endif

#ifndef XmCWinGravity
#define XmCWinGravity			XtCWinGravity
#endif

#ifndef XmCWindow
#define XmCWindow			XtCWindow
#endif

#ifndef XmCWindowGroup
#define XmCWindowGroup			XtCWindowGroup
#endif

#ifndef XmCWmTimeout
#define XmCWmTimeout			XtCWmTimeout
#endif

#ifndef XmCX
#define XmCX				XtCX
#endif

#ifndef XmCY
#define XmCY				XtCY
#endif

#ifndef XmNaccelerators
#define XmNaccelerators			XtNaccelerators
#endif

#ifndef XmNallowShellResize
#define XmNallowShellResize		XtNallowShellResize
#endif

#ifndef XmNancestorSensitive
#define XmNancestorSensitive		XtNancestorSensitive
#endif

#ifndef XmNargc
#define XmNargc				XtNargc
#endif

#ifndef XmNargv
#define XmNargv				XtNargv
#endif

#ifndef XmNbackground
#define XmNbackground			XtNbackground
#endif

#ifndef XmNbackgroundPixmap
#define XmNbackgroundPixmap		XtNbackgroundPixmap
#endif

#ifndef XmNbaseHeight
#define XmNbaseHeight			XtNbaseHeight
#endif

#ifndef XmNbaseHeight
#define XmNbaseHeight			XtNbaseHeight
#endif

#ifndef XmNbaseWidth
#define XmNbaseWidth			XtNbaseWidth
#endif

#ifndef XmNbaseWidth
#define XmNbaseWidth			XtNbaseWidth
#endif

#ifndef XmNbitmap
#define XmNbitmap			XtNbitmap
#endif

#ifndef XmNborder
#define XmNborder			XtNborder
#endif

#ifndef XmNborderColor
#define XmNborderColor			XtNborderColor
#endif

#ifndef XmNborderPixmap
#define XmNborderPixmap			XtNborderPixmap
#endif

#ifndef XmNborderWidth
#define XmNborderWidth			XtNborderWidth
#endif

#ifndef XmNcallback
#define XmNcallback			XtNcallback
#endif

#ifndef XmNchildren
#define XmNchildren			XtNchildren
#endif

#ifndef XmNcolormap
#define XmNcolormap			XtNcolormap
#endif

#ifndef XmNcreatePopupChildProc
#define XmNcreatePopupChildProc		XtNcreatePopupChildProc
#endif

#ifndef XmNdepth
#define XmNdepth			XtNdepth
#endif

#ifndef XmNdestroyCallback
#define XmNdestroyCallback		XtNdestroyCallback
#endif

#ifndef XmNeditType
#define XmNeditType			XtNeditType
#endif

#ifndef XmNfile
#define XmNfile				XtNfile
#endif

#ifndef XmNfont
#define XmNfont				XtNfont
#endif

#ifndef XmNfontSet
#define XmNfontSet		        XtNfontSet
#endif

#ifndef XmNforceBars
#define XmNforceBars			XtNforceBars
#endif

#ifndef XmNforeground
#define XmNforeground			XtNforeground
#endif

#ifndef XmNfunction
#define XmNfunction			XtNfunction
#endif

#ifndef XmNgeometry
#define XmNgeometry			XtNgeometry
#endif

#ifndef XmNheight
#define XmNheight			XtNheight
#endif

#ifndef XmNheightInc
#define XmNheightInc			XtNheightInc
#endif

#ifndef XmNhighlight
#define XmNhighlight			XtNhighlight
#endif

#ifndef XmNiconMask
#define XmNiconMask			XtNiconMask
#endif

#ifndef XmNiconName
#define XmNiconName			XtNiconName
#endif

#ifndef XmNiconNameEncoding
#define XmNiconNameEncoding		XtNiconNameEncoding
#endif

#ifndef XmNiconPixmap
#define XmNiconPixmap			XtNiconPixmap
#endif

#ifndef XmNiconWindow
#define XmNiconWindow			XtNiconWindow
#endif

#ifndef XmNiconX
#define XmNiconX			XtNiconX
#endif

#ifndef XmNiconY
#define XmNiconY			XtNiconY
#endif

#ifndef XmNiconic
#define XmNiconic			XtNiconic
#endif

#ifndef XmNindex
#define XmNindex			XtNindex
#endif

#ifndef XmNinitialResourcesPersistent
#define XmNinitialResourcesPersistent	XtNinitialResourcesPersistent
#endif

#ifndef XmNinitialState
#define XmNinitialState			XtNinitialState
#endif

#ifndef XmNinnerHeight
#define XmNinnerHeight			XtNinnerHeight
#endif

#ifndef XmNinnerWidth
#define XmNinnerWidth			XtNinnerWidth
#endif

#ifndef XmNinnerWindow
#define XmNinnerWindow			XtNinnerWindow
#endif

#ifndef XmNinput
#define XmNinput			XtNinput
#endif

#ifndef XmNinsertPosition
#define XmNinsertPosition		XtNinsertPosition
#endif

#ifndef XmNinternalHeight
#define XmNinternalHeight		XtNinternalHeight
#endif

#ifndef XmNinternalWidth
#define XmNinternalWidth		XtNinternalWidth
#endif

#ifndef XmNjumpProc
#define XmNjumpProc			XtNjumpProc
#endif

#ifndef XmNjustify
#define XmNjustify			XtNjustify
#endif

#ifndef XmNlength
#define XmNlength			XtNlength
#endif

#ifndef XmNlowerRight
#define XmNlowerRight			XtNlowerRight
#endif

#ifndef XmNmappedWhenManaged
#define XmNmappedWhenManaged		XtNmappedWhenManaged
#endif

#ifndef XmNmaxAspectX
#define XmNmaxAspectX			XtNmaxAspectX
#endif

#ifndef XmNmaxAspectY
#define XmNmaxAspectY			XtNmaxAspectY
#endif

#ifndef XmNmaxHeight
#define XmNmaxHeight			XtNmaxHeight
#endif

#ifndef XmNmaxWidth
#define XmNmaxWidth			XtNmaxWidth
#endif

#ifndef XmNmenuEntry
#define XmNmenuEntry			XtNmenuEntry
#endif

#ifndef XmNminAspectX
#define XmNminAspectX			XtNminAspectX
#endif

#ifndef XmNminAspectY
#define XmNminAspectY			XtNminAspectY
#endif

#ifndef XmNminHeight
#define XmNminHeight			XtNminHeight
#endif

#ifndef XmNminWidth
#define XmNminWidth			XtNminWidth
#endif

#ifndef XmNname
#define XmNname				XtNname
#endif

#ifndef XmNnotify
#define XmNnotify			XtNnotify
#endif

#ifndef XmNnumChildren
#define XmNnumChildren			XtNnumChildren
#endif

#ifndef XmNorientation
#define XmNorientation			XtNorientation
#endif

#ifndef XmNoverrideRedirect
#define XmNoverrideRedirect		XtNoverrideRedirect
#endif

#ifndef XmNparameter
#define XmNparameter			XtNparameter
#endif

#ifndef XmNpixmap
#define XmNpixmap			XtNpixmap
#endif

#ifndef XmNpopdownCallback
#define XmNpopdownCallback		XtNpopdownCallback
#endif

#ifndef XmNpopupCallback
#define XmNpopupCallback		XtNpopupCallback
#endif

#ifndef XmNresize
#define XmNresize			XtNresize
#endif

#ifndef XmNreverseVideo
#define XmNreverseVideo			XtNreverseVideo
#endif

#ifndef XmNsaveUnder
#define XmNsaveUnder			XtNsaveUnder
#endif

#ifndef XmNscreen
#define XmNscreen			XtNscreen
#endif

#ifndef XmNscrollDCursor
#define XmNscrollDCursor		XtNscrollDCursor
#endif

#ifndef XmNscrollHCursor
#define XmNscrollHCursor		XtNscrollHCursor
#endif

#ifndef XmNscrollLCursor
#define XmNscrollLCursor		XtNscrollLCursor
#endif

#ifndef XmNscrollProc
#define XmNscrollProc			XtNscrollProc
#endif

#ifndef XmNscrollRCursor
#define XmNscrollRCursor		XtNscrollRCursor
#endif

#ifndef XmNscrollUCursor
#define XmNscrollUCursor		XtNscrollUCursor
#endif

#ifndef XmNscrollVCursor
#define XmNscrollVCursor		XtNscrollVCursor
#endif

#ifndef XmNselection
#define XmNselection			XtNselection
#endif

#ifndef XmNselectionArray
#define XmNselectionArray		XtNselectionArray
#endif

#ifndef XmNsensitive
#define XmNsensitive			XtNsensitive
#endif

#ifndef XmNshown
#define XmNshown			XtNshown
#endif

#ifndef XmNspace
#define XmNspace			XtNspace
#endif

#ifndef XmNstring
#define XmNstring			XtNstring
#endif

#ifndef XmNtextOptions
#define XmNtextOptions			XtNtextOptions
#endif

#ifndef XmNtextSink
#define XmNtextSink			XtNtextSink
#endif

#ifndef XmNtextSource
#define XmNtextSource			XtNtextSource
#endif

#ifndef XmNthickness
#define XmNthickness			XtNthickness
#endif

#ifndef XmNthumb
#define XmNthumb			XtNthumb
#endif

#ifndef XmNthumbProc
#define XmNthumbProc			XtNthumbProc
#endif

#ifndef XmNtitle
#define XmNtitle			XtNtitle
#endif

#ifndef XmNtitleEncoding
#define XmNtitleEncoding		XtNtitleEncoding
#endif

#ifndef XmNtop
#define XmNtop				XtNtop
#endif

#ifndef XmNtransient
#define XmNtransient			XtNtransient
#endif

#ifndef XmNtransientFor
#define XmNtransientFor			XtNtransientFor
#endif

#ifndef XmNtransientFor
#define XmNtransientFor			XtNtransientFor
#endif

#ifndef XmNtranslations
#define XmNtranslations			XtNtranslations
#endif

#ifndef XmNupdate
#define XmNupdate			XtNupdate
#endif

#ifndef XmNuseBottom
#define XmNuseBottom			XtNuseBottom
#endif

#ifndef XmNuseRight
#define XmNuseRight			XtNuseRight
#endif

#ifndef XmNvalue
#define XmNvalue			XtNvalue
#endif

#ifndef XmNvisual
#define XmNvisual			XtNvisual
#endif

#ifndef XmNwaitForWm
#define XmNwaitForWm			XtNwaitForWm
#endif

#ifndef XmNwidth
#define XmNwidth			XtNwidth
#endif

#ifndef XmNwidthInc
#define XmNwidthInc			XtNwidthInc
#endif

#ifndef XmNwinGravity
#define XmNwinGravity			XtNwinGravity
#endif

#ifndef XmNwindow
#define XmNwindow			XtNwindow
#endif

#ifndef XmNwindowGroup
#define XmNwindowGroup			XtNwindowGroup
#endif

#ifndef XmNwmTimeout
#define XmNwmTimeout			XtNwmTimeout
#endif

#ifndef XmNx
#define XmNx				XtNx
#endif

#ifndef XmNy
#define XmNy				XtNy
#endif

#ifndef XmRAcceleratorTable
#define XmRAcceleratorTable		XtRAcceleratorTable
#endif

#ifndef XmRAtom
#define XmRAtom				XtRAtom
#endif

#ifndef XmRBitmap
#define XmRBitmap			XtRBitmap
#endif

#ifndef XmRBool
#define XmRBool				XtRBool
#endif

#ifndef XmRBoolean
#define XmRBoolean			XtRBoolean
#endif

#ifndef XmRCallProc
#define XmRCallProc			XtRCallProc
#endif

#ifndef XmRCallback
#define XmRCallback			XtRCallback
#endif

#ifndef XmRCardinal
#define XmRCardinal			XtRCardinal
#endif

#ifndef XmRColor
#define XmRColor			XtRColor
#endif

#ifndef XmRColormap
#define XmRColormap			XtRColormap
#endif

#ifndef XmRCursor
#define XmRCursor			XtRCursor
#endif

#ifndef XmRDimension
#define XmRDimension			XtRDimension
#endif

#ifndef XmRDisplay
#define XmRDisplay			XtRDisplay
#endif

#ifndef XmREditMode
#define XmREditMode			XtREditMode
#endif

#ifndef XmREnum
#define XmREnum			        XtREnum
#endif

#ifndef XmRFile
#define XmRFile				XtRFile
#endif

#ifndef XmRFloat
#define XmRFloat			XtRFloat
#endif

#ifndef XmRFont
#define XmRFont				XtRFont
#endif

#ifndef XmRFontSet
#define XmRFontSet		        XtRFontSet
#endif

#ifndef XmRFontStruct
#define XmRFontStruct			XtRFontStruct
#endif

#ifndef XmRFunction
#define XmRFunction			XtRFunction
#endif

#ifndef XmRGeometry
#define XmRGeometry			XtRGeometry
#endif

#ifndef XmRImmediate
#define XmRImmediate			XtRImmediate
#endif

#ifndef XmRInitialState
#define XmRInitialState		        XtRInitialState
#endif

#ifndef XmRInt
#define XmRInt				XtRInt
#endif

#ifndef XmRJustify
#define XmRJustify			XtRJustify
#endif

#ifndef XmRLongBoolean
#define XmRLongBoolean		        XtRLongBoolean
#endif

#ifndef XmROrientation
#define XmROrientation			XtROrientation
#endif

#ifndef XmRObject
#define XmRObject		        XtRObject
#endif

#ifndef XmRPixel
#define XmRPixel			XtRPixel
#endif

#ifndef XmRPixmap
#define XmRPixmap			XtRPixmap
#endif

#ifndef XmRPointer
#define XmRPointer			XtRPointer
#endif

#ifndef XmRPosition
#define XmRPosition			XtRPosition
#endif

#ifndef XmRScreen
#define XmRScreen	                XtRScreen
#endif

#ifndef XmRShort
#define XmRShort			XtRShort
#endif

#ifndef XmRString
#define XmRString			XtRString
#endif

#ifndef XmRStringArray
#define XmRStringArray		        XtRStringArray
#endif

#ifndef XmRStringTable
#define XmRStringTable			XtRStringTable
#endif

#ifndef XmRTextPosition
#define XmRTextPosition			XtCTextPosition
#endif

#ifndef XmRTranslationTable
#define XmRTranslationTable		XtRTranslationTable
#endif

#ifndef XmRUnsignedChar
#define XmRUnsignedChar			XtRUnsignedChar
#endif

#ifndef XmRVisual
#define XmRVisual		        XtRVisual
#endif

#ifndef XmRWidget
#define XmRWidget			XtRWidget
#endif

#ifndef XmRWidgetClass
#define XmRWidgetClass			XtRWidgetClass
#endif

#ifndef XmRWidgetList
#define XmRWidgetList			XtRWidgetList
#endif

#ifndef XmRWindow
#define XmRWindow			XtRWindow
#endif

#ifndef XmNtoolTipString
#define XmNtoolTipString 		"toolTipString"
#endif

#ifndef XmCToolTipString
#define XmCToolTipString 		"ToolTipString"
#endif

#ifndef XmNtoolTipPostDelay
#define XmNtoolTipPostDelay 		"toolTipPostDelay"
#endif

#ifndef XmCToolTipPostDelay
#define XmCToolTipPostDelay 		"ToolTipPostDelay"
#endif

#ifndef XmNtoolTipPostDuration
#define XmNtoolTipPostDuration 		"toolTipPostDuration"
#endif

#ifndef XmCToolTipPostDuration
#define XmCToolTipPostDuration 		"ToolTipPostDuration"
#endif

#ifndef XmNtoolTipEnable
#define XmNtoolTipEnable 		"toolTipEnable"
#endif

#ifndef XmCToolTipEnable
#define XmCToolTipEnable 		"ToolTipEnable"
#endif

#ifndef XmNanimate
#define XmNanimate			"animate"
#endif

#ifndef XmCAnimate
#define XmCAnimate			"Animate"
#endif

#ifdef __cplusplus
}  /* Close scope of 'extern "C"' declaration */
#endif

#endif /* _XmStrDefs_h_ */
