/* $TOG: XmStrDefs23.ht /main/2 1997/06/18 17:50:15 samborn $ */
#ifndef _XmStrDefs23_h_
#define _XmStrDefs23_h_

#include <X11/Intrinsic.h>

/* $TOG: makestrs.c /main/11 1998/02/06 11:24:15 kaleb $ */
/* This file is automatically generated. */
/* Default ABI version -- Do not edit */
/* TOG: xmstring.list /main/5 1997/06/20 08:37:02 samborn */

#ifdef XMSTRINGDEFINES
#define XmNdefaultEntryLabelRenderTable "defaultEntryLabelRenderTable"
#define XmNentryLabelRenderTable "entryLabelRenderTable"
#define XmNpixmapPlacement "pixmapPlacement"
#define XmCPixmapPlacement "PixmapPlacement"
#define XmRPixmapPlacement "PixmapPlacement"
#define XmNpixmapTextPadding "pixmapTextPadding"
#define XmNfontStyle "fontStyle"
#define XmCFontStyle "FontStyle"
#define XmNfontSize "fontSize"
#define XmCFontSize "FontSize"
#define XmNfontFoundry "fontFoundry"
#define XmCFontFoundry "FontFoundry"
#define XmNfontEncoding "fontEncoding"
#define XmCFontEncoding "FontEncoding"
#define XmNxftFont "xftFont"
#define XmCXftFont "XftFont"
#define XmSUTF8_STRING "UTF8_STRING"
extern  char _XmStrings23[];



