# 0 "Imakefile.c"
# 0 "<built-in>"
# 0 "<command-line>"




# 1 "/usr/include/stdc-predef.h" 1 3 4

# 17 "/usr/include/stdc-predef.h" 3 4



















# 45 "/usr/include/stdc-predef.h" 3 4

# 55 "/usr/include/stdc-predef.h" 3 4









# 4 "<command-line>" 2
# 1 "Imakefile.c"
