/* Header file generated by fdesign on Thu Dec 12 21:27:07 2013 */

#ifndef FD_browserattrib_h_
#define FD_browserattrib_h_

#include  "../lib/include/forms.h" 

/* Callbacks, globals and object handlers */

void add_item_cb( FL_OBJECT *, long );
void delete_item_cb( FL_OBJECT *, long );
void insert_cb( FL_OBJECT *, long );
void hscb_pref_cb( FL_OBJECT *, long );
void vscb_pref_cb( FL_OBJECT *, long );
void br_returnsetting_change( FL_OBJECT *, long );
void clear_field_cb( FL_OBJECT *, long );
void replace_item_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * browserattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * content_br;
    FL_OBJECT * input;
    FL_OBJECT * hscb_pref;
    FL_OBJECT * vscb_pref;
    FL_OBJECT * returnsetting;
    FL_OBJECT * auto_clear;
} FD_browserattrib;

FD_browserattrib * create_form_browserattrib( void );

#endif /* FD_browserattrib_h_ */
