/* Header file generated by fdesign on Thu Dec 12 21:27:07 2013 */

#ifndef FD_counterattrib_h_
#define FD_counterattrib_h_

#include  "../lib/include/forms.h" 

/* Callbacks, globals and object handlers */

void cnt_precision_cb( FL_OBJECT *, long );
void cnt_minmax_change( FL_OBJECT *, long );
void cnt_returnsetting_change( FL_OBJECT *, long );
void cnt_initialvalue_change( FL_OBJECT *, long );
void cnt_stepchange_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * counterattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * prec;
    FL_OBJECT * minval;
    FL_OBJECT * maxval;
    FL_OBJECT * returnsetting;
    FL_OBJECT * initialval;
    FL_OBJECT * step1;
    FL_OBJECT * step2;
} FD_counterattrib;

FD_counterattrib * create_form_counterattrib( void );

#endif /* FD_counterattrib_h_ */
