/* Form definition file generated by fdesign on Thu Dec 12 21:27:07 2013 */

#include <stdlib.h>
#include "menu_spec.h"



/***************************************
 ***************************************/

FD_menuattrib *
create_form_menuattrib( void )
{
    FL_OBJECT *obj;
    FD_menuattrib *fdui = ( FD_menuattrib * ) fl_malloc( sizeof *fdui );

    int old_bw = fl_get_border_width( );
    fl_set_border_width( -1 );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->menuattrib = fl_bgn_form( FL_NO_BOX, 520, 270 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 520, 270, "" );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 15, 20, 480, 230, "Menu Attributes" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 25, 65, 190, 170, "Item Attributes" );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 225, 67, 111, 140, "Action" );

    fdui->content_br = obj = fl_add_browser( FL_HOLD_BROWSER, 353, 70, 120, 140, "CurrentItems:" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );

    fdui->input = obj = fl_add_input( FL_NORMAL_INPUT, 35, 90, 170, 25, "EditItem" );
    fl_set_input_shortcut( obj, "#E", 1 );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );

    obj = fl_add_button( FL_NORMAL_BUTTON, 235, 82, 84, 26, "Add" );
    fl_set_button_shortcut( obj, "#A", 1 );
    fl_set_object_callback( obj, add_menu_item_cb, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 235, 143, 84, 24, "Delete" );
    fl_set_button_shortcut( obj, "#D", 1 );
    fl_set_object_callback( obj, delete_menu_item_cb, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 235, 172, 84, 24, "Change" );
    fl_set_button_shortcut( obj, "#C", 1 );
    fl_set_object_callback( obj, change_menu_item_cb, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 320, 220, 82, 24, "ClearField" );
    fl_set_object_callback( obj, clear_menu_field_cb, 0 );

    fdui->auto_clear = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 230, 220, 24, 27, "AutoClear" );
    fl_set_object_color( obj, FL_COL1, FL_BLUE );
    fl_set_button( obj, 1 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 235, 112, 84, 26, "Replace" );
    fl_set_button_shortcut( obj, "#R", 1 );
    fl_set_object_callback( obj, replace_menu_item_cb, 0 );

    fdui->mode = obj = fl_add_choice( FL_NORMAL_CHOICE2, 106, 133, 98, 25, "Mode" );
    fl_set_object_shortcut( obj, "#M", 1 );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );

    fdui->shortcut = obj = fl_add_input( FL_NORMAL_INPUT, 35, 133, 70, 25, "Shortcut" );
    fl_set_input_shortcut( obj, "#S", 1 );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );

    fdui->item_cb = obj = fl_add_input( FL_NORMAL_INPUT, 35, 176, 170, 25, "Callback" );
    fl_set_input_shortcut( obj, "#B", 1 );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );

    fdui->new_menuapi = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 280, 21, 35, 30, "Use Struct" );
    fl_set_button_shortcut( obj, "#U", 1 );
    fl_set_object_callback( obj, new_menuapi_cb, 0 );

    fdui->scope = obj = fl_add_choice( FL_NORMAL_CHOICE2, 365, 25, 75, 22, "" );
    fl_set_object_callback( obj, menuentry_scope_cb, 0 );

    fdui->id = obj = fl_add_counter( FL_NORMAL_COUNTER, 90, 210, 110, 20, "MenuID" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT );
    fl_set_counter_bounds( obj, 1.0, 1000000.0 );
    fl_set_counter_value( obj, 1.0 );
    fl_set_counter_step( obj, 1.0, 10.0 );

    fl_end_form( );

    fdui->menuattrib->fdui = fdui;
    fl_set_border_width( old_bw );

    return fdui;
}
