/* Header file generated by fdesign on Thu Dec 12 21:27:07 2013 */

#ifndef FD_pixmapattrib_h_
#define FD_pixmapattrib_h_

#include  "../lib/include/forms.h" 

/* Callbacks, globals and object handlers */

void pixmap_filename_change( FL_OBJECT *, long );
void pixmapalign_change( FL_OBJECT *, long );
void pixmaplookfor_pixmapfile_cb( FL_OBJECT *, long );
void pixmapusedata_change( FL_OBJECT *, long );
void pixmapfullpath_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * pixmapattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * frame;
    FL_OBJECT * filename;
    FL_OBJECT * pixalign;
    FL_OBJECT * browse;
    FL_OBJECT * use_data;
    FL_OBJECT * fullpath;
} FD_pixmapattrib;

FD_pixmapattrib * create_form_pixmapattrib( void );

#endif /* FD_pixmapattrib_h_ */
