/* Header file generated by fdesign on Thu Dec 12 21:27:07 2013 */

#ifndef FD_scrollbarattrib_h_
#define FD_scrollbarattrib_h_

#include  "../lib/include/forms.h" 

/* Callbacks, globals and object handlers */

void scb_minmax_change( FL_OBJECT *, long );
void scb_returnsetting_change( FL_OBJECT *, long );
void scb_initialvalue_change( FL_OBJECT *, long );
void scb_slsize_change( FL_OBJECT *, long );
void scb_delta_change( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * scrollbarattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * minval;
    FL_OBJECT * maxval;
    FL_OBJECT * returnsetting;
    FL_OBJECT * initial_val;
    FL_OBJECT * slsize;
    FL_OBJECT * ldelta;
    FL_OBJECT * rdelta;
} FD_scrollbarattrib;

FD_scrollbarattrib * create_form_scrollbarattrib( void );

#endif /* FD_scrollbarattrib_h_ */
