/* Header file generated by fdesign on Thu Dec 12 21:27:07 2013 */

#ifndef FD_sliderattrib_h_
#define FD_sliderattrib_h_

#include  "../lib/include/forms.h" 

/* Callbacks, globals and object handlers */

void adjust_precision( FL_OBJECT *, long );
void minmax_change( FL_OBJECT *, long );
void returnsetting_change( FL_OBJECT *, long );
void initialvalue_change( FL_OBJECT *, long );
void slsize_change( FL_OBJECT *, long );
void step_change( FL_OBJECT *, long );
void increment_change( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * sliderattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * prec;
    FL_OBJECT * minval;
    FL_OBJECT * maxval;
    FL_OBJECT * returnsetting;
    FL_OBJECT * initial_val;
    FL_OBJECT * slsize;
    FL_OBJECT * step;
    FL_OBJECT * ldelta;
    FL_OBJECT * rdelta;
} FD_sliderattrib;

FD_sliderattrib * create_form_sliderattrib( void );

#endif /* FD_sliderattrib_h_ */
