unit XmStrDefs;

interface


uses
  XTIntrinsic,
  XtShell,
  XTStringdefs;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}

//{$include <X11/Intrinsic.h>}

{ C++ extern C conditionnal removed }
{ $TOG: makestrs.c /main/11 1998/02/06 11:24:15 kaleb $  }
{ This file is automatically generated.  }
{ Default ABI version -- Do not edit  }
{ TOG: xmstring.list /main/5 1997/06/20 08:37:02 samborn  }

const
  XmS = '';  
  XmCAccelerator = 'Accelerator';  
  XmCAcceleratorText = 'AcceleratorText';  
  XmCAdjustLast = 'AdjustLast';  
  XmCAdjustMargin = 'AdjustMargin';  
  XmCAlignment = 'Alignment';  
  XmCAllowOverlap = 'AllowOverlap';  
  XmCAllowUnusedSpace = 'AllowUnusedSpace';  
  XmCAnimationMask = 'AnimationMask';  
  XmCAnimationPixmap = 'AnimationPixmap';  
  XmCAnimationPixmapDepth = 'AnimationPixmapDepth';  
  XmCAnimationStyle = 'AnimationStyle';  
  XmCApplyLabelString = 'ApplyLabelString';  
  XmCArmCallback = 'ArmCallback';  
  XmCArmColor = 'ArmColor';  
  XmCArmPixmap = 'ArmPixmap';  
  XmCArrowDirection = 'ArrowDirection';  
  XmCAttachment = 'Attachment';  
  XmCAudibleWarning = 'AudibleWarning';  
  XmCAutoShowCursorPosition = 'AutoShowCursorPosition';  
  XmCAutoUnmanage = 'AutoUnmanage';  
  XmCAutomaticSelection = 'AutomaticSelection';  
  XmCAvailability = 'Availability';  
  XmCBackgroundPixmap = 'BackgroundPixmap';  
  XmCBlendModel = 'BlendModel';  
  XmCBlinkRate = 'BlinkRate';  
  XmCBottomShadowColor = 'BottomShadowColor';  
  XmCBottomShadowPixmap = 'BottomShadowPixmap';  
  XmCButtonAcceleratorText = 'ButtonAcceleratorText';  
  XmCButtonAccelerators = 'ButtonAccelerators';  
  XmCButtonCount = 'ButtonCount';  
  XmCButtonFontList = 'ButtonFontList';  
  XmCButtonMnemonicCharSets = 'ButtonMnemonicCharSets';  
  XmCButtonMnemonics = 'ButtonMnemonics';  
  XmCButtonSet = 'ButtonSet';  
  XmCButtonType = 'ButtonType';  
  XmCButtons = 'Buttons';  
  XmCCancelLabelString = 'CancelLabelString';  
  XmCChildHorizontalAlignment = 'ChildHorizontalAlignment';  
  XmCChildHorizontalSpacing = 'ChildHorizontalSpacing';  
  XmCChildPlacement = 'ChildPlacement';  
  XmCChildType = 'ChildType';  
  XmCChildVerticalAlignment = 'ChildVerticalAlignment';  
  XmCChildren = 'Children';  
  XmCClientData = 'ClientData';  
  XmCClipWindow = 'ClipWindow';  
  XmCColumns = 'Columns';  
  XmCCommandWindow = 'CommandWindow';  
  XmCCommandWindowLocation = 'CommandWindowLocation';  
  XmCConvertProc = 'ConvertProc';  
  XmCCursorBackground = 'CursorBackground';  
  XmCCursorForeground = 'CursorForeground';  
  XmCCursorPosition = 'CursorPosition';  
  XmCCursorPositionVisible = 'CursorPositionVisible';  
  XmCDarkThreshold = 'DarkThreshold';  
  XmCDecimalPoints = 'DecimalPoints';  
  XmCDefaultButtonShadowThickness = 'DefaultButtonShadowThickness';  
  XmCDefaultButtonType = 'DefaultButtonType';  
  XmCDefaultCopyCursorIcon = 'DefaultCopyCursorIcon';  
  XmCDefaultFontList = 'DefaultFontList';  
  XmCDefaultInvalidCursorIcon = 'DefaultInvalidCursorIcon';  
  XmCDefaultLinkCursorIcon = 'DefaultLinkCursorIcon';  
  XmCDefaultMoveCursorIcon = 'DefaultMoveCursorIcon';  
  XmCDefaultNoneCursorIcon = 'DefaultNoneCursorIcon';  
  XmCDefaultPosition = 'DefaultPosition';  
  XmCDefaultSourceCursorIcon = 'DefaultSourceCursorIcon';  
  XmCDefaultValidCursorIcon = 'DefaultValidCursorIcon';  
  XmCDeleteResponse = 'DeleteResponse';  
  XmCDesktopParent = 'DesktopParent';  
  XmCDialogStyle = 'DialogStyle';  
  XmCDialogTitle = 'DialogTitle';  
  XmCDialogType = 'DialogType';  
  XmCDirListItemCount = 'DirListItemCount';  
  XmCDirListItems = 'DirListItems';  
  XmCDirListLabelString = 'DirListLabelString';  
  XmCDirMask = 'DirMask';  
  XmCDirSearchProc = 'DirSearchProc';  
  XmCDirSpec = 'DirSpec';  
  XmCDirectory = 'Directory';  
  XmCDirectoryValid = 'DirectoryValid';  
  XmCDisarmCallback = 'DisarmCallback';  
  XmCDoubleClickInterval = 'DoubleClickInterval';  
  XmCDragContextClass = 'DragContextClass';  
  XmCDragDropFinishCallback = 'DragDropFinishCallback';  
  XmCDragIconClass = 'DragIconClass';  
  XmCDragInitiatorProtocolStyle = 'DragInitiatorProtocolStyle';  
  XmCDragMotionCallback = 'DragMotionCallback';  
  XmCDragOperations = 'DragOperations';  
  XmCDragOverMode = 'DragOverMode';  
  XmCDragProc = 'DragProc';  
  XmCDragReceiverProtocolStyle = 'DragReceiverProtocolStyle';  
  XmCDropProc = 'DropProc';  
  XmCDropRectangles = 'DropRectangles';  
  XmCDropSiteActivity = 'DropSiteActivity';  
  XmCDropSiteEnterCallback = 'DropSiteEnterCallback';  
  XmCDropSiteLeaveCallback = 'DropSiteLeaveCallback';  
  XmCDropSiteManagerClass = 'DropSiteManagerClass';  
  XmCDropSiteOperations = 'DropSiteOperations';  
  XmCDropSiteType = 'DropSiteType';  
  XmCDropStartCallback = 'DropStartCallback';  
  XmCDropTransferClass = 'DropTransferClass';  
  XmCDropTransfers = 'DropTransfers';  
  XmCEditable = 'Editable';  
  XmCEntryBorder = 'EntryBorder';  
  XmCEntryClass = 'EntryClass';  
  XmCExportTargets = 'ExportTargets';  
  XmCExposeCallback = 'ExposeCallback';  
  XmCExtensionType = 'ExtensionType';  
  XmCFileListItemCount = 'FileListItemCount';  
  XmCFileListItems = 'FileListItems';  
  XmCFileListLabelString = 'FileListLabelString';  
  XmCFileSearchProc = 'FileSearchProc';  
  XmCFileTypeMask = 'FileTypeMask';  
  XmCFillOnArm = 'FillOnArm';  
  XmCFillOnSelect = 'FillOnSelect';  
  XmCFilterLabelString = 'FilterLabelString';  
  XmCFontList = 'FontList';  
  XmCForegroundThreshold = 'ForegroundThreshold';  
  XmCHelpLabelString = 'HelpLabelString';  
  XmCHighlightColor = 'HighlightColor';  
  XmCHighlightOnEnter = 'HighlightOnEnter';  
  XmCHighlightPixmap = 'HighlightPixmap';  
  XmCHighlightThickness = 'HighlightThickness';  
  XmCHorizontalFontUnit = 'HorizontalFontUnit';  
  XmCHorizontalScrollBar = 'HorizontalScrollBar';  
  XmCHot = 'Hot';  
  XmCICCHandle = 'ICCHandle';  
  XmCImportTargets = 'ImportTargets';  
  XmCIncrement = 'Increment';  
  XmCIncremental = 'Incremental';  
  XmCIndicatorOn = 'IndicatorOn';  
  XmCIndicatorSize = 'IndicatorSize';  
  XmCIndicatorType = 'IndicatorType';  
  XmCInitialDelay = 'InitialDelay';  
  XmCInitialFocus = 'InitialFocus';  
  XmCInputCreate = 'InputCreate';  
  XmCInputMethod = 'InputMethod';  
  XmCInvalidCursorForeground = 'InvalidCursorForeground';  
  XmCIsAligned = 'IsAligned';  
  XmCIsHomogeneous = 'IsHomogeneous';  
  XmCItemCount = 'ItemCount';  
  XmCItems = 'Items';  
  XmCKeyboardFocusPolicy = 'KeyboardFocusPolicy';  
  XmCLabelFontList = 'LabelFontList';  
  XmCLabelInsensitivePixmap = 'LabelInsensitivePixmap';  
  XmCLabelPixmap = 'LabelPixmap';  
  XmCLabelString = 'LabelString';  
  XmCLabelType = 'LabelType';  
  XmCLightThreshold = 'LightThreshold';  
  XmCListLabelString = 'ListLabelString';  
  XmCListMarginHeight = 'ListMarginHeight';  
  XmCListMarginWidth = 'ListMarginWidth';  
  XmCListSizePolicy = 'ListSizePolicy';  
  XmCListSpacing = 'ListSpacing';  
  XmCListUpdated = 'ListUpdated';  
  XmCLogicalParent = 'LogicalParent';  
  XmCMainWindowMarginHeight = 'MainWindowMarginHeight';  
  XmCMainWindowMarginWidth = 'MainWindowMarginWidth';  
  XmCMappingDelay = 'MappingDelay';  
  XmCMarginBottom = 'MarginBottom';  
  XmCMarginHeight = 'MarginHeight';  
  XmCMarginLeft = 'MarginLeft';  
  XmCMarginRight = 'MarginRight';  
  XmCMarginTop = 'MarginTop';  
  XmCMarginWidth = 'MarginWidth';  
  XmCMask = 'Mask';  
  XmCMaxItems = 'MaxItems';  
  XmCMaxLength = 'MaxLength';  
  XmCMaxValue = 'MaxValue';  
  XmCMaximum = 'Maximum';  
  XmCMenuBar = 'MenuBar';  
  XmCMenuPost = 'MenuPost';  
  XmCMenuWidget = 'MenuWidget';  
  XmCMessageProc = 'MessageProc';  
  XmCMessageWindow = 'MessageWindow';  
  XmCMinimizeButtons = 'MinimizeButtons';  
  XmCMinimum = 'Minimum';  
  XmCMnemonic = 'Mnemonic';  
  XmCMnemonicCharSet = 'MnemonicCharSet';  
  XmCMoveOpaque = 'MoveOpaque';  
  XmCMultiClick = 'MultiClick';  
  XmCMustMatch = 'MustMatch';  
  XmCMwmDecorations = 'MwmDecorations';  
  XmCMwmFunctions = 'MwmFunctions';  
  XmCMwmInputMode = 'MwmInputMode';  
  XmCMwmMenu = 'MwmMenu';  
  XmCMwmMessages = 'MwmMessages';  
  XmCNavigationType = 'NavigationType';  
  XmCNeedsMotion = 'NeedsMotion';  
  XmCNoMatchString = 'NoMatchString';  
  XmCNoResize = 'NoResize';  
  XmCNoneCursorForeground = 'NoneCursorForeground';  
  XmCNotifyProc = 'NotifyProc';  
  XmCNumChildren = 'NumChildren';  
  XmCNumColumns = 'NumColumns';  
  XmCNumDropRectangles = 'NumDropRectangles';  
  XmCNumDropTransfers = 'NumDropTransfers';  
  XmCNumExportTargets = 'NumExportTargets';  
  XmCNumImportTargets = 'NumImportTargets';  
  XmCOffset = 'Offset';  
  XmCOkLabelString = 'OkLabelString';  
  XmCOperationChangedCallback = 'OperationChangedCallback';  
  XmCOperationCursorIcon = 'OperationCursorIcon';  
  XmCOptionLabel = 'OptionLabel';  
  XmCOptionMnemonic = 'OptionMnemonic';  
  XmCOutputCreate = 'OutputCreate';  
  XmCPacking = 'Packing';  
  XmCPageIncrement = 'PageIncrement';  
  XmCPaneMaximum = 'PaneMaximum';  
  XmCPaneMinimum = 'PaneMinimum';  
  XmCPattern = 'Pattern';  
  XmCPendingDelete = 'PendingDelete';  
  XmCPopupEnabled = 'PopupEnabled';  
  XmCPositionIndex = 'PositionIndex';  
  XmCPostFromButton = 'PostFromButton';  
  XmCPostFromCount = 'PostFromCount';  
  XmCPostFromList = 'PostFromList';  
  XmCPreeditType = 'PreeditType';  
  XmCProcessingDirection = 'ProcessingDirection';  
  XmCPromptString = 'PromptString';  
  XmCProtocolCallback = 'ProtocolCallback';  
  XmCPushButtonEnabled = 'PushButtonEnabled';  
  XmCQualifySearchDataProc = 'QualifySearchDataProc';  
  XmCRadioAlwaysOne = 'RadioAlwaysOne';  
  XmCRadioBehavior = 'RadioBehavior';  
  XmCRecomputeSize = 'RecomputeSize';  
  XmCRectangles = 'Rectangles';  
  XmCRepeatDelay = 'RepeatDelay';  
  XmCResizeCallback = 'ResizeCallback';  
  XmCResizeHeight = 'ResizeHeight';  
  XmCResizePolicy = 'ResizePolicy';  
  XmCResizeWidth = 'ResizeWidth';  
  XmCRowColumnType = 'RowColumnType';  
  XmCRows = 'Rows';  
  XmCRubberPositioning = 'RubberPositioning';  
  XmCSashHeight = 'SashHeight';  
  XmCSashIndent = 'SashIndent';  
  XmCSashWidth = 'SashWidth';  
  XmCScaleHeight = 'ScaleHeight';  
  XmCScaleMultiple = 'ScaleMultiple';  
  XmCScaleWidth = 'ScaleWidth';  
  XmCScroll = 'Scroll';  
  XmCScrollBarDisplayPolicy = 'ScrollBarDisplayPolicy';  
  XmCScrollBarPlacement = 'ScrollBarPlacement';  
  XmCScrollSide = 'ScrollSide';  
  XmCScrolledWindowMarginHeight = 'ScrolledWindowMarginHeight';  
  XmCScrolledWindowMarginWidth = 'ScrolledWindowMarginWidth';  
  XmCScrollingPolicy = 'ScrollingPolicy';  
  XmCSelectColor = 'SelectColor';  
  XmCSelectInsensitivePixmap = 'SelectInsensitivePixmap';  
  XmCSelectPixmap = 'SelectPixmap';  
  XmCSelectThreshold = 'SelectThreshold';  
  XmCSelectedItemCount = 'SelectedItemCount';  
  XmCSelectedItems = 'SelectedItems';  
  XmCSelectionArrayCount = 'SelectionArrayCount';  
  XmCSelectionLabelString = 'SelectionLabelString';  
  XmCSelectionPolicy = 'SelectionPolicy';  
  XmCSeparatorOn = 'SeparatorOn';  
  XmCSeparatorType = 'SeparatorType';  
  XmCSet = 'Set';  
  XmCShadowThickness = 'ShadowThickness';  
  XmCShadowType = 'ShadowType';  
  XmCShellUnitType = 'ShellUnitType';  
  XmCShowArrows = 'ShowArrows';  
  XmCShowAsDefault = 'ShowAsDefault';  
  XmCShowSeparator = 'ShowSeparator';  
  XmCShowValue = 'ShowValue';  
  XmCSimpleCheckBox = 'SimpleCheckBox';  
  XmCSimpleMenuBar = 'SimpleMenuBar';  
  XmCSimpleOptionMenu = 'SimpleOptionMenu';  
  XmCSimplePopupMenu = 'SimplePopupMenu';  
  XmCSimplePulldownMenu = 'SimplePulldownMenu';  
  XmCSimpleRadioBox = 'SimpleRadioBox';  
  XmCSizePolicy = 'SizePolicy';  
  XmCSliderSize = 'SliderSize';  
  XmCSource = 'Source';  
  XmCSourceCursorIcon = 'SourceCursorIcon';  
  XmCSourceIsExternal = 'SourceIsExternal';  
  XmCSourcePixmapIcon = 'SourcePixmapIcon';  
  XmCSourceWidget = 'SourceWidget';  
  XmCSourceWindow = 'SourceWindow';  
  XmCSpacing = 'Spacing';  
  XmCStartTime = 'StartTime';  
  XmCStateCursorIcon = 'StateCursorIcon';  
  XmCStringDirection = 'StringDirection';  
  XmCTearOffModel = 'TearOffModel';  
  XmCTextFontList = 'TextFontList';  
  XmCTextString = 'TextString';  
  XmCTextValue = 'TextValue';  
  XmCTitleString = 'TitleString';  
  XmCTopCharacter = 'TopCharacter';  
  XmCTopItemPosition = 'TopItemPosition';  
  XmCTopLevelEnterCallback = 'TopLevelEnterCallback';  
  XmCTopLevelLeaveCallback = 'TopLevelLeaveCallback';  
  XmCTopShadowColor = 'TopShadowColor';  
  XmCTopShadowPixmap = 'TopShadowPixmap';  
  XmCTransferProc = 'TransferProc';  
  XmCTransferStatus = 'TransferStatus';  
  XmCTraversalOn = 'TraversalOn';  
  XmCTraversalType = 'TraversalType';  
  XmCTreeUpdateProc = 'TreeUpdateProc';  
  XmCTroughColor = 'TroughColor';  
  XmCUnitType = 'UnitType';  
  XmCUnpostBehavior = 'UnpostBehavior';  
  XmCUnselectPixmap = 'UnselectPixmap';  
  XmCUpdateSliderSize = 'UpdateSliderSize';  
  XmCUseAsyncGeometry = 'UseAsyncGeometry';  
  XmCUserData = 'UserData';  
  XmCValidCursorForeground = 'ValidCursorForeground';  
  XmCValueChangedCallback = 'ValueChangedCallback';  
  XmCValueWcs = 'ValueWcs';  
  XmCVerifyBell = 'VerifyBell';  
  XmCVerticalAlignment = 'VerticalAlignment';  
  XmCVerticalFontUnit = 'VerticalFontUnit';  
  XmCVerticalScrollBar = 'VerticalScrollBar';  
  XmCVisibleItemCount = 'VisibleItemCount';  
  XmCVisibleWhenOff = 'VisibleWhenOff';  
  XmCVisualPolicy = 'VisualPolicy';  
  XmCWhichButton = 'WhichButton';  
  XmCWordWrap = 'WordWrap';  
  XmCWorkWindow = 'WorkWindow';  
  XmCXmString = 'XmString';  
  XmNaccelerator = 'accelerator';  
  XmNacceleratorText = 'acceleratorText';  
  XmNactivateCallback = 'activateCallback';  
  XmNadjustLast = 'adjustLast';  
  XmNadjustMargin = 'adjustMargin';  
  XmNalignment = 'alignment';  
  XmNallowOverlap = 'allowOverlap';  
  XmNallowResize = 'allowResize';  
  XmNallowUnusedSpace = 'allowUnusedSpace';  
  XmNanimationMask = 'animationMask';  
  XmNanimationPixmap = 'animationPixmap';  
  XmNanimationPixmapDepth = 'animationPixmapDepth';  
  XmNanimationStyle = 'animationStyle';  
  XmNapplyCallback = 'applyCallback';  
  XmNapplyLabelString = 'applyLabelString';  
  XmNarmCallback = 'armCallback';  
  XmNarmColor = 'armColor';  
  XmNarmPixmap = 'armPixmap';  
  XmNarrowDirection = 'arrowDirection';  
  XmNattachment = 'attachment';  
  XmNaudibleWarning = 'audibleWarning';  
  XmNautoShowCursorPosition = 'autoShowCursorPosition';  
  XmNautoUnmanage = 'autoUnmanage';  
  XmNautomaticSelection = 'automaticSelection';  
  XmNavailability = 'availability';  
  XmNblendModel = 'blendModel';  
  XmNblinkRate = 'blinkRate';  
  XmNbottomAttachment = 'bottomAttachment';  
  XmNbottomOffset = 'bottomOffset';  
  XmNbottomPosition = 'bottomPosition';  
  XmNbottomShadowColor = 'bottomShadowColor';  
  XmNbottomShadowPixmap = 'bottomShadowPixmap';  
  XmNbottomWidget = 'bottomWidget';  
  XmNbrowseSelectionCallback = 'browseSelectionCallback';  
  XmNbuttonAcceleratorText = 'buttonAcceleratorText';  
  XmNbuttonAccelerators = 'buttonAccelerators';  
  XmNbuttonCount = 'buttonCount';  
  XmNbuttonFontList = 'buttonFontList';  
  XmNbuttonMnemonicCharSets = 'buttonMnemonicCharSets';  
  XmNbuttonMnemonics = 'buttonMnemonics';  
  XmNbuttonSet = 'buttonSet';  
  XmNbuttonType = 'buttonType';  
  XmNbuttons = 'buttons';  
  XmNcancelButton = 'cancelButton';  
  XmNcancelCallback = 'cancelCallback';  
  XmNcancelLabelString = 'cancelLabelString';  
  XmNcascadePixmap = 'cascadePixmap';  
  XmNcascadingCallback = 'cascadingCallback';  
  XmNchildHorizontalAlignment = 'childHorizontalAlignment';  
  XmNchildHorizontalSpacing = 'childHorizontalSpacing';  
  XmNchildPlacement = 'childPlacement';  
  XmNchildPosition = 'childPosition';  
  XmNchildType = 'childType';  
  XmNchildVerticalAlignment = 'childVerticalAlignment';  
  XmNclientData = 'clientData';  
  XmNclipWindow = 'clipWindow';  
  XmNcolumns = 'columns';  
  XmNcommand = 'command';  
  XmNcommandChangedCallback = 'commandChangedCallback';  
  XmNcommandEnteredCallback = 'commandEnteredCallback';  
  XmNcommandWindow = 'commandWindow';  
  XmNcommandWindowLocation = 'commandWindowLocation';  
  XmNconvertProc = 'convertProc';  
  XmNcursorBackground = 'cursorBackground';  
  XmNcursorForeground = 'cursorForeground';  
  XmNcursorPosition = 'cursorPosition';  
  XmNcursorPositionVisible = 'cursorPositionVisible';  
  XmNdarkThreshold = 'darkThreshold';  
  XmNdecimalPoints = 'decimalPoints';  
  XmNdecrementCallback = 'decrementCallback';  
  XmNdefaultActionCallback = 'defaultActionCallback';  
  XmNdefaultButton = 'defaultButton';  
  XmNdefaultButtonShadowThickness = 'defaultButtonShadowThickness';  
  XmNdefaultButtonType = 'defaultButtonType';  
  XmNdefaultCopyCursorIcon = 'defaultCopyCursorIcon';  
  XmNdefaultFontList = 'defaultFontList';  
  XmNdefaultInvalidCursorIcon = 'defaultInvalidCursorIcon';  
  XmNdefaultLinkCursorIcon = 'defaultLinkCursorIcon';  
  XmNdefaultMoveCursorIcon = 'defaultMoveCursorIcon';  
  XmNdefaultNoneCursorIcon = 'defaultNoneCursorIcon';  
  XmNdefaultPosition = 'defaultPosition';  
  XmNdefaultSourceCursorIcon = 'defaultSourceCursorIcon';  
  XmNdefaultValidCursorIcon = 'defaultValidCursorIcon';  
  XmNdeleteResponse = 'deleteResponse';  
  XmNdesktopParent = 'desktopParent';  
  XmNdialogStyle = 'dialogStyle';  
  XmNdialogTitle = 'dialogTitle';  
  XmNdialogType = 'dialogType';  
  XmNdirListItemCount = 'dirListItemCount';  
  XmNdirListItems = 'dirListItems';  
  XmNdirListLabelString = 'dirListLabelString';  
  XmNdirMask = 'dirMask';  
  XmNdirSearchProc = 'dirSearchProc';  
  XmNdirSpec = 'dirSpec';  
  XmNdirectory = 'directory';  
  XmNdirectoryValid = 'directoryValid';  
  XmNdisarmCallback = 'disarmCallback';  
  XmNdoubleClickInterval = 'doubleClickInterval';  
  XmNdragCallback = 'dragCallback';  
  XmNdragContextClass = 'dragContextClass';  
  XmNdragDropFinishCallback = 'dragDropFinishCallback';  
  XmNdragIconClass = 'dragIconClass';  
  XmNdragInitiatorProtocolStyle = 'dragInitiatorProtocolStyle';  
  XmNdragMotionCallback = 'dragMotionCallback';  
  XmNdragOperations = 'dragOperations';  
  XmNdragOverMode = 'dragOverMode';  
  XmNdragProc = 'dragProc';  
  XmNdragReceiverProtocolStyle = 'dragReceiverProtocolStyle';  
  XmNdropFinishCallback = 'dropFinishCallback';  
  XmNdropProc = 'dropProc';  
  XmNdropRectangles = 'dropRectangles';  
  XmNdropSiteActivity = 'dropSiteActivity';  
  XmNdropSiteEnterCallback = 'dropSiteEnterCallback';  
  XmNdropSiteLeaveCallback = 'dropSiteLeaveCallback';  
  XmNdropSiteManagerClass = 'dropSiteManagerClass';  
  XmNdropSiteOperations = 'dropSiteOperations';  
  XmNdropSiteType = 'dropSiteType';  
  XmNdropStartCallback = 'dropStartCallback';  
  XmNdropTransferClass = 'dropTransferClass';  
  XmNdropTransfers = 'dropTransfers';  
  XmNeditMode = 'editMode';  
  XmNeditable = 'editable';  
  XmNentryAlignment = 'entryAlignment';  
  XmNentryBorder = 'entryBorder';  
  XmNentryCallback = 'entryCallback';  
  XmNentryClass = 'entryClass';  
  XmNentryVerticalAlignment = 'entryVerticalAlignment';  
  XmNexportTargets = 'exportTargets';  
  XmNexposeCallback = 'exposeCallback';  
  XmNextendedSelectionCallback = 'extendedSelectionCallback';  
  XmNextensionType = 'extensionType';  
  XmNfileListItemCount = 'fileListItemCount';  
  XmNfileListItems = 'fileListItems';  
  XmNfileListLabelString = 'fileListLabelString';  
  XmNfileSearchProc = 'fileSearchProc';  
  XmNfileTypeMask = 'fileTypeMask';  
  XmNfillOnArm = 'fillOnArm';  
  XmNfillOnSelect = 'fillOnSelect';  
  XmNfilterLabelString = 'filterLabelString';  
  XmNfocusCallback = 'focusCallback';  
  XmNfocusMovedCallback = 'focusMovedCallback';  
  XmNfocusPolicyChanged = 'focusPolicyChanged';  
  XmNfontList = 'fontList';  
  XmNforegroundThreshold = 'foregroundThreshold';  
  XmNfractionBase = 'fractionBase';  
  XmNgainPrimaryCallback = 'gainPrimaryCallback';  
  XmNhelpCallback = 'helpCallback';  
  XmNhelpLabelString = 'helpLabelString';  
  XmNhighlightColor = 'highlightColor';  
  XmNhighlightOnEnter = 'highlightOnEnter';  
  XmNhighlightPixmap = 'highlightPixmap';  
  XmNhighlightThickness = 'highlightThickness';  
  XmNhistoryItemCount = 'historyItemCount';  
  XmNhistoryItems = 'historyItems';  
  XmNhistoryMaxItems = 'historyMaxItems';  
  XmNhistoryVisibleItemCount = 'historyVisibleItemCount';  
  XmNhorizontalFontUnit = 'horizontalFontUnit';  
  XmNhorizontalScrollBar = 'horizontalScrollBar';  
  XmNhorizontalSpacing = 'horizontalSpacing';  
  XmNhotX = 'hotX';  
  XmNhotY = 'hotY';  
  XmNiccHandle = 'iccHandle';  
  XmNimportTargets = 'importTargets';  
  XmNincrement = 'increment';  
  XmNincrementCallback = 'incrementCallback';  
  XmNincremental = 'incremental';  
  XmNindicatorOn = 'indicatorOn';  
  XmNindicatorSize = 'indicatorSize';  
  XmNindicatorType = 'indicatorType';  
  XmNinitialDelay = 'initialDelay';  
  XmNinitialFocus = 'initialFocus';  
  XmNinputCallback = 'inputCallback';  
  XmNinputCreate = 'inputCreate';  
  XmNinputMethod = 'inputMethod';  
  XmNinvalidCursorForeground = 'invalidCursorForeground';  
  XmNisAligned = 'isAligned';  
  XmNisHomogeneous = 'isHomogeneous';  
  XmNitemCount = 'itemCount';  
  XmNitems = 'items';  
  XmNkeyboardFocusPolicy = 'keyboardFocusPolicy';  
  XmNlabelFontList = 'labelFontList';  
  XmNlabelInsensitivePixmap = 'labelInsensitivePixmap';  
  XmNlabelPixmap = 'labelPixmap';  
  XmNlabelString = 'labelString';  
  XmNlabelType = 'labelType';  
  XmNleftAttachment = 'leftAttachment';  
  XmNleftOffset = 'leftOffset';  
  XmNleftPosition = 'leftPosition';  
  XmNleftWidget = 'leftWidget';  
  XmNlightThreshold = 'lightThreshold';  
  XmNlineSpace = 'lineSpace';  
  XmNlistItemCount = 'listItemCount';  
  XmNlistItems = 'listItems';  
  XmNlistLabelString = 'listLabelString';  
  XmNlistMarginHeight = 'listMarginHeight';  
  XmNlistMarginWidth = 'listMarginWidth';  
  XmNlistSizePolicy = 'listSizePolicy';  
  XmNlistSpacing = 'listSpacing';  
  XmNlistUpdated = 'listUpdated';  
  XmNlistVisibleItemCount = 'listVisibleItemCount';  
  XmNlogicalParent = 'logicalParent';  
  XmNlosePrimaryCallback = 'losePrimaryCallback';  
  XmNlosingFocusCallback = 'losingFocusCallback';  
  XmNmainWindowMarginHeight = 'mainWindowMarginHeight';  
  XmNmainWindowMarginWidth = 'mainWindowMarginWidth';  
  XmNmapCallback = 'mapCallback';  
  XmNmappingDelay = 'mappingDelay';  
  XmNmargin = 'margin';  
  XmNmarginBottom = 'marginBottom';  
  XmNmarginHeight = 'marginHeight';  
  XmNmarginLeft = 'marginLeft';  
  XmNmarginRight = 'marginRight';  
  XmNmarginTop = 'marginTop';  
  XmNmarginWidth = 'marginWidth';  
  XmNmask = 'mask';  
  XmNmaxLength = 'maxLength';  
  XmNmaximum = 'maximum';  
  XmNmenuAccelerator = 'menuAccelerator';  
  XmNmenuBar = 'menuBar';  
  XmNmenuCursor = 'menuCursor';  
  XmNmenuHelpWidget = 'menuHelpWidget';  
  XmNmenuHistory = 'menuHistory';  
  XmNmenuPost = 'menuPost';  
  XmNmessageAlignment = 'messageAlignment';  
  XmNmessageProc = 'messageProc';  
  XmNmessageString = 'messageString';  
  XmNmessageWindow = 'messageWindow';  
  XmNminimizeButtons = 'minimizeButtons';  
  XmNminimum = 'minimum';  
  XmNmnemonic = 'mnemonic';  
  XmNmnemonicCharSet = 'mnemonicCharSet';  
  XmNmodifyVerifyCallback = 'modifyVerifyCallback';  
  XmNmodifyVerifyCallbackWcs = 'modifyVerifyCallbackWcs';  
  XmNmotionVerifyCallback = 'motionVerifyCallback';  
  XmNmoveOpaque = 'moveOpaque';  
  XmNmultiClick = 'multiClick';  
  XmNmultipleSelectionCallback = 'multipleSelectionCallback';  
  XmNmustMatch = 'mustMatch';  
  XmNmwmDecorations = 'mwmDecorations';  
  XmNmwmFunctions = 'mwmFunctions';  
  XmNmwmInputMode = 'mwmInputMode';  
  XmNmwmMenu = 'mwmMenu';  
  XmNmwmMessages = 'mwmMessages';  
  XmNnavigationType = 'navigationType';  
  XmNneedsMotion = 'needsMotion';  
  XmNnoMatchCallback = 'noMatchCallback';  
  XmNnoMatchString = 'noMatchString';  
  XmNnoResize = 'noResize';  
  XmNnoneCursorForeground = 'noneCursorForeground';  
  XmNnotifyProc = 'notifyProc';  
  XmNnumColumns = 'numColumns';  
  XmNnumDropRectangles = 'numDropRectangles';  
  XmNnumDropTransfers = 'numDropTransfers';  
  XmNnumExportTargets = 'numExportTargets';  
  XmNnumImportTargets = 'numImportTargets';  
  XmNnumRectangles = 'numRectangles';  
  XmNoffsetX = 'offsetX';  
  XmNoffsetY = 'offsetY';  
  XmNokCallback = 'okCallback';  
  XmNokLabelString = 'okLabelString';  
  XmNoperationChangedCallback = 'operationChangedCallback';  
  XmNoperationCursorIcon = 'operationCursorIcon';  
  XmNoptionLabel = 'optionLabel';  
  XmNoptionMnemonic = 'optionMnemonic';  
  XmNoutputCreate = 'outputCreate';  
  XmNpacking = 'packing';  
  XmNpageDecrementCallback = 'pageDecrementCallback';  
  XmNpageIncrement = 'pageIncrement';  
  XmNpageIncrementCallback = 'pageIncrementCallback';  
  XmNpaneMaximum = 'paneMaximum';  
  XmNpaneMinimum = 'paneMinimum';  
  XmNpattern = 'pattern';  
  XmNpendingDelete = 'pendingDelete';  
  XmNpopupEnabled = 'popupEnabled';  
  XmNpositionIndex = 'positionIndex';  
  XmNpostFromButton = 'postFromButton';  
  XmNpostFromCount = 'postFromCount';  
  XmNpostFromList = 'postFromList';  
  XmNpreeditType = 'preeditType';  
  XmNprocessingDirection = 'processingDirection';  
  XmNpromptString = 'promptString';  
  XmNprotocolCallback = 'protocolCallback';  
  XmNpushButtonEnabled = 'pushButtonEnabled';  
  XmNqualifySearchDataProc = 'qualifySearchDataProc';  
  XmNradioAlwaysOne = 'radioAlwaysOne';  
  XmNradioBehavior = 'radioBehavior';  
  XmNrealizeCallback = 'realizeCallback';  
  XmNrecomputeSize = 'recomputeSize';  
  XmNrectangles = 'rectangles';  
  XmNrefigureMode = 'refigureMode';  
  XmNrepeatDelay = 'repeatDelay';  
  XmNresizable = 'resizable';  
  XmNresizeCallback = 'resizeCallback';  
  XmNresizeHeight = 'resizeHeight';  
  XmNresizePolicy = 'resizePolicy';  
  XmNresizeWidth = 'resizeWidth';  
  XmNrightAttachment = 'rightAttachment';  
  XmNrightOffset = 'rightOffset';  
  XmNrightPosition = 'rightPosition';  
  XmNrightWidget = 'rightWidget';  
  XmNrowColumnType = 'rowColumnType';  
  XmNrows = 'rows';  
  XmNrubberPositioning = 'rubberPositioning';  
  XmNsashHeight = 'sashHeight';  
  XmNsashIndent = 'sashIndent';  
  XmNsashShadowThickness = 'sashShadowThickness';  
  XmNsashWidth = 'sashWidth';  
  XmNscaleHeight = 'scaleHeight';  
  XmNscaleMultiple = 'scaleMultiple';  
  XmNscaleWidth = 'scaleWidth';  
  XmNscrollBarDisplayPolicy = 'scrollBarDisplayPolicy';  
  XmNscrollBarPlacement = 'scrollBarPlacement';  
  XmNscrollHorizontal = 'scrollHorizontal';  
  XmNscrollLeftSide = 'scrollLeftSide';  
  XmNscrollTopSide = 'scrollTopSide';  
  XmNscrollVertical = 'scrollVertical';  
  XmNscrolledWindowMarginHeight = 'scrolledWindowMarginHeight';  
  XmNscrolledWindowMarginWidth = 'scrolledWindowMarginWidth';  
  XmNscrollingPolicy = 'scrollingPolicy';  
  XmNselectColor = 'selectColor';  
  XmNselectInsensitivePixmap = 'selectInsensitivePixmap';  
  XmNselectPixmap = 'selectPixmap';  
  XmNselectThreshold = 'selectThreshold';  
  XmNselectedItemCount = 'selectedItemCount';  
  XmNselectedItems = 'selectedItems';  
  XmNselectionArrayCount = 'selectionArrayCount';  
  XmNselectionLabelString = 'selectionLabelString';  
  XmNselectionPolicy = 'selectionPolicy';  
  XmNseparatorOn = 'separatorOn';  
  XmNseparatorType = 'separatorType';  
  XmNset = 'set';  
  XmNshadow = 'shadow';  
  XmNshadowThickness = 'shadowThickness';  
  XmNshadowType = 'shadowType';  
  XmNshellUnitType = 'shellUnitType';  
  XmNshowArrows = 'showArrows';  
  XmNshowAsDefault = 'showAsDefault';  
  XmNshowSeparator = 'showSeparator';  
  XmNshowValue = 'showValue';  
  XmNsimpleCallback = 'simpleCallback';  
  XmNsingleSelectionCallback = 'singleSelectionCallback';  
  XmNsizePolicy = 'sizePolicy';  
  XmNskipAdjust = 'skipAdjust';  
  XmNsliderSize = 'sliderSize';  
  XmNsource = 'source';  
  XmNsourceCursorIcon = 'sourceCursorIcon';  
  XmNsourceIsExternal = 'sourceIsExternal';  
  XmNsourcePixmapIcon = 'sourcePixmapIcon';  
  XmNsourceWidget = 'sourceWidget';  
  XmNsourceWindow = 'sourceWindow';  
  XmNspacing = 'spacing';  
  XmNspotLocation = 'spotLocation';  
  XmNstartTime = 'startTime';  
  XmNstateCursorIcon = 'stateCursorIcon';  
  XmNstringDirection = 'stringDirection';  
  XmNsubMenuId = 'subMenuId';  
  XmNsymbolPixmap = 'symbolPixmap';  
  XmNtearOffMenuActivateCallback = 'tearOffMenuActivateCallback';  
  XmNtearOffMenuDeactivateCallback = 'tearOffMenuDeactivateCallback';  
  XmNtearOffModel = 'tearOffModel';  
  XmNtextAccelerators = 'textAccelerators';  
  XmNtextColumns = 'textColumns';  
  XmNtextFontList = 'textFontList';  
  XmNtextString = 'textString';  
  XmNtextTranslations = 'textTranslations';  
  XmNtextValue = 'textValue';  
  XmNtitleString = 'titleString';  
  XmNtoBottomCallback = 'toBottomCallback';  
  XmNtoPositionCallback = 'toPositionCallback';  
  XmNtoTopCallback = 'toTopCallback';  
  XmNtopAttachment = 'topAttachment';  
  XmNtopCharacter = 'topCharacter';  
  XmNtopItemPosition = 'topItemPosition';  
  XmNtopLevelEnterCallback = 'topLevelEnterCallback';  
  XmNtopLevelLeaveCallback = 'topLevelLeaveCallback';  
  XmNtopOffset = 'topOffset';  
  XmNtopPosition = 'topPosition';  
  XmNtopShadowColor = 'topShadowColor';  
  XmNtopShadowPixmap = 'topShadowPixmap';  
  XmNtopWidget = 'topWidget';  
  XmNtransferProc = 'transferProc';  
  XmNtransferStatus = 'transferStatus';  
  XmNtraversalCallback = 'traversalCallback';  
  XmNtraversalOn = 'traversalOn';  
  XmNtraversalType = 'traversalType';  
  XmNtraverseObscuredCallback = 'traverseObscuredCallback';  
  XmNtreeUpdateProc = 'treeUpdateProc';  
  XmNtroughColor = 'troughColor';  
  XmNunitType = 'unitType';  
  XmNunmapCallback = 'unmapCallback';  
  XmNunpostBehavior = 'unpostBehavior';  
  XmNunselectPixmap = 'unselectPixmap';  
  XmNupdateSliderSize = 'updateSliderSize';  
  XmNuseAsyncGeometry = 'useAsyncGeometry';  
  XmNuserData = 'userData';  
  XmNvalidCursorForeground = 'validCursorForeground';  
  XmNvalueChangedCallback = 'valueChangedCallback';  
  XmNvalueWcs = 'valueWcs';  
  XmNverifyBell = 'verifyBell';  
  XmNverticalFontUnit = 'verticalFontUnit';  
  XmNverticalScrollBar = 'verticalScrollBar';  
  XmNverticalSpacing = 'verticalSpacing';  
  XmNvisibleItemCount = 'visibleItemCount';  
  XmNvisibleWhenOff = 'visibleWhenOff';  
  XmNvisualPolicy = 'visualPolicy';  
  XmNwhichButton = 'whichButton';  
  XmNwordWrap = 'wordWrap';  
  XmNworkWindow = 'workWindow';  
  XmRAlignment = 'Alignment';  
  XmRAnimationMask = 'AnimationMask';  
  XmRAnimationPixmap = 'AnimationPixmap';  
  XmRAnimationStyle = 'AnimationStyle';  
  XmRArrowDirection = 'ArrowDirection';  
  XmRAtomList = 'AtomList';  
  XmRAttachment = 'Attachment';  
  XmRAudibleWarning = 'AudibleWarning';  
  XmRAvailability = 'Availability';  
  XmRBackgroundPixmap = 'BackgroundPixmap';  
  XmRBlendModel = 'BlendModel';  
  XmRBooleanDimension = 'BooleanDimension';  
  XmRBottomShadowPixmap = 'BottomShadowPixmap';  
  XmRButtonType = 'ButtonType';  
  XmRCallbackProc = 'CallbackProc';  
  XmRChar = 'Char';  
  XmRCharSetTable = 'CharSetTable';  
  XmRChildHorizontalAlignment = 'ChildHorizontalAlignment';  
  XmRChildPlacement = 'ChildPlacement';  
  XmRChildType = 'ChildType';  
  XmRChildVerticalAlignment = 'ChildVerticalAlignment';  
  XmRCommandWindowLocation = 'CommandWindowLocation';  
  XmRCompoundText = 'CompoundText';  
  XmRDefaultButtonType = 'DefaultButtonType';  
  XmRDeleteResponse = 'DeleteResponse';  
  XmRDialogStyle = 'DialogStyle';  
  XmRDialogType = 'DialogType';  
  XmRDoubleClickInterval = 'DoubleClickInterval';  
  XmRDragInitiatorProtocolStyle = 'DragInitiatorProtocolStyle';  
  XmRDragReceiverProtocolStyle = 'DragReceiverProtocolStyle';  
  XmRDropSiteActivity = 'DropSiteActivity';  
  XmRDropSiteOperations = 'DropSiteOperations';  
  XmRDropSiteType = 'DropSiteType';  
  XmRDropTransfers = 'DropTransfers';  
  XmRExtensionType = 'ExtensionType';  
  XmRFileTypeMask = 'FileTypeMask';  
  XmRFontList = 'FontList';  
  XmRGadgetPixmap = 'GadgetPixmap';  
  XmRHighlightPixmap = 'HighlightPixmap';  
  XmRHorizontalDimension = 'HorizontalDimension';  
  XmRHorizontalInt = 'HorizontalInt';  
  XmRHorizontalPosition = 'HorizontalPosition';  
  XmRIconAttachment = 'IconAttachment';  
  XmRImportTargets = 'ImportTargets';  
  XmRIndicatorType = 'IndicatorType';  
  XmRItemCount = 'ItemCount';  
  XmRItems = 'Items';  
  XmRKeySym = 'KeySym';  
  XmRKeySymTable = 'KeySymTable';  
  XmRKeyboardFocusPolicy = 'KeyboardFocusPolicy';  
  XmRLabelType = 'LabelType';  
  XmRListMarginHeight = 'ListMarginHeight';  
  XmRListMarginWidth = 'ListMarginWidth';  
  XmRListSizePolicy = 'ListSizePolicy';  
  XmRListSpacing = 'ListSpacing';  
  XmRManBottomShadowPixmap = 'ManBottomShadowPixmap';  
  XmRManForegroundPixmap = 'ManForegroundPixmap';  
  XmRManHighlightPixmap = 'ManHighlightPixmap';  
  XmRManTopShadowPixmap = 'ManTopShadowPixmap';  
  XmRMenuWidget = 'MenuWidget';  
  XmRMnemonic = 'Mnemonic';  
  XmRMultiClick = 'MultiClick';  
  XmRNavigationType = 'NavigationType';  
  XmRPacking = 'Packing';  
  XmRPrimForegroundPixmap = 'PrimForegroundPixmap';  
  XmRProc = 'Proc';  
  XmRProcessingDirection = 'ProcessingDirection';  
  XmRRectangleList = 'RectangleList';  
  XmRResizePolicy = 'ResizePolicy';  
  XmRRowColumnType = 'RowColumnType';  
  XmRScrollBarDisplayPolicy = 'ScrollBarDisplayPolicy';  
  XmRScrollBarPlacement = 'ScrollBarPlacement';  
  XmRScrollingPolicy = 'ScrollingPolicy';  
  XmRSelectedItemCount = 'SelectedItemCount';  
  XmRSelectedItems = 'SelectedItems';  
  XmRSelectionPolicy = 'SelectionPolicy';  
  XmRSelectionType = 'SelectionType';  
  XmRSeparatorType = 'SeparatorType';  
  XmRShadowType = 'ShadowType';  
  XmRShellHorizDim = 'ShellHorizDim';  
  XmRShellHorizPos = 'ShellHorizPos';  
  XmRShellUnitType = 'ShellUnitType';  
  XmRShellVertDim = 'ShellVertDim';  
  XmRShellVertPos = 'ShellVertPos';  
  XmRSizePolicy = 'SizePolicy';  
  XmRStringDirection = 'StringDirection';  
  XmRTearOffModel = 'TearOffModel';  
  XmRTopShadowPixmap = 'TopShadowPixmap';  
  XmRTransferStatus = 'TransferStatus';  
  XmRTraversalType = 'TraversalType';  
  XmRUnitType = 'UnitType';  
  XmRUnpostBehavior = 'UnpostBehavior';  
  XmRValueWcs = 'ValueWcs';  
  XmRVerticalAlignment = 'VerticalAlignment';  
  XmRVerticalDimension = 'VerticalDimension';  
  XmRVerticalInt = 'VerticalInt';  
  XmRVerticalPosition = 'VerticalPosition';  
  XmRVirtualBinding = 'VirtualBinding';  
  XmRVisibleItemCount = 'VisibleItemCount';  
  XmRVisualPolicy = 'VisualPolicy';  
  XmRWhichButton = 'WhichButton';  
  XmRXmBackgroundPixmap = 'XmBackgroundPixmap';  
  XmRXmString = 'XmString';  
  XmRXmStringCharSet = 'XmStringCharSet';  
  XmRXmStringTable = 'XmStringTable';  
  XmVosfActivate = 'osfActivate';  
  XmVosfAddMode = 'osfAddMode';  
  XmVosfBackSpace = 'osfBackSpace';  
  XmVosfBeginLine = 'osfBeginLine';  
  XmVosfCancel = 'osfCancel';  
  XmVosfClear = 'osfClear';  
  XmVosfCopy = 'osfCopy';  
  XmVosfCut = 'osfCut';  
  XmVosfDelete = 'osfDelete';  
  XmVosfDown = 'osfDown';  
  XmVosfEndLine = 'osfEndLine';  
  XmVosfHelp = 'osfHelp';  
  XmVosfInsert = 'osfInsert';  
  XmVosfLeft = 'osfLeft';  
  XmVosfMenu = 'osfMenu';  
  XmVosfMenuBar = 'osfMenuBar';  
  XmVosfPageDown = 'osfPageDown';  
  XmVosfPageLeft = 'osfPageLeft';  
  XmVosfPageRight = 'osfPageRight';  
  XmVosfPageUp = 'osfPageUp';  
  XmVosfPaste = 'osfPaste';  
  XmVosfPrimaryPaste = 'osfPrimaryPaste';  
  XmVosfQuickPaste = 'osfQuickPaste';  
  XmVosfRight = 'osfRight';  
  XmVosfSelect = 'osfSelect';  
  XmVosfUndo = 'osfUndo';  
  XmVosfUp = 'osfUp';  
  XmSFONTLIST_DEFAULT_TAG_STRING = 'FONTLIST_DEFAULT_TAG_STRING';  
  XmSXmFONTLIST_DEFAULT_TAG_STRING = 'XmFONTLIST_DEFAULT_TAG_STRING';  
  XmRTopItemPosition = 'TopItemPosition';  
  XmNtearOffTitle = 'tearOffTitle';  
  XmCTearOffTitle = 'TearOffTitle';  
  XmNpopupHandlerCallback = 'popupHandlerCallback';  
  XmNconvertCallback = 'convertCallback';  
  XmNdestinationCallback = 'destinationCallback';  
  XmNselectedItem = 'selectedItem';  
  XmCSelectedItem = 'SelectedItem';  
  XmNselectionCallback = 'selectionCallback';  
  XmNmatchBehavior = 'matchBehavior';  
  XmCMatchBehavior = 'MatchBehavior';  
  XmNnoFontCallback = 'noFontCallback';  
  XmNtextPath = 'textPath';  
  XmNeditingPath = 'editingPath';  
  XmCEditingPath = 'EditingPath';  
  XmNbidirectionalCursor = 'bidirectionalCursor';  
  XmCBidirectionalCursor = 'BidirectionalCursor';  
  XmNcollapsedStatePixmap = 'collapsedStatePixmap';  
  XmNdetailColumnHeading = 'detailColumnHeading';  
  XmNdetailCount = 'detailCount';  
  XmNdetailTabList = 'detailTabList';  
  XmNexpandedStatePixmap = 'expandedStatePixmap';  
  XmNlargeCellHeight = 'largeCellHeight';  
  XmNlargeCellWidth = 'largeCellWidth';  
  XmNlayoutType = 'layoutType';  
  XmNoutlineIndentation = 'outlineIndentation';  
  XmNoutlineLineStyle = 'outlineLineStyle';  
  XmNprimaryOwnership = 'primaryOwnership';  
  XmNselectionTechnique = 'selectionTechnique';  
  XmNsmallCellHeight = 'smallCellHeight';  
  XmNsmallCellWidth = 'smallCellWidth';  
  XmNspatialStyle = 'spatialStyle';  
  XmNentryParent = 'entryParent';  
  XmNlargeIconX = 'largeIconX';  
  XmNlargeIconY = 'largeIconY';  
  XmNsmallIconX = 'smallIconX';  
  XmNsmallIconY = 'smallIconY';  
  XmCCollapsedStatePixmap = 'CollapsedStatePixmap';  
  XmCDetailColumnHeading = 'DetailColumnHeading';  
  XmCDetailCount = 'DetailCount';  
  XmCDetailMask = 'DetailMask';  
  XmCEntryViewType = 'EntryViewType';  
  XmCLineStyle = 'LineStyle';  
  XmCDetailTabList = 'DetailTabList';  
  XmCExpandedStatePixmap = 'ExpandedStatePixmap';  
  XmCIncludeModel = 'IncludeModel';  
  XmCCellHeight = 'CellHeight';  
  XmCCellWidth = 'CellWidth';  
  XmCLayoutType = 'LayoutType';  
  XmCOutlineIndentation = 'OutlineIndentation';  
  XmCPlaceModel = 'PlaceModel';  
  XmCPrimaryOwnership = 'PrimaryOwnership';  
  XmCSelectionTechnique = 'SelectionTechnique';  
  XmCSpatialStyle = 'SpatialStyle';  
  XmCEntryDetail = 'EntryDetail';  
  XmCExpandState = 'ExpandState';  
  XmNlargeIcon = 'largeIcon';  
  XmNlargeIconMask = 'largeIconMask';  
  XmNlargeIconPixmap = 'largeIconPixmap';  
  XmNsmallIcon = 'smallIcon';  
  XmNsmallIconMask = 'smallIconMask';  
  XmNsmallIconPixmap = 'smallIconPixmap';  
  XmCIcon = 'Icon';  
  XmCViewType = 'ViewType';  
  XmCVisualEmphasis = 'VisualEmphasis';  
  XmNcurrentPageNumber = 'currentPageNumber';  
  XmNfirstPageNumber = 'firstPageNumber';  
  XmNlastPageNumber = 'lastPageNumber';  
  XmNbackPagePlacement = 'backPagePlacement';  
  XmNbackPageNumber = 'backPageNumber';  
  XmNbackPageSize = 'backPageSize';  
  XmNbackPageForeground = 'backPageForeground';  
  XmNbackPageBackground = 'backPageBackground';  
  XmNframeBackground = 'frameBackground';  
  XmNbindingType = 'bindingType';  
  XmNbindingPixmap = 'bindingPixmap';  
  XmNbindingWidth = 'bindingWidth';  
  XmNmajorTabSpacing = 'majorTabSpacing';  
  XmNminorTabSpacing = 'minorTabSpacing';  
  XmNinnerMarginWidth = 'innerMarginWidth';  
  XmNinnerMarginHeight = 'innerMarginHeight';  
  XmNframeShadowThickness = 'frameShadowThickness';  
  XmNpageNumber = 'pageNumber';  
  XmCCurrentPageNumber = 'CurrentPageNumber';  
  XmCFirstPageNumber = 'FirstPageNumber';  
  XmCLastPageNumber = 'LastPageNumber';  
  XmCBackPagePlacement = 'BackPagePlacement';  
  XmCBackPageNumber = 'BackPageNumber';  
  XmCBackPageSize = 'BackPageSize';  
  XmCBackPageForeground = 'BackPageForeground';  
  XmCBackPageBackground = 'BackPageBackground';  
  XmCFrameBackground = 'FrameBackground';  
  XmCBindingType = 'BindingType';  
  XmCBindingPixmap = 'BindingPixmap';  
  XmCBindingWidth = 'BindingWidth';  
  XmCMajorTabSpacing = 'MajorTabSpacing';  
  XmCMinorTabSpacing = 'MinorTabSpacing';  
  XmCInnerMarginWidth = 'InnerMarginWidth';  
  XmCInnerMarginHeight = 'InnerMarginHeight';  
  XmCPageChangeCallback = 'PageChangeCallback';  
  XmCPageNumber = 'PageNumber';  
  XmRArrowLayout = 'ArrowLayout';  
  XmRArrowSensitivity = 'ArrowSensitivity';  
  XmRSpinBoxChildType = 'SpinBoxChildType';  
  XmNarrowLayout = 'arrowLayout';  
  XmCArrowLayout = 'ArrowLayout';  
  XmNarrowSensitivity = 'arrowSensitivity';  
  XmCArrowSensitivity = 'ArrowSensitivity';  
  XmNdefaultArrowSensitivity = 'defaultArrowSensitivity';  
  XmCDefaultArrowSensitivity = 'DefaultArrowSensitivity';  
  XmNarrowSize = 'arrowSize';  
  XmCArrowSize = 'ArrowSize';  
  XmNspinBoxChildType = 'spinBoxChildType';  
  XmCSpinBoxChildType = 'SpinBoxChildType';  
  XmNposition = 'position';  
  XmNnumValues = 'numValues';  
  XmCNumValues = 'NumValues';  
  XmNvalues = 'values';  
  XmCValues = 'Values';  
  XmNminimumValue = 'minimumValue';  
  XmCMinimumValue = 'MinimumValue';  
  XmNmaximumValue = 'maximumValue';  
  XmCMaximumValue = 'MaximumValue';  
  XmNincrementValue = 'incrementValue';  
  XmCIncrementValue = 'IncrementValue';  
  XmRAutomaticSelection = 'AutomaticSelection';  
  XmRLineStyle = 'LineStyle';  
  XmREntryViewType = 'EntryViewType';  
  XmRDirection = 'Direction';  
  XmRLayoutType = 'LayoutType';  
  XmRPrimaryOwnership = 'PrimaryOwnership';  
  XmRSelectionTechnique = 'SelectionTechnique';  
  XmRSpatialStyle = 'SpatialStyle';  
  XmRTabList = 'TabList';  
  XmRViewType = 'ViewType';  
  XmRVisualEmphasis = 'VisualEmphasis';  
  XmRBindingType = 'BindingType';  
  XmRNBChildType = 'NBChildType';  
  XmNentryViewType = 'entryViewType';  
  XmNinsensitiveStippleBitmap = 'insensitiveStippleBitmap';  
  XmNlayoutDirection = 'layoutDirection';  
  XmNviewType = 'viewType';  
  XmNvisualEmphasis = 'visualEmphasis';  
  XmCLayoutDirection = 'LayoutDirection';  
  XmNsnapBackMultiple = 'snapBackMultiple';  
  XmNslidingMode = 'slidingMode';  
  XmNsliderVisual = 'sliderVisual';  
  XmNautoDragModel = 'autoDragModel';  
  XmNcolorCalculationProc = 'colorCalculationProc';  
  XmNbitmapConversionModel = 'bitmapConversionModel';  
  XmNcolorAllocationProc = 'colorAllocationProc';  
  XmNselectionMode = 'selectionMode';  
  XmNselectedPositions = 'selectedPositions';  
  XmNselectedPositionCount = 'selectedPositionCount';  
  XmCSnapBackMultiple = 'SnapBackMultiple';  
  XmCSliderVisual = 'SliderVisual';  
  XmCSlidingMode = 'SlidingMode';  
  XmCAutoDragModel = 'AutoDragModel';  
  XmCColorCalculationProc = 'ColorCalculationProc';  
  XmCBitmapConversionModel = 'BitmapConversionModel';  
  XmCColorAllocationProc = 'ColorAllocationProc';  
  XmCInsensitiveStippleBitmap = 'InsensitiveStippleBitmap';  
  XmCSelectionMode = 'SelectionMode';  
  XmCSelectedPositions = 'SelectedPositions';  
  XmCSelectedPositionCount = 'SelectedPositionCount';  
  XmRSlidingMode = 'SlidingMode';  
  XmRShowArrows = 'ShowArrows';  
  XmRSliderVisual = 'SliderVisual';  
  XmRShowValue = 'ShowValue';  
  XmRAutoDragModel = 'AutoDragModel';  
  XmRSWChildType = 'SWChildType';  
  XmRBitmapConversionModel = 'BitmapConversionModel';  
  XmRSelectionMode = 'SelectionMode';  
  XmNinputPolicy = 'inputPolicy';  
  XmCInputPolicy = 'InputPolicy';  
  XmRInputPolicy = 'InputPolicy';  
  XmNtoggleMode = 'toggleMode';  
  XmCToggleMode = 'ToggleMode';  
  XmRToggleMode = 'ToggleMode';  
  XmRIndicatorOn = 'IndicatorOn';  
  XmRSet = 'Set';  
  XmNindeterminatePixmap = 'indeterminatePixmap';  
  XmCIndeterminatePixmap = 'IndeterminatePixmap';  
  XmNunselectColor = 'unselectColor';  
  XmCUnselectColor = 'UnselectColor';  
  XmNselectedPosition = 'selectedPosition';  
  XmNarrowSpacing = 'arrowSpacing';  
  XmCArrowSpacing = 'ArrowSpacing';  
  XmRMatchBehavior = 'MatchBehavior';  
  XmRComboBoxType = 'ComboBoxType';  
  XmCSelectedPosition = 'SelectedPosition';  
  XmNenableWarp = 'enableWarp';  
  XmCEnableWarp = 'EnableWarp';  
  XmREnableWarp = 'EnableWarp';  
  XmNmotifVersion = 'motifVersion';  
  XmCMotifVersion = 'MotifVersion';  
  XmNdefaultGlyphPixmap = 'defaultGlyphPixmap';  
  XmCDefaultGlyphPixmap = 'DefaultGlyphPixmap';  
  XmCRendition = 'Rendition';  
  XmNtag = 'tag';  
  XmCTag = 'Tag';  
  XmNfontName = 'fontName';  
  XmCFontName = 'FontName';  
  XmNfontType = 'fontType';  
  XmCFontType = 'FontType';  
  XmRFontType = 'FontType';  
  XmNloadModel = 'loadModel';  
  XmCLoadModel = 'LoadModel';  
  XmRLoadModel = 'LoadModel';  
  XmNtabList = 'tabList';  
  XmCTabList = 'TabList';  
  XmRRenditionPixel = 'RenditionPixel';  
  XmNunderlineType = 'underlineType';  
  XmCUnderlineType = 'UnderlineType';  
  XmNstrikethruType = 'strikethruType';  
  XmCStrikethruType = 'StrikethruType';  
  XmRLineType = 'LineType';  
  XmNrenderTable = 'renderTable';  
  XmCRenderTable = 'RenderTable';  
  XmRRenderTable = 'RenderTable';  
  XmNbuttonRenderTable = 'buttonRenderTable';  
  XmCButtonRenderTable = 'ButtonRenderTable';  
  XmRButtonRenderTable = 'ButtonRenderTable';  
  XmNlabelRenderTable = 'labelRenderTable';  
  XmCLabelRenderTable = 'LabelRenderTable';  
  XmRLabelRenderTable = 'LabelRenderTable';  
  XmNtextRenderTable = 'textRenderTable';  
  XmCTextRenderTable = 'TextRenderTable';  
  XmRTextRenderTable = 'TextRenderTable';  
  XmNdragStartCallback = 'dragStartCallback';  
  XmNnoRenditionCallback = 'noRenditionCallback';  
  XmSXmAS_IS = 'XmAS_IS';  
  XmMIsWhiteSpaceMethod = 'IsWhiteSpaceMethod';  
  XmMIsScanBreakMethod = 'IsScanBreakMethod';  
  XmMCharDirection = 'CharDirection';  
  XmMInitialCharsDirection = 'InitialCharsDirection';  
  XmNpatternType = 'patternType';  
  XmNsubstitute = 'substitute';  
  XmNinvokeParseProc = 'invokeParseProc';  
  XmNincludeStatus = 'includeStatus';  
  XmVosfBackTab = 'osfBackTab';  
  XmVosfBeginData = 'osfBeginData';  
  XmVosfDeselectAll = 'osfDeselectAll';  
  XmVosfEndData = 'osfEndData';  
  XmVosfEscape = 'osfEscape';  
  XmVosfExtend = 'osfExtend';  
  XmVosfLeftLine = 'osfLeftLine';  
  XmVosfNext = 'osfNext';  
  XmVosfNextField = 'osfNextField';  
  XmVosfNextMenu = 'osfNextMenu';  
  XmVosfNextMinor = 'osfNextMinor';  
  XmVosfPrevField = 'osfPrevField';  
  XmVosfPrevMenu = 'osfPrevMenu';  
  XmVosfPrior = 'osfPrior';  
  XmVosfPriorMinor = 'osfPriorMinor';  
  XmVosfReselect = 'osfReselect';  
  XmVosfRestore = 'osfRestore';  
  XmVosfRightLine = 'osfRightLine';  
  XmVosfSelectAll = 'osfSelectAll';  
  XmVosfSwitchDirection = 'osfSwitchDirection';  
  XmNnotebookChildType = 'notebookChildType';  
  XmCNotebookChildType = 'NotebookChildType';  
  XmRNotebookChildType = 'NotebookChildType';  
  XmNscrolledWindowChildType = 'scrolledWindowChildType';  
  XmCScrolledWindowChildType = 'ScrolledWindowChildType';  
  XmRScrolledWindowChildType = 'ScrolledWindowChildType';  
  XmNselectedObjects = 'selectedObjects';  
  XmCSelectedObjects = 'SelectedObjects';  
  XmNselectedObjectCount = 'selectedObjectCount';  
  XmCSelectedObjectCount = 'SelectedObjectCount';  
  XmNcomboBoxType = 'comboBoxType';  
  XmCComboBoxType = 'ComboBoxType';  
  XmNtabValue = 'tabValue';  
  XmNoffsetModel = 'offsetModel';  
  XmNdecimal = 'decimal';  
  XmNdetail = 'detail';  
  XmCDetail = 'Detail';  
//  XmNdetailCount = 'detailCount';  
//  XmCDetailCount = 'DetailCount';  
  XmNcontainerID = 'containerID';  
  XmCContainerID = 'ContainerID';  
  XmSCLIENT_WINDOW = 'CLIENT_WINDOW';  
  XmSCLIP_TEMPORARY = 'CLIP_TEMPORARY';  
  XmSCLIPBOARD = 'CLIPBOARD';  
  XmSCOMPOUND_TEXT = 'COMPOUND_TEXT';  
  XmSDELETE = 'DELETE';  
  XmSFILE = 'FILE';  
  XmSFILE_NAME = 'FILE_NAME';  
  XmSINCR = 'INCR';  
  XmSINSERT_PROPERTY = 'INSERT_PROPERTY';  
  XmSINSERT_SELECTION = 'INSERT_SELECTION';  
  XmSLENGTH = 'LENGTH';  
  XmSLINK_SELECTION = 'LINK_SELECTION';  
  XmS_MOTIF_ATOM_0 = '_MOTIF_ATOM_0';  
  XmS_MOTIF_BINDINGS = '_MOTIF_BINDINGS';  
  XmS_MOTIF_DEFAULT_BINDINGS = '_MOTIF_DEFAULT_BINDINGS';  
  XmS_MOTIF_CANCEL_DROP_EFFECT = '_MOTIF_CANCEL_DROP_EFFECT';  
  XmS_MOTIF_CLIP_HEADER = '_MOTIF_CLIP_HEADER';  
  XmS_MOTIF_CLIP_DATA_REQUEST = '_MOTIF_CLIP_DATA_REQUEST';  
  XmS_MOTIF_CLIP_DATA_DELETE = '_MOTIF_CLIP_DATA_DELETE';  
  XmS_MOTIF_CLIP_ITEM = '_MOTIF_CLIP_ITEM';  
  XmS_MOTIF_CLIP_LOCK = '_MOTIF_CLIP_LOCK';  
  XmS_MOTIF_CLIP_LOCK_ACCESS_VALID = '_MOTIF_CLIP_LOCK_ACCESS_VALID';  
  XmS_MOTIF_CLIP_MESSAGE = '_MOTIF_CLIP_MESSAGE';  
  XmS_MOTIF_CLIP_NEXT_ID = '_MOTIF_CLIP_NEXT_ID';  
  XmS_MOTIF_CLIP_TIME = '_MOTIF_CLIP_TIME';  
  XmS_MOTIF_CLIPBOARD_TARGETS = '_MOTIF_CLIPBOARD_TARGETS';  
  XmS_MOTIF_COMPOUND_STRING = '_MOTIF_COMPOUND_STRING';  
  XmS_MOTIF_DEFERRED_CLIPBOARD_TARGETS = '_MOTIF_DEFERRED_CLIPBOARD_TARGETS';  
  XmS_MOTIF_DESTINATION = '_MOTIF_DESTINATION';  
  XmS_MOTIF_DRAG_OFFSET = '_MOTIF_DRAG_OFFSET';  
  XmS_MOTIF_DROP = '_MOTIF_DROP';  
  XmS_MOTIF_ENCODING_REGISTRY = '_MOTIF_ENCODING_REGISTRY';  
  XmS_MOTIF_EXPORT_TARGETS = '_MOTIF_EXPORT_TARGETS';  
  XmS_MOTIF_LOSE_SELECTION = '_MOTIF_LOSE_SELECTION';  
  XmS_MOTIF_RENDER_TABLE = '_MOTIF_RENDER_TABLE';  
  XmS_MOTIF_WM_QUERY = '_MOTIF_WM_QUERY';  
  XmS_MOTIF_WM_ALL_CLIENTS = '_MOTIF_WM_ALL_CLIENTS';  
  XmSMULTIPLE = 'MULTIPLE';  
  XmSNULL = 'NULL';  
  XmSTARGETS = 'TARGETS';  
  XmSTEXT = 'TEXT';  
  XmSTIMESTAMP = 'TIMESTAMP';  
  XmSWM_STATE = 'WM_STATE';  
  XmSTRANSFER_SUCCESS = 'XmTRANSFER_SUCCESS';  
  XmSTRANSFER_FAILURE = 'XmTRANSFER_FAILURE';  
  XmNpathMode = 'pathMode';  
  XmRPathMode = 'PathMode';  
  XmCPathMode = 'PathMode';  
  XmNfileFilterStyle = 'fileFilterStyle';  
  XmRFileFilterStyle = 'FileFilterStyle';  
  XmCFileFilterStyle = 'FileFilterStyle';  
  XmNdirTextLabelString = 'dirTextLabelString';  
  XmCDirTextLabelString = 'DirTextLabelString';  
  XmNenableBtn1Transfer = 'enableBtn1Transfer';  
  XmCEnableBtn1Transfer = 'EnableBtn1Transfer';  
  XmNenableButtonTab = 'enableButtonTab';  
  XmCEnableButtonTab = 'EnableButtonTab';  
  XmNenableEtchedInMenu = 'enableEtchedInMenu';  
  XmCEnableEtchedInMenu = 'EnableEtchedInMenu';  
  XmNdefaultButtonEmphasis = 'defaultButtonEmphasis';  
  XmCDefaultButtonEmphasis = 'DefaultButtonEmphasis';  
  XmRDefaultButtonEmphasis = 'DefaultButtonEmphasis';  
  XmNenableToggleColor = 'enableToggleColor';  
  XmCEnableToggleColor = 'EnableToggleColor';  
  XmNenableToggleVisual = 'enableToggleVisual';  
  XmCEnableToggleVisual = 'EnableToggleVisual';  
  XmNenableDragIcon = 'enableDragIcon';  
  XmCEnableDragIcon = 'EnableDragIcon';  
  XmNenableUnselectableDrag = 'enableUnselectableDrag';  
  XmCEnableUnselectableDrag = 'EnableUnselectableDrag';  
  XmNdragOverActiveMode = 'dragOverActiveMode';  
  XmCDragOverActiveMode = 'DragOverActiveMode';  
  XmNinstallColormap = 'installColormap';  
  XmCInstallColormap = 'InstallColormap';  
  XmCOwnerEvents = 'OwnerEvents';  
  XmNownerEvents = 'ownerEvents';  
  XmCGrabStyle = 'GrabStyle';  
  XmNgrabStyle = 'grabStyle';  
  XmNforegroundState = 'foregroundState';  
  XmNbackgroundState = 'backgroundState';  
  XmCGroundState = 'GroundState';  
  XmRGroundState = 'GroundState';  
  XmRSelectColor = 'SelectColor';  
  XmRLargeIconPixmap = 'LargeIconPixmap';  
  XmRSmallIconPixmap = 'SmallIconPixmap';  
  XmNoutlineState = 'outlineState';  
  XmCOutlineState = 'OutlineState';  
  XmROutlineState = 'OutlineState';  
  XmNspatialIncludeModel = 'spatialIncludeModel';  
  XmCSpatialIncludeModel = 'SpatialIncludeModel';  
  XmRSpatialIncludeModel = 'SpatialIncludeModel';  
  XmNspatialResizeModel = 'spatialResizeModel';  
  XmCSpatialResizeModel = 'SpatialResizeModel';  
  XmRSpatialResizeModel = 'SpatialResizeModel';  
  XmNspatialSnapModel = 'spatialSnapModel';  
  XmCSpatialSnapModel = 'SpatialSnapModel';  
  XmRSpatialSnapModel = 'SpatialSnapModel';  
  XmNdetailColumnHeadingCount = 'detailColumnHeadingCount';  
  XmCDetailColumnHeadingCount = 'DetailColumnHeadingCount';  
  XmNdetailOrder = 'detailOrder';  
  XmCDetailOrder = 'DetailOrder';  
  XmRCardinalList = 'CardinalList';  
  XmNdetailOrderCount = 'detailOrderCount';  
  XmCDetailOrderCount = 'DetailOrderCount';  
  XmNoutlineColumnWidth = 'outlineColumnWidth';  
  XmCOutlineColumnWidth = 'OutlineColumnWidth';  
  XmNoutlineChangedCallback = 'outlineChangedCallback';  
  XmCOutlineChangedCallback = 'OutlineChangedCallback';  
  XmNoutlineButtonPolicy = 'outlineButtonPolicy';  
  XmCOutlineButtonPolicy = 'OutlineButtonPolicy';  
  XmROutlineButtonPolicy = 'OutlineButtonPolicy';  
  XmCDefaultVirtualBindings = 'DefaultVirtualBindings';  
  XmNdefaultVirtualBindings = 'defaultVirtualBindings';  
  XmCResizable = 'Resizable';  
  XmRDynamicPixmap = 'DynamicPixmap';  
  XmNpageChangedCallback = 'pageChangedCallback';  
  XmNarea = 'area';  
  XmNdetailShadowThickness = 'detailShadowThickness';  
  XmNsliderMark = 'sliderMark';  
  XmCSliderMark = 'SliderMark';  
  XmRSliderMark = 'SliderMark';  
  XmREnableBtn1Transfer = 'EnableBtn1Transfer';  
  XmNrenditionBackground = 'renditionBackground';  
  XmNrenditionForeground = 'renditionForeground';  
  XmCRenditionBackground = 'RenditionBackground';  
  XmCRenditionForeground = 'RenditionForeground';  
  XmNindeterminateInsensitivePixmap = 'indeterminateInsensitivePixmap';  
  XmCIndeterminateInsensitivePixmap = 'IndeterminateInsensitivePixmap';  
  XmNframeChildType = 'frameChildType';  
  XmCFrameChildType = 'FrameChildType';  
  XmNtextField = 'textField';  
  XmCTextField = 'TextField';  
  XmNenableThinThickness = 'enableThinThickness';  
  XmCEnableThinThickness = 'EnableThinThickness';  
  XmNprimaryColorSetId = 'primaryColorSetId';  
  XmCPrimaryColorSetId = 'PrimaryColorSetId';  
  XmNsecondaryColorSetId = 'secondaryColorSetId';  
  XmCSecondaryColorSetId = 'SecondaryColorSetId';  
  XmNtextColorSetId = 'textColorSetId';  
  XmCTextColorSetId = 'TextColorSetId';  
  XmNactiveColorSetId = 'activeColorSetId';  
  XmCActiveColorSetId = 'ActiveColorSetId';  
  XmNinactiveColorSetId = 'inactiveColorSetId';  
  XmCInactiveColorSetId = 'InactiveColorSetId';  
  XmNuseColorObj = 'useColorObj';  
  XmCUseColorObj = 'UseColorObj';  
  XmNuseTextColor = 'useTextColor';  
  XmCUseTextColor = 'UseTextColor';  
  XmNuseTextColorForList = 'useTextColorForList';  
  XmCUseTextColorForList = 'UseTextColorForList';  
  XmNuseMask = 'useMask';  
  XmCUseMask = 'UseMask';  
  XmNuseMultiColorIcons = 'useMultiColorIcons';  
  XmCUseMultiColorIcons = 'UseMultiColorIcons';  
  XmNuseIconFileCache = 'useIconFileCache';  
  XmCUseIconFileCache = 'UseIconFileCache';  
  XmSPIXEL_SET = 'Pixel Sets';  
  XmSCUSTOMIZE_DATA = 'Customize Data:';  
  XmSCOLOR_SRV_NAME = 'ColorServer';  
  XmNlist = 'list';  
  XmCList = 'List';  
  XmNarrowOrientation = 'arrowOrientation';  
  XmCArrowOrientation = 'ArrowOrientation';  
  XmRArrowOrientation = 'ArrowOrientation';  
  XmNpositionType = 'positionType';  
  XmCPositionType = 'PositionType';  
  XmRPositionType = 'PositionType';  
  XmNwrap = 'wrap';  
  XmCWrap = 'Wrap';  
  XmNpositionMode = 'positionMode';  
  XmCPositionMode = 'PositionMode';  
  XmRPositionMode = 'PositionMode';  
  XmNprintOrientation = 'printOrientation';  
  XmCPrintOrientation = 'PrintOrientation';  
  XmNprintOrientations = 'printOrientations';  
  XmCPrintOrientations = 'PrintOrientations';  
  XmNprintResolution = 'printResolution';  
  XmCPrintResolution = 'PrintResolution';  
  XmNprintResolutions = 'printResolutions';  
  XmCPrintResolutions = 'PrintResolutions';  
  XmNdefaultPixmapResolution = 'defaultPixmapResolution';  
  XmCDefaultPixmapResolution = 'DefaultPixmapResolution';  
  XmNstartJobCallback = 'startJobCallback';  
  XmNendJobCallback = 'endJobCallback';  
  XmNpageSetupCallback = 'pageSetupCallback';  
  XmNpdmNotificationCallback = 'pdmNotificationCallback';  
  XmNminX = 'minX';  
  XmNminY = 'minY';  
  XmNmaxX = 'maxX';  
  XmNmaxY = 'maxY';  
  XmCMinX = 'MinX';  
  XmCMinY = 'MinY';  
  XmCMaxX = 'MaxX';  
  XmCMaxY = 'MaxY';  
  XmNpreeditStartCallback = 'preeditStartCallback';  
  XmNpreeditDoneCallback = 'preeditDoneCallback';  
  XmNpreeditDrawCallback = 'preeditDrawCallback';  
  XmNpreeditCaretCallback = 'preeditCaretCallback';  
  XmNverifyPreedit = 'verifyPreedit';  
  XmCVerifyPreedit = 'VerifyPreedit';  
  XmNenableMultiKeyBindings = 'enableMultiKeyBindings';  
  XmCEnableMultiKeyBindings = 'EnableMultiKeyBindings';  
  XmRButtonFontList = 'ButtonFontList';  
  XmRLabelFontList = 'LabelFontList';  
  XmRTextFontList = 'TextFontList';  
  XmSPIXEL_SET_PROP = 'SDT Pixel Set';  
  XmS50_foreground = '50_foreground';  
  XmSunspecified_pixmap = 'unspecified_pixmap';  

var
    _XmStrings : Pchar;cvar;external libXm;

// {$include <X11/StringDefs.h>}

{ C++ extern C conditionnal removed }

const
  XmSTRING_DEFAULT_CHARSET = XmS;  
  XmSTRING_ISO8859_1 = 'ISO8859-1';  
  XmFONTLIST_DEFAULT_TAG = XmSFONTLIST_DEFAULT_TAG_STRING;  
  XmFONTLIST_DEFAULT_TAG_STRING = XmSXmFONTLIST_DEFAULT_TAG_STRING;  
  XmVaCASCADEBUTTON = 'cascadeButton';  
  XmVaCHECKBUTTON = 'checkButton';  
  XmVaDOUBLE_SEPARATOR = 'doubleSeparator';  
  XmVaPUSHBUTTON = 'pushButton';  
  XmVaRADIOBUTTON = 'radioButton';  
  XmVaSEPARATOR = 'separator';  
  XmVaSINGLE_SEPARATOR = 'singleSeparator';  
  XmVaTOGGLEBUTTON = 'checkButton';  
{$ifndef XmVaTITLE}

const
  XmVaTITLE = XtNtitle;  
{$endif}
{$ifndef XtCKeyboardFocusPolicy}

const
  XtCKeyboardFocusPolicy = XmCKeyboardFocusPolicy;  
{$endif}
{$ifndef XtCShellUnitType}

const
  XtCShellUnitType = XmCShellUnitType;  
{$endif}
{$ifndef XtNkeyboardFocusPolicy}

const
  XtNkeyboardFocusPolicy = XmNkeyboardFocusPolicy;  
{$endif}
{$ifndef XtNshellUnitType}

const
  XtNshellUnitType = XmNshellUnitType;  
{$endif}
{$ifndef XtRKeyboardFocusPolicy}

const
  XtRKeyboardFocusPolicy = XmRKeyboardFocusPolicy;  
{$endif}
{$ifndef XmRPrimBottomShadowPixmap}

const
  XmRPrimBottomShadowPixmap = XmRBottomShadowPixmap;  
{$endif}
{$ifndef XmRPrimHighlightPixmap}

const
  XmRPrimHighlightPixmap = XmRHighlightPixmap;  
{$endif}
{$ifndef XmRPrimTopShadowPixmap}

const
  XmRPrimTopShadowPixmap = XmRTopShadowPixmap;  
{$endif}
{$ifndef XmCAccelerators}

const
  XmCAccelerators = XtCAccelerators;  
{$endif}
{$ifndef XmCAllowShellResize}

const
  XmCAllowShellResize = XtCAllowShellResize;  
{$endif}
{$ifndef XmCArgc}

const
  XmCArgc = XtCArgc;  
{$endif}
{$ifndef XmCArgv}

const
  XmCArgv = XtCArgv;  
{$endif}
{$ifndef XmCBackground}

const
  XmCBackground = XtCBackground;  
{$endif}
{$ifndef XmCBaseHeight}

const
  XmCBaseHeight = XtCBaseHeight;  
{$endif}
{$ifndef XmCBaseHeight}

const
  XmCBaseHeight = XtCBaseHeight;  
{$endif}
{$ifndef XmCBaseWidth}

const
  XmCBaseWidth = XtCBaseWidth;  
{$endif}
{$ifndef XmCBaseWidth}

const
  XmCBaseWidth = XtCBaseWidth;  
{$endif}
{$ifndef XmCBitmap}

const
  XmCBitmap = XtCBitmap;  
{$endif}
{$ifndef XmCBoolean}

const
  XmCBoolean = XtCBoolean;  
{$endif}
{$ifndef XmCBorderColor}

const
  XmCBorderColor = XtCBorderColor;  
{$endif}
{$ifndef XmCBorderWidth}

const
  XmCBorderWidth = XtCBorderWidth;  
{$endif}
{$ifndef XmCCallback}

const
  XmCCallback = XtCCallback;  
{$endif}
{$ifndef XmCColor}

const
  XmCColor = XtCColor;  
{$endif}
{$ifndef XmCColormap}

const
  XmCColormap = XtCColormap;  
{$endif}
{$ifndef XmCCreatePopupChildProc}

const
  XmCCreatePopupChildProc = XtCCreatePopupChildProc;  
{$endif}
{$ifndef XmCCursor}

const
  XmCCursor = XtCCursor;  
{$endif}
{$ifndef XmCDepth}

const
  XmCDepth = XtCDepth;  
{$endif}
{$ifndef XmCDimension}

const
  XmCDimension = XtRDimension;  
{$endif}
{$ifndef XmCEditMode}

const
  XmCEditMode = XtREditMode;  
{$endif}
{$ifndef XmCEditType}

const
  XmCEditType = XtCEditType;  
{$endif}
{$ifndef XmCEventBindings}

const
  XmCEventBindings = XtCEventBindings;  
{$endif}
{$ifndef XmCFile}

const
  XmCFile = XtCFile;  
{$endif}
{$ifndef XmCFont}

const
  XmCFont = XtCFont;  
{$endif}
{$ifndef XmCFontSet}

const
  XmCFontSet = XtCFontSet;  
{$endif}
{$ifndef XmCForeground}

const
  XmCForeground = XtCForeground;  
{$endif}
{$ifndef XmCFraction}

const
  XmCFraction = XtCFraction;  
{$endif}
{$ifndef XmCFunction}

const
  XmCFunction = XtCFunction;  
{$endif}
{$ifndef XmCGeometry}

const
  XmCGeometry = XtCGeometry;  
{$endif}
{$ifndef XmCHSpace}

const
  XmCHSpace = XtCHSpace;  
{$endif}
{$ifndef XmCHeight}

const
  XmCHeight = XtCHeight;  
{$endif}
{$ifndef XmCHeightInc}

const
  XmCHeightInc = XtCHeightInc;  
{$endif}
{$ifndef XmCIconMask}

const
  XmCIconMask = XtCIconMask;  
{$endif}
{$ifndef XmCIconName}

const
  XmCIconName = XtCIconName;  
{$endif}
{$ifndef XmCIconNameEncoding}

const
  XmCIconNameEncoding = XtCIconNameEncoding;  
{$endif}
{$ifndef XmCIconPixmap}

const
  XmCIconPixmap = XtCIconPixmap;  
{$endif}
{$ifndef XmCIconWindow}

const
  XmCIconWindow = XtCIconWindow;  
{$endif}
{$ifndef XmCIconX}

const
  XmCIconX = XtCIconX;  
{$endif}
{$ifndef XmCIconY}

const
  XmCIconY = XtCIconY;  
{$endif}
{$ifndef XmCIconic}

const
  XmCIconic = XtCIconic;  
{$endif}
{$ifndef XmCIndex}

const
  XmCIndex = XtCIndex;  
{$endif}
{$ifndef XmCInitialResourcesPersistent}

const
  XmCInitialResourcesPersistent = XtCInitialResourcesPersistent;  
{$endif}
{$ifndef XmCInitialState}

const
  XmCInitialState = XtCInitialState;  
{$endif}
{$ifndef XmCInput}

const
  XmCInput = XtCInput;  
{$endif}
{$ifndef XmCInsertPosition}

const
  XmCInsertPosition = XtCInsertPosition;  
{$endif}
{$ifndef XmCInterval}

const
  XmCInterval = XtCInterval;  
{$endif}
{$ifndef XmCJustify}

const
  XmCJustify = XtCJustify;  
{$endif}
{$ifndef XmCLabel}

const
  XmCLabel = XtCLabel;  
{$endif}
{$ifndef XmCLength}

const
  XmCLength = XtCLength;  
{$endif}
{$ifndef XmCMappedWhenManaged}

const
  XmCMappedWhenManaged = XtCMappedWhenManaged;  
{$endif}
{$ifndef XmCMargin}

const
  XmCMargin = XtCMargin;  
{$endif}
{$ifndef XmCMaxAspectX}

const
  XmCMaxAspectX = XtCMaxAspectX;  
{$endif}
{$ifndef XmCMaxAspectY}

const
  XmCMaxAspectY = XtCMaxAspectY;  
{$endif}
{$ifndef XmCMaxHeight}

const
  XmCMaxHeight = XtCMaxHeight;  
{$endif}
{$ifndef XmCMaxWidth}

const
  XmCMaxWidth = XtCMaxWidth;  
{$endif}
{$ifndef XmCMenuEntry}

const
  XmCMenuEntry = XtCMenuEntry;  
{$endif}
{$ifndef XmCMinAspectX}

const
  XmCMinAspectX = XtCMinAspectX;  
{$endif}
{$ifndef XmCMinAspectY}

const
  XmCMinAspectY = XtCMinAspectY;  
{$endif}
{$ifndef XmCMinHeight}

const
  XmCMinHeight = XtCMinHeight;  
{$endif}
{$ifndef XmCMinWidth}

const
  XmCMinWidth = XtCMinWidth;  
{$endif}
{$ifndef XmCNotify}

const
  XmCNotify = XtCNotify;  
{$endif}
{$ifndef XmCOrientation}

const
  XmCOrientation = XtCOrientation;  
{$endif}
{$ifndef XmCOverrideRedirect}

const
  XmCOverrideRedirect = XtCOverrideRedirect;  
{$endif}
{$ifndef XmCParameter}

const
  XmCParameter = XtCParameter;  
{$endif}
{$ifndef XmCPixmap}

const
  XmCPixmap = XtCPixmap;  
{$endif}
{$ifndef XmCPosition}

const
  XmCPosition = XtCPosition;  
{$endif}
{$ifndef XmCReadOnly}

const
  XmCReadOnly = XtCReadOnly;  
{$endif}
{$ifndef XmCResize}

const
  XmCResize = XtCResize;  
{$endif}
{$ifndef XmCReverseVideo}

const
  XmCReverseVideo = XtCReverseVideo;  
{$endif}
{$ifndef XmCSaveUnder}

const
  XmCSaveUnder = XtCSaveUnder;  
{$endif}
{$ifndef XmCScreen}

const
  XmCScreen = XtCScreen;  
{$endif}
{$ifndef XmCScrollDCursor}

const
  XmCScrollDCursor = XtCScrollDCursor;  
{$endif}
{$ifndef XmCScrollHCursor}

const
  XmCScrollHCursor = XtCScrollHCursor;  
{$endif}
{$ifndef XmCScrollLCursor}

const
  XmCScrollLCursor = XtCScrollLCursor;  
{$endif}
{$ifndef XmCScrollProc}

const
  XmCScrollProc = XtCScrollProc;  
{$endif}
{$ifndef XmCScrollRCursor}

const
  XmCScrollRCursor = XtCScrollRCursor;  
{$endif}
{$ifndef XmCScrollUCursor}

const
  XmCScrollUCursor = XtCScrollUCursor;  
{$endif}
{$ifndef XmCScrollVCursor}

const
  XmCScrollVCursor = XtCScrollVCursor;  
{$endif}
{$ifndef XmCSelection}

const
  XmCSelection = XtCSelection;  
{$endif}
{$ifndef XmCSelectionArray}

const
  XmCSelectionArray = XtCSelectionArray;  
{$endif}
{$ifndef XmCSensitive}

const
  XmCSensitive = XtCSensitive;  
{$endif}
{$ifndef XmCSpace}

const
  XmCSpace = XtCSpace;  
{$endif}
{$ifndef XmCString}

const
  XmCString = XtCString;  
{$endif}
{$ifndef XmCTextOptions}

const
  XmCTextOptions = XtCTextOptions;  
{$endif}
{$ifndef XmCTextPosition}

const
  XmCTextPosition = XtCTextPosition;  
{$endif}
{$ifndef XmCTextSink}

const
  XmCTextSink = XtCTextSink;  
{$endif}
{$ifndef XmCTextSource}

const
  XmCTextSource = XtCTextSource;  
{$endif}
{$ifndef XmCThickness}

const
  XmCThickness = XtCThickness;  
{$endif}
{$ifndef XmCThumb}

const
  XmCThumb = XtCThumb;  
{$endif}
{$ifndef XmCTitle}

const
  XmCTitle = XtCTitle;  
{$endif}
{$ifndef XmCTitleEncoding}

const
  XmCTitleEncoding = XtCTitleEncoding;  
{$endif}
{$ifndef XmCTransient}

const
  XmCTransient = XtCTransient;  
{$endif}
{$ifndef XmCTransientFor}

const
  XmCTransientFor = XtCTransientFor;  
{$endif}
{$ifndef XmCTranslations}

const
  XmCTranslations = XtCTranslations;  
{$endif}
{$ifndef XmCVSpace}

const
  XmCVSpace = XtCVSpace;  
{$endif}
{$ifndef XmCValue}

const
  XmCValue = XtCValue;  
{$endif}
{$ifndef XmCVisual}

const
  XmCVisual = XtCVisual;  
{$endif}
{$ifndef XmCWaitForWm}

const
  XmCWaitForWm = XtCWaitForWm;  
{$endif}
{$ifndef XmCWidget}

const
  XmCWidget = XtRWidget;  
{$endif}
{$ifndef XmCWidth}

const
  XmCWidth = XtCWidth;  
{$endif}
{$ifndef XmCWidthInc}

const
  XmCWidthInc = XtCWidthInc;  
{$endif}
{$ifndef XmCWinGravity}

const
  XmCWinGravity = XtCWinGravity;  
{$endif}
{$ifndef XmCWindow}

const
  XmCWindow = XtCWindow;  
{$endif}
{$ifndef XmCWindowGroup}

const
  XmCWindowGroup = XtCWindowGroup;  
{$endif}
{$ifndef XmCWmTimeout}

const
  XmCWmTimeout = XtCWmTimeout;  
{$endif}
{$ifndef XmCX}

const
  XmCX = XtCX;  
{$endif}
{$ifndef XmCY}

const
  XmCY = XtCY;  
{$endif}
{$ifndef XmNaccelerators}

const
  XmNaccelerators = XtNaccelerators;  
{$endif}
{$ifndef XmNallowShellResize}

const
  XmNallowShellResize = XtNallowShellResize;  
{$endif}
{$ifndef XmNancestorSensitive}

const
  XmNancestorSensitive = XtNancestorSensitive;  
{$endif}
{$ifndef XmNargc}

const
  XmNargc = XtNargc;  
{$endif}
{$ifndef XmNargv}

const
  XmNargv = XtNargv;  
{$endif}
{$ifndef XmNbackground}

const
  XmNbackground = XtNbackground;  
{$endif}
{$ifndef XmNbackgroundPixmap}

const
  XmNbackgroundPixmap = XtNbackgroundPixmap;  
{$endif}
{$ifndef XmNbaseHeight}

const
  XmNbaseHeight = XtNbaseHeight;  
{$endif}
{$ifndef XmNbaseHeight}

const
  XmNbaseHeight = XtNbaseHeight;  
{$endif}
{$ifndef XmNbaseWidth}

const
  XmNbaseWidth = XtNbaseWidth;  
{$endif}
{$ifndef XmNbaseWidth}

const
  XmNbaseWidth = XtNbaseWidth;  
{$endif}
{$ifndef XmNbitmap}

const
  XmNbitmap = XtNbitmap;  
{$endif}
{$ifndef XmNborder}

const
  XmNborder = XtNborder;  
{$endif}
{$ifndef XmNborderColor}

const
  XmNborderColor = XtNborderColor;  
{$endif}
{$ifndef XmNborderPixmap}

const
  XmNborderPixmap = XtNborderPixmap;  
{$endif}
{$ifndef XmNborderWidth}

const
  XmNborderWidth = XtNborderWidth;  
{$endif}
{$ifndef XmNcallback}

const
  XmNcallback = XtNcallback;  
{$endif}
{$ifndef XmNchildren}

const
  XmNchildren = XtNchildren;  
{$endif}
{$ifndef XmNcolormap}

const
  XmNcolormap = XtNcolormap;  
{$endif}
{$ifndef XmNcreatePopupChildProc}

const
  XmNcreatePopupChildProc = XtNcreatePopupChildProc;  
{$endif}
{$ifndef XmNdepth}

const
  XmNdepth = XtNdepth;  
{$endif}
{$ifndef XmNdestroyCallback}

const
  XmNdestroyCallback = XtNdestroyCallback;  
{$endif}
{$ifndef XmNeditType}

const
  XmNeditType = XtNeditType;  
{$endif}
{$ifndef XmNfile}

const
  XmNfile = XtNfile;  
{$endif}
{$ifndef XmNfont}

const
  XmNfont = XtNfont;  
{$endif}
{$ifndef XmNfontSet}

const
  XmNfontSet = XtNfontSet;  
{$endif}
{$ifndef XmNforceBars}

const
  XmNforceBars = XtNforceBars;  
{$endif}
{$ifndef XmNforeground}

const
  XmNforeground = XtNforeground;  
{$endif}
{$ifndef XmNfunction}

const
  XmNfunction = XtNfunction;  
{$endif}
{$ifndef XmNgeometry}

const
  XmNgeometry = XtNgeometry;  
{$endif}
{$ifndef XmNheight}

const
  XmNheight = XtNheight;  
{$endif}
{$ifndef XmNheightInc}

const
  XmNheightInc = XtNheightInc;  
{$endif}
{$ifndef XmNhighlight}

const
  XmNhighlight = XtNhighlight;  
{$endif}
{$ifndef XmNiconMask}

const
  XmNiconMask = XtNiconMask;  
{$endif}
{$ifndef XmNiconName}

const
  XmNiconName = XtNiconName;  
{$endif}
{$ifndef XmNiconNameEncoding}

const
  XmNiconNameEncoding = XtNiconNameEncoding;  
{$endif}
{$ifndef XmNiconPixmap}

const
  XmNiconPixmap = XtNiconPixmap;  
{$endif}
{$ifndef XmNiconWindow}

const
  XmNiconWindow = XtNiconWindow;  
{$endif}
{$ifndef XmNiconX}

const
  XmNiconX = XtNiconX;  
{$endif}
{$ifndef XmNiconY}

const
  XmNiconY = XtNiconY;  
{$endif}
{$ifndef XmNiconic}

const
  XmNiconic = XtNiconic;  
{$endif}
{$ifndef XmNindex}

const
  XmNindex = XtNindex;  
{$endif}
{$ifndef XmNinitialResourcesPersistent}

const
  XmNinitialResourcesPersistent = XtNinitialResourcesPersistent;  
{$endif}
{$ifndef XmNinitialState}

const
  XmNinitialState = XtNinitialState;  
{$endif}
{$ifndef XmNinnerHeight}

const
  XmNinnerHeight = XtNinnerHeight;  
{$endif}
{$ifndef XmNinnerWidth}

const
  XmNinnerWidth = XtNinnerWidth;  
{$endif}
{$ifndef XmNinnerWindow}

const
  XmNinnerWindow = XtNinnerWindow;  
{$endif}
{$ifndef XmNinput}

const
  XmNinput = XtNinput;  
{$endif}
{$ifndef XmNinsertPosition}

const
  XmNinsertPosition = XtNinsertPosition;  
{$endif}
{$ifndef XmNinternalHeight}

const
  XmNinternalHeight = XtNinternalHeight;  
{$endif}
{$ifndef XmNinternalWidth}

const
  XmNinternalWidth = XtNinternalWidth;  
{$endif}
{$ifndef XmNjumpProc}

const
  XmNjumpProc = XtNjumpProc;  
{$endif}
{$ifndef XmNjustify}

const
  XmNjustify = XtNjustify;  
{$endif}
{$ifndef XmNlength}

const
  XmNlength = XtNlength;  
{$endif}
{$ifndef XmNlowerRight}

const
  XmNlowerRight = XtNlowerRight;  
{$endif}
{$ifndef XmNmappedWhenManaged}

const
  XmNmappedWhenManaged = XtNmappedWhenManaged;  
{$endif}
{$ifndef XmNmaxAspectX}

const
  XmNmaxAspectX = XtNmaxAspectX;  
{$endif}
{$ifndef XmNmaxAspectY}

const
  XmNmaxAspectY = XtNmaxAspectY;  
{$endif}
{$ifndef XmNmaxHeight}

const
  XmNmaxHeight = XtNmaxHeight;  
{$endif}
{$ifndef XmNmaxWidth}

const
  XmNmaxWidth = XtNmaxWidth;  
{$endif}
{$ifndef XmNmenuEntry}

const
  XmNmenuEntry = XtNmenuEntry;  
{$endif}
{$ifndef XmNminAspectX}

const
  XmNminAspectX = XtNminAspectX;  
{$endif}
{$ifndef XmNminAspectY}

const
  XmNminAspectY = XtNminAspectY;  
{$endif}
{$ifndef XmNminHeight}

const
  XmNminHeight = XtNminHeight;  
{$endif}
{$ifndef XmNminWidth}

const
  XmNminWidth = XtNminWidth;  
{$endif}
{$ifndef XmNname}

const
  XmNname = XtNname;  
{$endif}
{$ifndef XmNnotify}

const
  XmNnotify = XtNnotify;  
{$endif}
{$ifndef XmNnumChildren}

const
  XmNnumChildren = XtNnumChildren;  
{$endif}
{$ifndef XmNorientation}

const
  XmNorientation = XtNorientation;  
{$endif}
{$ifndef XmNoverrideRedirect}

const
  XmNoverrideRedirect = XtNoverrideRedirect;  
{$endif}
{$ifndef XmNparameter}

const
  XmNparameter = XtNparameter;  
{$endif}
{$ifndef XmNpixmap}

const
  XmNpixmap = XtNpixmap;  
{$endif}
{$ifndef XmNpopdownCallback}

const
  XmNpopdownCallback = XtNpopdownCallback;  
{$endif}
{$ifndef XmNpopupCallback}

const
  XmNpopupCallback = XtNpopupCallback;  
{$endif}
{$ifndef XmNresize}

const
  XmNresize = XtNresize;  
{$endif}
{$ifndef XmNreverseVideo}

const
  XmNreverseVideo = XtNreverseVideo;  
{$endif}
{$ifndef XmNsaveUnder}

const
  XmNsaveUnder = XtNsaveUnder;  
{$endif}
{$ifndef XmNscreen}

const
  XmNscreen = XtNscreen;  
{$endif}
{$ifndef XmNscrollDCursor}

const
  XmNscrollDCursor = XtNscrollDCursor;  
{$endif}
{$ifndef XmNscrollHCursor}

const
  XmNscrollHCursor = XtNscrollHCursor;  
{$endif}
{$ifndef XmNscrollLCursor}

const
  XmNscrollLCursor = XtNscrollLCursor;  
{$endif}
{$ifndef XmNscrollProc}

const
  XmNscrollProc = XtNscrollProc;  
{$endif}
{$ifndef XmNscrollRCursor}

const
  XmNscrollRCursor = XtNscrollRCursor;  
{$endif}
{$ifndef XmNscrollUCursor}

const
  XmNscrollUCursor = XtNscrollUCursor;  
{$endif}
{$ifndef XmNscrollVCursor}

const
  XmNscrollVCursor = XtNscrollVCursor;  
{$endif}
{$ifndef XmNselection}

const
  XmNselection = XtNselection;  
{$endif}
{$ifndef XmNselectionArray}

const
  XmNselectionArray = XtNselectionArray;  
{$endif}
{$ifndef XmNsensitive}

const
  XmNsensitive = XtNsensitive;  
{$endif}
{$ifndef XmNshown}

const
  XmNshown = XtNshown;  
{$endif}
{$ifndef XmNspace}

const
  XmNspace = XtNspace;  
{$endif}
{$ifndef XmNstring}

const
  XmNstring = XtNstring;  
{$endif}
{$ifndef XmNtextOptions}

const
  XmNtextOptions = XtNtextOptions;  
{$endif}
{$ifndef XmNtextSink}

const
  XmNtextSink = XtNtextSink;  
{$endif}
{$ifndef XmNtextSource}

const
  XmNtextSource = XtNtextSource;  
{$endif}
{$ifndef XmNthickness}

const
  XmNthickness = XtNthickness;  
{$endif}
{$ifndef XmNthumb}

const
  XmNthumb = XtNthumb;  
{$endif}
{$ifndef XmNthumbProc}

const
  XmNthumbProc = XtNthumbProc;  
{$endif}
{$ifndef XmNtitle}

const
  XmNtitle = XtNtitle;  
{$endif}
{$ifndef XmNtitleEncoding}

const
  XmNtitleEncoding = XtNtitleEncoding;  
{$endif}
{$ifndef XmNtop}

const
  XmNtop = XtNtop;  
{$endif}
{$ifndef XmNtransient}

const
  XmNtransient = XtNtransient;  
{$endif}
{$ifndef XmNtransientFor}

const
  XmNtransientFor = XtNtransientFor;  
{$endif}
{$ifndef XmNtransientFor}

const
  XmNtransientFor = XtNtransientFor;  
{$endif}
{$ifndef XmNtranslations}

const
  XmNtranslations = XtNtranslations;  
{$endif}
{$ifndef XmNupdate}

const
  XmNupdate = XtNupdate;  
{$endif}
{$ifndef XmNuseBottom}

const
  XmNuseBottom = XtNuseBottom;  
{$endif}
{$ifndef XmNuseRight}

const
  XmNuseRight = XtNuseRight;  
{$endif}
{$ifndef XmNvalue}

const
  XmNvalue = XtNvalue;  
{$endif}
{$ifndef XmNvisual}

const
  XmNvisual = XtNvisual;  
{$endif}
{$ifndef XmNwaitForWm}

const
  XmNwaitForWm = XtNwaitForWm;  
{$endif}
{$ifndef XmNwidth}

const
  XmNwidth = XtNwidth;  
{$endif}
{$ifndef XmNwidthInc}

const
  XmNwidthInc = XtNwidthInc;  
{$endif}
{$ifndef XmNwinGravity}

const
  XmNwinGravity = XtNwinGravity;  
{$endif}
{$ifndef XmNwindow}

const
  XmNwindow = XtNwindow;  
{$endif}
{$ifndef XmNwindowGroup}

const
  XmNwindowGroup = XtNwindowGroup;  
{$endif}
{$ifndef XmNwmTimeout}

const
  XmNwmTimeout = XtNwmTimeout;  
{$endif}
{$ifndef XmNx}

const
  XmNx = XtNx;  
{$endif}
{$ifndef XmNy}

const
  XmNy = XtNy;  
{$endif}
{$ifndef XmRAcceleratorTable}

const
  XmRAcceleratorTable = XtRAcceleratorTable;  
{$endif}
{$ifndef XmRAtom}

const
  XmRAtom = XtRAtom;  
{$endif}
{$ifndef XmRBitmap}

const
  XmRBitmap = XtRBitmap;  
{$endif}
{$ifndef XmRBool}

const
  XmRBool = XtRBool;  
{$endif}
{$ifndef XmRBoolean}

const
  XmRBoolean = XtRBoolean;  
{$endif}
{$ifndef XmRCallProc}

const
  XmRCallProc = XtRCallProc;  
{$endif}
{$ifndef XmRCallback}

const
  XmRCallback = XtRCallback;  
{$endif}
{$ifndef XmRCardinal}

const
  XmRCardinal = XtRCardinal;  
{$endif}
{$ifndef XmRColor}

const
  XmRColor = XtRColor;  
{$endif}
{$ifndef XmRColormap}

const
  XmRColormap = XtRColormap;  
{$endif}
{$ifndef XmRCursor}

const
  XmRCursor = XtRCursor;  
{$endif}
{$ifndef XmRDimension}

const
  XmRDimension = XtRDimension;  
{$endif}
{$ifndef XmRDisplay}

const
  XmRDisplay = XtRDisplay;  
{$endif}
{$ifndef XmREditMode}

const
  XmREditMode = XtREditMode;  
{$endif}
{$ifndef XmREnum}

const
  XmREnum = XtREnum;  
{$endif}
{$ifndef XmRFile}

const
  XmRFile = XtRFile;  
{$endif}
{$ifndef XmRFloat}

const
  XmRFloat = XtRFloat;  
{$endif}
{$ifndef XmRFont}

const
  XmRFont = XtRFont;  
{$endif}
{$ifndef XmRFontSet}

const
  XmRFontSet = XtRFontSet;  
{$endif}
{$ifndef XmRFontStruct}

const
  XmRFontStruct = XtRFontStruct;  
{$endif}
{$ifndef XmRFunction}

const
  XmRFunction = XtRFunction;  
{$endif}
{$ifndef XmRGeometry}

const
  XmRGeometry = XtRGeometry;  
{$endif}
{$ifndef XmRImmediate}

const
  XmRImmediate = XtRImmediate;  
{$endif}
{$ifndef XmRInitialState}

const
  XmRInitialState = XtRInitialState;  
{$endif}
{$ifndef XmRInt}

const
  XmRInt = XtRInt;  
{$endif}
{$ifndef XmRJustify}

const
  XmRJustify = XtRJustify;  
{$endif}
{$ifndef XmRLongBoolean}

const
  XmRLongBoolean = XtRLongBoolean;  
{$endif}
{$ifndef XmROrientation}

const
  XmROrientation = XtROrientation;  
{$endif}
{$ifndef XmRObject}

const
  XmRObject = XtRObject;  
{$endif}
{$ifndef XmRPixel}

const
  XmRPixel = XtRPixel;  
{$endif}
{$ifndef XmRPixmap}

const
  XmRPixmap = XtRPixmap;  
{$endif}
{$ifndef XmRPointer}

const
  XmRPointer = XtRPointer;  
{$endif}
{$ifndef XmRPosition}

const
  XmRPosition = XtRPosition;  
{$endif}
{$ifndef XmRScreen}

const
  XmRScreen = XtRScreen;  
{$endif}
{$ifndef XmRShort}

const
  XmRShort = XtRShort;  
{$endif}
{$ifndef XmRString}

const
  XmRString = XtRString;  
{$endif}
{$ifndef XmRStringArray}

const
  XmRStringArray = XtRStringArray;  
{$endif}
{$ifndef XmRStringTable}

const
  XmRStringTable = XtRStringTable;  
{$endif}
{$ifndef XmRTextPosition}

const
  XmRTextPosition = XtCTextPosition;  
{$endif}
{$ifndef XmRTranslationTable}

const
  XmRTranslationTable = XtRTranslationTable;  
{$endif}
{$ifndef XmRUnsignedChar}

const
  XmRUnsignedChar = XtRUnsignedChar;  
{$endif}
{$ifndef XmRVisual}

const
  XmRVisual = XtRVisual;  
{$endif}
{$ifndef XmRWidget}

const
  XmRWidget = XtRWidget;  
{$endif}
{$ifndef XmRWidgetClass}

const
  XmRWidgetClass = XtRWidgetClass;  
{$endif}
{$ifndef XmRWidgetList}

const
  XmRWidgetList = XtRWidgetList;  
{$endif}
{$ifndef XmRWindow}

const
  XmRWindow = XtRWindow;  
{$endif}
{$ifndef XmNtoolTipString}

const
  XmNtoolTipString = 'toolTipString';  
{$endif}
{$ifndef XmCToolTipString}

const
  XmCToolTipString = 'ToolTipString';  
{$endif}
{$ifndef XmNtoolTipPostDelay}

const
  XmNtoolTipPostDelay = 'toolTipPostDelay';  
{$endif}
{$ifndef XmCToolTipPostDelay}

const
  XmCToolTipPostDelay = 'ToolTipPostDelay';  
{$endif}
{$ifndef XmNtoolTipPostDuration}

const
  XmNtoolTipPostDuration = 'toolTipPostDuration';  
{$endif}
{$ifndef XmCToolTipPostDuration}

const
  XmCToolTipPostDuration = 'ToolTipPostDuration';  
{$endif}
{$ifndef XmNtoolTipEnable}

const
  XmNtoolTipEnable = 'toolTipEnable';  
{$endif}
{$ifndef XmCToolTipEnable}

const
  XmCToolTipEnable = 'ToolTipEnable';  
{$endif}
{$ifndef XmNanimate}

const
  XmNanimate = 'animate';  
{$endif}
{$ifndef XmCAnimate}

const
  XmCAnimate = 'Animate';  
{$endif}
{$endif}
{ _XmStrDefs_h_  }

implementation


end.
