unit XmXmStrDefs23;

interface

uses
  XTIntrinsic;

// {$include <X11/Intrinsic.h>}

{ $TOG: makestrs.c /main/11 1998/02/06 11:24:15 kaleb $  }
{ This file is automatically generated.  }
{ Default ABI version -- Do not edit  }
{ TOG: xmstring.list /main/5 1997/06/20 08:37:02 samborn  }
const
  XmNdefaultEntryLabelRenderTable = 'defaultEntryLabelRenderTable';  
  XmNentryLabelRenderTable = 'entryLabelRenderTable';  
  XmNpixmapPlacement = 'pixmapPlacement';  
  XmCPixmapPlacement = 'PixmapPlacement';  
  XmRPixmapPlacement = 'PixmapPlacement';  
  XmNpixmapTextPadding = 'pixmapTextPadding';  
  XmNfontStyle = 'fontStyle';  
  XmCFontStyle = 'FontStyle';  
  XmNfontSize = 'fontSize';  
  XmCFontSize = 'FontSize';  
  XmNfontFoundry = 'fontFoundry';  
  XmCFontFoundry = 'FontFoundry';  
  XmNfontEncoding = 'fontEncoding';  
  XmCFontEncoding = 'FontEncoding';  
  XmNxftFont = 'xftFont';  
  XmCXftFont = 'XftFont';  
  XmSUTF8_STRING = 'UTF8_STRING';  
  var
    _XmStrings23 : Pchar;cvar;external libXm;

implementation


end.
